### ISSUE TITLE
Add Additional Flags: Include/Exclude Patterns for folders/files - Improve Performance and Accuracy

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#1720]
**Is your feature request related to a problem? Please describe.**
When running kics over a big repository, I want to discard by default some folders and files using Include or Exclude patterns in order to avoid spending time scanning it and generating results that user is not interested in. 
For example, if in my repo I have very nested folders, by the IaC files I'm interesting to scan are only in the root of repository, so providing an include pattern like this "--include_pattern Dockerfile" will save some time, or an exclude pattern might help as well, like excluding test, 3rd party or build folders folders: "--exclude_pattern '*test*,node_modules,build'"

**Describe the solution you'd like**
Kics should be able to handle additional flags to Exclude or Include Folders/Files

**Describe alternatives you've considered**
Looking at current way Checkmarx CLI works with inclusions/Exclusions might help

**Comment by rogeriopeixotocx** [comment]
I think it would be beneficial to also look for a `.kicsignore` in the scanned path and ignore the globs patterns stated inside this file. Similar to the way git works.

**Comment by felipe-avelar** [comment]
> @felipe-avelar I think it would be beneficial to also look for a `.kicsignore` in the scanned path and ignore the globs patterns stated inside this file. Similar to the way git works.

@ruigomescx suggested, and I agree with him, that, instead a `.kicsignore` file, this could be part of a configuration file, like the described in #1833
