### ISSUE TITLE
Need of additional Flags: High, Medium and Low Threshold flags

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#1721]
**Is your feature request related to a problem? Please describe.**
In order to start to introduce Kics to CI/CD processes, it would be great if we can, providing additional thresholds for High, Medium and Low results, break the build.

**Describe the solution you'd like**
3 new flags are needed:
- high
- medium
- low

**Describe alternatives you've considered**
Same exact logic as Checkmarx CLI

**Comment by rogeriopeixotocx** [comment]
being developed together with #2400
