### ISSUE TITLE
Scan kics with Gosec in build

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#1832]
**Is your feature request related to a problem? Please describe.**
Improve security of kics source code

**Describe the solution you'd like**
Add a step to perform Gosec scan in the build pipeline to get better secure code
https://github.com/securego/gosec

**Comment by ruigomescx** [comment]
Thanks for the suggestion @miguelfreitas93!

**Comment by rogeriopeixotocx** [comment]
Issue opened by @felipe-avelar got solved and the PR merged but since then they haven't released a new version yet so we can't move this forward unless we build gosec and run it without using the GH action https://github.com/securego/gosec/pull/565

**Comment by miguelfreitas93** [comment]
@rogeriopeixotocx you can run an action of a specific commit or version or branch:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
steps:    
  # Reference a specific commit
  - uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
  # Reference the major version of a release
  - uses: actions/setup-node@v1
  # Reference a minor version of a release
  - uses: actions/setup-node@v1.2
  # Reference a branch
  - uses: actions/setup-node@main

**Comment by rogeriopeixotocx** [comment]
@miguelfreitas93  Yes, that's true.. the issue is that [their GH action uses the latest docker image published](https://github.com/securego/gosec/blob/master/action.yml#L13) and they only publish a docker image whenever there's a new release. So we're stuck the same unless we check out the project build it, and run the binary.. which is not very difficult.

**Comment by rogeriopeixotocx** [comment]
@miguelfreitas93  better yet check their [dockerfile ](https://github.com/securego/gosec/blob/master/Dockerfile)and [makefile](https://github.com/securego/gosec/blob/master/Makefile)for instructions on how to build it
