### ISSUE TITLE
Incorrect error reporting Kinesis SSE Not Configured

### ISSUE THREAD

**Issue by frediana** [Checkmarx/kics#1858]
### Steps to Reproduce the Problem

1.  Given a Kinesis Data stream, with encryption enabled
2. And a Kinesis Firehose Delivery stream with the preceding Kinesis Data stream configured as data source

refering to https://docs.aws.amazon.com/firehose/latest/dev/encryption.html

"When you configure a Kinesis data stream as the data source of a Kinesis Data Firehose delivery stream, Kinesis Data Firehose no longer stores the data at rest. Instead, the data is stored in the data stream."

Thus, unless I missed something, Kics should not report  Attribute 'server_side_encryption' is set on the Kinesis Firehose Delivery Stream in this particular situation.

**Comment by frediana** [comment]
If the issue is confirmed, I would be happy to contribute.

**Comment by ruigomescx** [comment]
@frediana First thanks for raising this issue!
I believe you are correct, in this scenario the result shouldn't appear. The problem should reside in this [query](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/kinesis_sse_not_configured/query.rego)
If you would like to contribute, feel free to create a pull request to address this issue.

To debug it's easy, you just need to run with the -d flag that will convert your terraform file to a .json representation and then you can copy paste the converted .json and the existing query into: https://play.openpolicyagent.org/ 
Or else, you can provide us a small snippet where this false positive is appearing and we will try to fix it.

Thanks!
