### ISSUE TITLE
[Similarity ID] Lot of errors "Unable to compute similarity id: illegal absolute path to file"

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#1977]
### Expected Behavior
No errors and Similarity ID properly computed.

### Actual Behavior
Lot of errors and no Similarity ID computed due to error "Unable to compute similarity id: illegal absolute path to file"

### Steps to Reproduce the Problem

1.  Scan Kics repository with Kics and verbose enabled

### Specifications

-   Version: 1.1.2
-   Platform: linux
-   Subsystem: docker

**Comment by ruigomescx** [comment]
Thanks @miguelfreitas93 we will look into this.
