### ISSUE TITLE
GitLab SAST Reports Integration

### ISSUE THREAD

**Issue by adam-moss** [Checkmarx/kics#1986]
**Is your feature request related to a problem? Please describe.**
It is frustrating when cli tool output has to be further processed or analysed to get up-front meaningful value, or cannot be integrated into existing development lifecycle tooling.

**Describe the solution you'd like**
It would be nice if a feature flag could be added to output the json report in GitLab SAST format, so that it is immediately consumable within the GitLab UI (merge request widget, Security Dashboard etc) through the standard report artifact mechanism in GitLab CI.

**Describe alternatives you've considered**
Processing the output directly with `jq` or equivalent to transform the output.

**Additional context**
Further information on the integrated reports formats included as part of GitLab CI are here: https://docs.gitlab.com/ee/development/integrations/secure.html#report.  SAST json definition is here: https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/raw/v13.1.0/dist/sast-report-format.json

**Comment by ruigomescx** [comment]
Hi @adam-moss. Thank you for your feedback. Currently we're only outputting the results to our internal .json format. 

At the moment we're also working on adding support for SARIF format:
http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html

We will look into your suggestion, to see we can support it. Feel free to contribute also!
Thank you

**Comment by adam-moss** [comment]
Hi @ruigomescx , there is actually an existing [issue within gitlab](https://gitlab.com/gitlab-org/gitlab/-/issues/118496) to support SARIF, so hopefully there will be a happy confluent 😁
