### ISSUE TITLE
Clean duplicated queries for Terraform

### ISSUE THREAD

**Issue by NunoAraujoCX** [Checkmarx/kics#2029]
**Platform**
Terraform

**Description**
Need to clean these duplicated queries in Terraform:

- Cloudwatch without retention days
- Public ECR policy
- Insufficient password length
- No password reuse prevention
- All Users Group Gets Read Access
- SQLServer with Public Access
- Unprotected SQS Queue
- SSH Port Open
- Unprotected S3 Storage

**Comment by joaomartinscx** [comment]
Add these two to the list:
* *SSH Port Open* - it's already being addressed in *SSH (TCP:22) in Public Scope* and with incoming changes makes this query unnecessary
*  *Unprotected S3 Storage* - already addressed in *S3 bucket without encryption at REST* which also has incoming changes and makes this query unnecessary
