### ISSUE TITLE
Exclude category of queries 

### ISSUE THREAD

**Issue by ansidorov** [Checkmarx/kics#2161]
Good afternoon.
**Is your feature request related to a problem? Please describe.**
I would like to be able to perform exclude certain categories of requests. For example I believe I don't want to check Privileged containers in Kubernetes manifests.

**Describe the solution you'd like**
It should be some flag that would allow a list of categories, separated by commas and then queries from that category would not run on my source code.

**Describe alternatives you've considered**
Alternatively it could be a command to display all available check categories and the option to specify only specified categories for checking.

**Comment by ruigomescx** [comment]
Thanks for the request @ansidorov. We'll evaluate this question and get back to you.
