### ISSUE TITLE
Incorrect OPA results interpretation

### ISSUE THREAD

**Issue by Nikolasel** [Checkmarx/kics#2167]
### Expected Behavior
All findings should be displayed in the final result of kics.

### Actual Behavior
If the "searchKey" from the OPA result is equal for multiple lines in the input file, only the first occurrence is shown.
### Steps to Reproduce the Problem

Run kics with the following file (simple-pwd.yml):
```
test:
  password: abcdefg

test2:
  password: abcdefg
```

The result is:
```
Passwords And Secrets In Infrastructure Code, Severity: HIGH, Results: 1
	.../simple-pwd.yml:2
```
Since line 5 uses the same insecure password, the result should also contain line 5.

### Specifications

-   Version: 1.14
-   Platform: Linux
-   Subsystem: Common/Passwords And Secrets In Infrastructure Code

**Comment by ruigomescx** [comment]
Hi @Nikolasel. Thank you for reporting this bug, we will look into it.
