### ISSUE TITLE
Use short SHA for nightly builds

### ISSUE THREAD

**Issue by kaplanlior** [Checkmarx/kics#2222]
At the moment the nightly builds use the full SHA256 string, which creates very long build names.
Would be great to use short (8 chars) IDs to make those more easy to read.

e.g.
`git rev-parse --short 6250682d11ba8048de481857c09466cdcd5b5092
6250682`

**Comment by rogeriopeixotocx** [comment]
@kaplanlior Thank you Lior, we will take a look into that ASAP.
