### ISSUE TITLE
Include external queries option

### ISSUE THREAD

**Issue by kaplanlior** [Checkmarx/kics#2224]
KICS comes with a wide set of queries, which is great.
I want to request a feature that would ease people to create more queries.

ATM, for someone to add query, files must be added to KICS directory hierarchy.
If the user want to upgrade KICS he needs to remember to copy/move all the files
he'd added to the new copy of KICS.

If we have an option for KICS to include external queries it would simply the process.
Allowing a person or an organization to keep their customization between upgrades/changes, or to manage them on their GIT.

Please notice that in case the user uses this option, we also want to suggest he'd contribute those queries to KICS, so everyone can enjoy them. Linking to the contribution page.

**Comment by rogeriopeixotocx** [comment]
I'm adding here as a note that custom queries should enable the user to add external data. That will be accessed by `import data`: as suggested by @mukeshpilaniya in https://gitter.im/kics-io/community?at=6099011d20d4f02631b25f60

Reference for implementation: 
https://github.com/open-policy-agent/opa/blob/82cca627647165804f8cf042cfd7f84dd13ddecc/rego/rego.go#L873
https://github.com/Checkmarx/kics/blob/master/pkg/engine/inspector.go#L136-L141

cc: @oribendetcx @nunoocx
