### ISSUE TITLE
Comments aren't taken into consideration in the "line" presented in the results

### ISSUE THREAD

**Issue by Ruben-Silva** [Checkmarx/kics#2338]
### Expected Behavior
The `line` in the results refers to the end of the searchKey, and the attribute in which the vulnerability is present.

### Actual Behavior
The `line` doesn't take into consideration comments present in the samples. For example:

```
1- Resources:
2-  # VPC in which containers will be networked.
3-  # It has two public subnets, and two private subnets.
4-  # We distribute the subnets across the first two available subnets
5-  # for the region, for high availability.
6-  VPC:
7-    Type: AWS::EC2::VPC
8-    Properties:
9-      EnableDnsSupport: true
10-      EnableDnsHostnames: true
11-      CidrBlock: !FindInMap ['SubnetConfig', 'VPC', 'CIDR']

```
In this case, if a searchKey ends in the resouce "VPC", the line should be **6** in the results. However, the line that would appear would be **2**.

**Comment by rafaela-soares** [comment]
Hello, @Ruben-Silva 🙂 I hope you are doing well. Thank you so much for the bug report.
I am delighted to say this bug does not occur anymore.
 [](url)
![samplecomment](https://user-images.githubusercontent.com/74001161/134646537-6e7f681b-4130-4dc1-b583-8494c889eb67.PNG)
