### ISSUE TITLE
Line is incorrect in results if there is a previous occurrence of the same name used in searchKey

### ISSUE THREAD

**Issue by Ruben-Silva** [Checkmarx/kics#2339]
### Expected Behavior
`Line` topic in the results points to the end of the searchKey, the attribute in which the vulnerability is present.

### Actual Behavior
If there is a previous occurence of the same name that is present in the searchKey, then the line would take that into consideration. This happens most commonly when a resource is referenced previously in another resource, or when there is a comment with the same name as the attribute that has the vulnerability. For example:

```
1- SubnetAPublic:
2-    DependsOn: VPCCidrBlock
3-    Type: 'AWS::EC2::Subnet'
4-    Properties:
5-      #AssignIpv6AddressOnCreation: true # TODO can not be set if MapPublicIpOnLaunch is true as well
6-      AvailabilityZone: !Select [0, !GetAZs '']
7-      CidrBlock: !Sub '10.${ClassB}.0.0/20'
8-      Ipv6CidrBlock: !Select [0, !Cidr [!Select [0, !GetAtt 'VPC.Ipv6CidrBlocks'], 4, 64]]
9-      MapPublicIpOnLaunch: true
10-      VpcId: !Ref VPC
11-      Tags:
12-      - Key: Name
13-        Value: 'A public'
14-      - Key: Reach
15-        Value: public
```
In this case, the vulnerability being that the attribute "MapPublicIpOnLaunch" should be false, the line points to **5**, instead of the correct **9**.

**Comment by joaoReigota1** [comment]
This issue has been fixed with the implementation of the searchLine #3977
