### ISSUE TITLE
Add CPU and Memory usage to logs

### ISSUE THREAD

**Issue by ruigomescx** [Checkmarx/kics#2379]
### Description
Provide a way to get metrics of KICS scanning performance to add more relevant information when reporting some issue, for example.

In our generated log file, we should have information about CPU peak usage and memory peak usage.

**Comment by rogeriopeixotocx** [comment]
We can achieve this with [zerolog](https://github.com/rs/zerolog#log-sampling) and profile(github.com/pkg/profile)
