### ISSUE TITLE
Expose different status codes depending on scanning results

### ISSUE THREAD

**Issue by ruigomescx** [Checkmarx/kics#2400]
### Description
Currently KICS when scanning only reports exit status code 0 when the scan has occurred successfully. This exit status code is linked with the current program execution and not the reporting of results/vulnerabilities.

We should give status code depending on whether results were found or not, and even depending on the severity of results found.
Also, we should output specific status code for when KICS doesn't run successfully (queries didn't load, program aborted earlier, etc.)

First, the a list of status code should be presented, before implementing them.

**Comment by rogeriopeixotocx** [comment]
Reopened as draft in #2726

**Comment by rogeriopeixotocx** [comment]
@kaplanlior @markmishaevcx @nunoocx @ruigomescx 

We should discuss here the requirements for this feature.
