### ISSUE TITLE
Typo on the kics/docs/integrations_ghactions.md page (output-path, should be output_path)

### ISSUE THREAD

**Issue by juegge** [Checkmarx/kics#2466]
The code for the KICS Github action with Sarif file upload has a typo
it says
[...]
 - name: KICS Github Action
        id: kics
        uses: Checkmarx/kics-github-action@v1.0
        with:
          path: terraform/
          output-path: 'results.sarif'
          
  But should be 
 - name: KICS Github Action
        id: kics
        uses: Checkmarx/kics-github-action@v1.0
        with:
          path: terraform/
          output_path: 'results.sarif'

Pse change the hyphen in output-path to an underscore, i. e. output_path

**Comment by rogeriopeixotocx** [comment]
Thank you for your feedback @juegge I'll take care of that.
