### ISSUE TITLE
Sort HTML report by severity

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#2723]
**Is your feature request related to a problem? Please describe.**
After running the kics HTML report output, parsing the template to view the critical results was challenging. This was challenging because there was no way to sort from just critical results to informational. Going through hundreds of results can be painful if you have to look for the orange shield and can't sort.

**Describe the solution you'd like**
Press the critical shield or a sort toggle function to sort the results from most critical first to information results.

**Comment by felipe-avelar** [comment]
@jonny-wg2 thanks for your feedback.
Our next release, scheduled for tonight, will be sorting results from critical to information results and we want to work on filtering results on HTML soon.

**Comment by rogeriopeixotocx** [comment]
@jonny-wg2 check out the new filters in the HTML report on the next nightly build
