### ISSUE TITLE
Documentation - picture links are broken in architecture.md

### ISSUE THREAD

**Issue by yevgenykuz** [Checkmarx/kics#2730]
Hi, great project !

Going over the docs I found that some pictures are missing in the following page:
https://github.com/Checkmarx/kics/blob/master/docs/architecture.md

For example - https://github.com/Checkmarx/kics/blob/master/img/arch/high-level-arch.png is missing.

**Comment by rogeriopeixotocx** [comment]
@yevgenykuz thank you, we will take a look into it.
