### ISSUE TITLE
Dead link for the "Get started" button on kics.io

### ISSUE THREAD

**Issue by fniessink** [Checkmarx/kics#2937]
Clicking the "Get started" button (which links to https://docs.kics.io/getting-started/) gives me a 404.

**Comment by fredericmalo** [comment]
Hello Franck, 

Here is the correct link: https://docs.kics.io/1.2.3/#getting-started

Talk to you soon, Frédéric

**Comment by rogeriopeixotocx** [comment]
Thank you for the feedback, we will fix this ASAP.

**Comment by joaoReigota1** [comment]
Thank you for the feedback
This bug has been fixed https://kics.io/
