### ISSUE TITLE
Please use Docker instead of downloading manually the files

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#2962]
### Expected Behavior
Have CI examples using docker instead of using complicated downloads on this folder https://github.com/Checkmarx/kics/tree/master/examples

### Actual Behavior
Examples presented using wget, not docker

### Specifications
-   Version: latest
-   Platform: docker
-   Subsystem: Linux

**Comment by miguelfreitas93** [comment]
For example, for Gitlab:
``yml
image: docker:git

services:
- docker:dind

stages:
  - kics

before_script:
  - docker pull checkmarx/kics:$KICS_VERSION

kics:
  stage: kics
  script:
    - > 
        docker run
        -v $CI_PROJECT_DIR:/code
        checkmarx/kics:$KICS_VERSION
        scan 
        -p /code

``

**Comment by miguelfreitas93** [comment]
Also it is required to have a README.md explaining which variables you need to define and which are default variables already defined on the pipeline for example:

- Gitlab Default Variables:
-- CI_PROJECT_DIR -> Folder where Source code can be found

- CI/CD Pipeline variables required to be created:
-- KICS_VERSION -> Docker Tag of kics docker image to be used

**Comment by jbrotsos** [comment]
@miguelfreitas93 I was about to file the same FR but is it necessary to run docker pull & docker run?  I believe this would work instead:

  image:
    name: checkmarx/kics:${KICS_VERSION}

**Comment by miguelfreitas93** [comment]
Yeah, that might work @jbrotsos

**Comment by rogeriopeixotocx** [comment]
@miguelfreitas93 @jbrotsos your feedback is greatly appreciated. We'll take a look at those improvements. But then again, you're also welcome to contribute. 

We want to promote community engagement! ✌🏻

**Comment by rogeriopeixotocx** [comment]
It's good to provide the option for our users to use docker in their CI/CD pipelines.

We already have integration examples using docker for:
- Jenkins.
- CircleCI
- Github Actions

Currently, those are WIP:
- Gitlab
- Azure DevOps

TBD in the near future:
- Bitbucket

cc: @StanislavPolovnyi @elit-cx @nunoocx @markmishaevcx

**Comment by roock** [comment]
@rogeriopeixotocx  are you still accepting community contribution for an updated template for Gitlab CI using the docker images?

**Comment by rogeriopeixotocx** [comment]
Hi @roock, yes we are :)

**Comment by roock** [comment]
This has already been implemented and can be closed

**Comment by nunoocx** [comment]
Thank you @roock !
