### ISSUE TITLE
Add more examples to most used CI/CD Build Servers

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#2963]
**Is your feature request related to a problem? Please describe.**
As an user I want to see examples for most common CI/CD Build Servers, using their convention, so I can quickly & smoothly integrate KICS on any CI/CD Pipeline.

**Describe the solution you'd like**
Beside the already existent examples, I would like to see examples for the following too:

- Jenkins
- Jenkins Pipelines
- Bamboo
- Team City
- AWS CodeBuild
- Travis CI
- Circle CI

On this examples, I would like to see the use of their own YML structure, Default Environment Variables similar to issue #2962 
and README file with all the details about which steps are required to follow to successfully integrate, like "Where can we define the environment variables in AWS CodeBuild ?"

This should be also available on public documentation https://docs.kics.io/1.2.4/ in the Integration section.

Thanks !

**Comment by rogeriopeixotocx** [comment]
@miguelfreitas93 FYI, we're already working on the Jenkins pipeline and Circle CI Orb. You're welcome to contribute with examples from the other platforms. Thank you for your feedback.

**Comment by rogeriopeixotocx** [comment]
We have merged https://github.com/Checkmarx/kics/pull/3038 adding documentation and examples for Jenkins pipelines.

**Comment by rogeriopeixotocx** [comment]
We have merged https://github.com/Checkmarx/kics/pull/3086 adding documentation and examples for CircleCI

**Comment by rogeriopeixotocx** [comment]
Adding TeamCity example https://github.com/Checkmarx/kics/pull/4259

**Comment by rafaela-soares** [comment]
Hi, @miguelfreitas93 🙂 

Thank you so much for reaching us! KICS will document all of your integration suggestions very soon.

Jenkins, Team City, Travis CI, and Circle CI are already documented. Regarding Bamboo and AWS CodeBuild, the documentation was added in the respective PR's, #4791 and #4790.
