### ISSUE TITLE
Specify Name of Output Files written to output-path

### ISSUE THREAD

**Issue by milesflo** [Checkmarx/kics#2964]
It would be useful if you could specify the name of the output files written to `output-path`, set either with CLI args or as a config file entry. Right now they will always be called `results.*`.

### Hacky Fix in the Meantime

```bash
kics -p /path/to/dir -o ./scan_results
cd scan_results
for f in results.*; do mv "$f" "${f/results/my_infra_project}"; done
```

**Comment by rogeriopeixotocx** [comment]
Thank you for your suggestion but currently, this is not on our roadmap is enough to address your requirements

**Comment by milesflo** [comment]
@rogeriopeixotocx If I submitted a working PR would you accept it?

**Comment by rogeriopeixotocx** [comment]
@milesflo if you want to contribute we're happy to review this together
