### ISSUE TITLE
Stringified json in error message

### ISSUE THREAD

**Issue by cxlucas** [Checkmarx/kics#2967]
### Expected Behavior
Show an error message "unknown 

### Actual Behavior
Displays the error message "unknown flag" and a stringified json in the end of output.

![save](https://user-images.githubusercontent.com/82591370/115854410-1ef2bd00-a422-11eb-8525-6502faa26211.png)

### Steps to Reproduce the Problem

1.  Open terminal.  
2. Go to kics folder.
3. Run: 'kics --any'

### Specifications

-   Version: 1.2.4
-   Platform: any
-   Subsystem: n/a

**Comment by felipe-avelar** [comment]
@cxlucas also reproduced this problem when using unknown commands, as can be seen on following image:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/76731601/115889784-2929b100-a44c-11eb-8ac2-3735e5bac66a.png)

**Comment by felipe-avelar** [comment]
If a flag must have arguments, but not receives, it will reproduce the bug, e.g.: `go run ./cmd/console/main.go scan -p valid_path --fail-on`
