### ISSUE TITLE
Documentation versioning should only be major.minor + latest symlink

### ISSUE THREAD

**Issue by kaplanlior** [Checkmarx/kics#3036]
https://docs.kics.io has versioned documentation (1.2.3, 1.2.4...). 

1. It should be for major.minor (e.g. 1.1, 1.2) as the maintenance releases should be only bug fixes / small issues.

2. At the moment when someone goes into the website, the URL is reffered to the a fixed version (https://docs.kics.io/1.2.4/ at the moment). This makes people hardcode the version when the send this URL to friends, add it to websites and so on. We should have either no version by default (versioned url will be for history only uses) or latest (stable) as the default (e.g. https://docs.kics.io/latest/ ).

You can see this at https://www.checkmarx.com/opensource/kics/ where it refers https://docs.kics.io/1.2.3/

**Comment by gabriel-cx** [comment]
Closing this issue due to the fact that, by default, the url now is https://docs.kics.io/latest/ .
