### ISSUE TITLE
Report about telemetry enabled in used software

### ISSUE THREAD

**Issue by emanuelb** [Checkmarx/kics#3041]
telemetry is widespread in ecosystem and some of it is opt-out and may send data in containers/env, etc..
There is project https://toptout.me/ github: https://github.com/beatcracker/toptout that track data on how to disable telemetry for several projects which I currently in process of adding more data to it, this issue is about reporting when telemetry is enabled, and suggest to disable it (running the needed commands or set required environment variables)

**Comment by rogeriopeixotocx** [comment]
@emanuelb thank you for your feedback, I've placed a PR for this.
