### ISSUE TITLE
Add Support to Buildah

### ISSUE THREAD

**Issue by emanuelb** [Checkmarx/kics#3135]
https://buildah.io/
> A tool that facilitates building OCI container images.

can be used via script to build container by separate steps not through Containerfile/Dockerfile (when `buildah bud` not used), for example:
https://www.redhat.com/sysadmin/building-buildah#creating-and-running-the-bash-script

There lots of results on github for searching `buildah run`, the issue about adding support for such scripts (or invocation of `buildah` in other ways):
https://github.com/chapeaux/cncpx/blob/f7311f81eafedb5a5780518e667e7c566ce1021f/containers/images/godot_ubi8.sh

**Comment by rafaela-soares** [comment]
Hi, @emanuelb 🙂 I hope this message finds you well.

Thank you so much for your suggestion. We are happy to inform you that KICS will start to support Buildah (PR #4740)!
