### ISSUE TITLE
On invalid log path - log is created in cwd

### ISSUE THREAD

**Issue by leonidweinbergcx** [Checkmarx/kics#3155]
### Expected Behavior
Log file invalid filename exception thrown

### Actual Behavior
Log file created in cwd

### Steps to Reproduce the Problem

1.  run command: kics scan --output-path ./../output --path ./../project --log-path log./../wow.log
2.  log is created in cwd instead of CLI error

### Specifications

-   Version: 1.3.0
-   Platform: windows
-   Subsystem:

**Comment by rogeriopeixotocx** [comment]
@leonidweinbergcx this seems to be resolved in the HEAD of the master branch.

Can you confirm and close the issue? 
![image](https://user-images.githubusercontent.com/75368139/117977431-b6b04080-b328-11eb-8d9d-be68e515a6b2.png)

cc: @joaoReigota1 @felipe-avelar

**Comment by leonidweinbergcx** [comment]
It still reproduces for me
