### ISSUE TITLE
Add SSH Access (Port 3389) Is Not Restricted From The Internet query for Terraform

### ISSUE THREAD

**Issue by joaomartinscx** [Checkmarx/kics#328]
### Platform
Terraform

### Provider
GCP

### Description
Check if Google Firewall allows SSH access (port 3389) from the Internet (public CIDR block)

**Comment by PauloASilva** [comment]
Hi team,
`3389` is the default RDP port.

Based on [Google Cloud Platform Foundation  CIS Benchmark][1], a new rule should be add to "_Ensure that RDP access is restricted from the internet_" ([SSH counterpart is also part of CIS Benchmark][2]).

Cheers,
Paulo A. Silva

[1]: https://paper.bobylive.com/Security/CIS/CIS_Google_Cloud_Platform_Foundation_Benchmark_v1_0_0.pdf#page=108&zoom=auto,-267,752
[2]: https://paper.bobylive.com/Security/CIS/CIS_Google_Cloud_Platform_Foundation_Benchmark_v1_0_0.pdf#page=105&zoom=auto,-267,752

**Comment by joaomartinscx** [comment]
Hello Paulo,
This issue was closed without PR because it was repeating. And yes, that port does not belong to SSH, which was noted beforehand and this query was not added to the repo. 
If you have any other questions, please let me know.
Regards,
João Martins
