### ISSUE TITLE
Error with terraform rules (multiple)

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3388]
Error with some rules

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/39831372/118971641-f651da80-b96f-11eb-9609-c66178f01fa8.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/39831372/118971684-010c6f80-b970-11eb-9043-e96ad9da3830.png">

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/39831372/118971839-2bf6c380-b970-11eb-9d94-66ae880b2606.png">

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/39831372/118972611-061dee80-b971-11eb-88dd-d21929f067b8.png">

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/39831372/118974697-6877ee80-b973-11eb-9eba-b77446d3ce5d.png">

### Specifications

-   docker image `checkmarx/kics:latest` v1.3.0

**Comment by felipe-avelar** [comment]
@jonny-wg2 hello, I'm hope you're doing well. Could you elaborate what kind of problems are happening with those queries? Also, if it is possible, could you provide an example the scenario they happens?

**Comment by rogeriopeixotocx** [comment]
I'm closing this as stale, @jonny-wg2 can reopen providing additional info.
