### ISSUE TITLE
Update \[Passwords And Secrets In Infrastructure Code\] query for \[dockerfile\]

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3389]
### Platform
Dockerfile

### Description
False positives 

<img width="1307" alt="Screenshot 2021-05-20 at 14 06 13" src="https://user-images.githubusercontent.com/39831372/118975878-b3decc80-b974-11eb-99ec-84f5a78eef6f.png">

**Comment by felipe-avelar** [comment]
Hello, @jonny-wg2, thanks for your report, we will check this issue as soon as possible.
