### ISSUE TITLE
Update [WORKDIR Path Not Absolute] query for [dockerfile]

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3390]
### Platform
Dockerfile

### Description
Unsure why this is triggering and has a complete path?

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/39831372/118977139-213f2d00-b976-11eb-8c82-3aa01d1311cc.png">

**Comment by felipe-avelar** [comment]
Hello, @jonny-wg2, I hope you're doing well and thank you for your report. This is a complete path and shouldn't be triggering this query, we will correct this as soon as possible
