### ISSUE TITLE
Update [APT-GET Missing '-y' To Avoid Manual Inputquery] for Dockerfile

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3391]
### Platform
Dockerfile

### Description
Need to update regex to support `-qy` e.g.

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/39831372/118977303-49c72700-b976-11eb-89f3-be392bcbdccb.png">

**Comment by rafaela-soares** [comment]
Hello, Jonny 🙂 Thank you so much for the report. We will support that flag very soon!

**Comment by rafaela-soares** [comment]
https://github.com/Checkmarx/kics/blob/master/assets/queries/dockerfile/apt_get_missing_yes_flag_to_avoid_manual_input/metadata.json
