### ISSUE TITLE
Update [Secrets Stored In Dockerfile] query for Dockerfile

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3394]
### Platform
Dockerfile

### Description
False positives for environment variables

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/39831372/118981776-03c09200-b97b-11eb-9f30-2773c0e884f3.png">

**Comment by felipe-avelar** [comment]
@jonny-wg2 thank you for your report. I think this query is doubled, so we will check as soon as possible.
