### ISSUE TITLE
Update ServiceAccount Allows Access Secrets for Kubernetes

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3396]
### Platform
Kubernetes

### Description
ServiceAccount Allows Access Secrets doesn't make sense. A role should be used to gain access to secrets.

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/39831372/118990880-8e0cf400-b983-11eb-8795-a6015aa71475.png">

**Comment by rafaela-soares** [comment]
Hello, Jonny 🙂 Thank you for your report. Can you give us more information, please?

Just a little note: This query is based on this [recommendation](https://kubernetes.io/docs/concepts/configuration/secret/#clients-that-use-the-secret-api) of the official Kubernetes documentation.

**Comment by rogeriopeixotocx** [comment]
I'm closing this as stale, @jonny-wg2 can reopen with additional information required.
