### ISSUE TITLE
Add the option to select the queries to be run by KICS (include and not exclude)

### ISSUE THREAD

**Issue by oribendetcx** [Checkmarx/kics#3413]
**Description**
Add the possibility of providing `--queries-path` or `-p` multiple times, to be able to select queries by inclusion and not only exclusion.

**Comment by rogeriopeixotocx** [comment]
We'll add a `--include-queries` or `-i` shorthand for filtering queries for now which is easier to achieve, then we can think later about the query overriding system with multiple queries path, embedding libraries into the KICS binary all together into a same topic
