### ISSUE TITLE
MarshalJSON Error on YAML Extend

### ISSUE THREAD

**Issue by xqrt** [Checkmarx/kics#3414]
### Expected Behavior
yaml files can be converted to JSON, so they can be parsed via KICS.
### Actual Behavior
KICS fails with error on yaml files where "Extend <<" is used

 
### Steps to Reproduce the Problem

1.  step 1
use the attached file bug.yaml [bug.yaml.txt](https://github.com/Checkmarx/kics/files/6529028/bug.yaml.txt) 
(rename it back to .yaml)
2.  step 2
```
./bin/kics scan -p ~/Downloads/bug.yaml -d bug.json -vvv
```
3.  step 3
```
Executing queries: [=           6.5%           ]11:33PM ERR Failed to run application error="failed to read sources: failed to save file content: json: error calling MarshalJSON for type model.Document: json: unsupported type: map[interface {}]interface {}"
```
### Specifications

-   Version: 1.3.0; 1.3.1; snapshot-6ae329f3 (possibly all)
-   Platform: Linux
-   Subsystem:

**Comment by xqrt** [comment]
https://blog.daemonl.com/2016/02/yaml.html

**Comment by felipe-avelar** [comment]
This problem happens when trying marshal document at sink.go:33
