### ISSUE TITLE
AWS CDK - add a configuration guide on how to extract CF files from AWS cloud assembly

### ISSUE THREAD

**Issue by oribendetcx** [Checkmarx/kics#3427]
**Description**

AWS CDK outputs an AWS Cloudformation template, we should provide documentation on how to scan the CDK output with KICS.

https://docs.aws.amazon.com/cdk/latest/guide/home.html

**Comment by rogeriopeixotocx** [comment]
Related with https://github.com/Checkmarx/kics/issues/3103
