### ISSUE TITLE
Invalid JSON log format

### ISSUE THREAD

**Issue by leonidweinbergcx** [Checkmarx/kics#3475]
### Expected Behavior
Scan log is in valid JSON format

### Actual Behavior
Scan log is in invalid JSON format

### Steps to Reproduce the Problem

1.  scan any project with --log-format json
2.  log structure is as following:
{object}
{object}
etc..

Multiple objects on root level are not allowed according to JSON spec. JSON parsers will fail.
It should be:
[
{object},
{object}
]

https://jsonlint.com/

### Specifications

-   Version: 1.3.1
-   Platform: windows x64
-   Subsystem:

**Comment by rogeriopeixotocx** [comment]
This is the default behavior of zerolog https://github.com/rs/zerolog#setting-global-log-level

Usually, when you're streaming logs in JSON format you send one object per line. 

Because otherwise, you would need to know the entire output before sending any events to format the array.

**Comment by rogeriopeixotocx** [comment]
If you want to wait for KICS to finish and combine the entries using pipes in CLI:
You could use: `jq -cs`
![image](https://user-images.githubusercontent.com/75368139/120212950-92aa9580-c22a-11eb-8e71-052da0cc2a86.png)
