### ISSUE TITLE
scan duration in log should be displayed in milis

### ISSUE THREAD

**Issue by leonidweinbergcx** [Checkmarx/kics#3477]
### Expected Behavior
scan duration displayed in milis

### Actual Behavior
scan duration displayed in seconds with fractions

### Steps to Reproduce the Problem
1.  scan any project

It is up to user application to parse the time and display in any format he wants.

### Specifications

-   Version: 1.3.1
-   Platform: windows
-   Subsystem:

**Comment by joaoReigota1** [comment]
Hi @leonidweinbergcx is it ok if this change is only set for the flag `--ci`? It is easier for a user to read the scan duration in a format other than milliseconds
