### ISSUE TITLE
Invalid exit code on successful kics execution

### ISSUE THREAD

**Issue by leonidweinbergcx** [Checkmarx/kics#3501]
### Expected Behavior
Exit code is 0

### Actual Behavior
Exit code is 50

### Steps to Reproduce the Problem

1. run kics scan without cli errors.
2.  inspect the exit code

According to the standards, a program should return exit code 0 on successful execution and 1-255 for other general errors.
Optional: General errors could be documented along with the code numbers.

### Specifications

-   Version: 1.3.1
-   Platform: windows
-   Subsystem:

**Comment by rogeriopeixotocx** [comment]
@leonidweinbergcx this is by design.

https://docs.kics.io/1.3.1/changes/

https://docs.kics.io/1.3.1/results/#exit_status_code
