### ISSUE TITLE
v1.3.2 kics scan command always export to result.json regardless of -o parameter

### ISSUE THREAD

**Issue by ILiuACR** [Checkmarx/kics#3528]
${TARGET_DIR}/kics scan --no-progress -q ${TARGET_DIR}/assets/queries -p ${PWD} --output-path ${PWD}/kics-results.json
### Expected Behavior
output file should be kics-results.json
### Actual Behavior
output file always be results.json
### Steps to Reproduce the Problem

1.  step 1
2.  step 2
3.  step 3

### Specifications

-   Version: 1.3.2
-   Platform:linux
-   Subsystem:

**Comment by felipe-avelar** [comment]
Hello, @ILiuACR, I hope you're doing well. There was an update for `ouput-path` flag and, now, it refers to specific path where the report will be saved. To choose a custom name, like kics-result, you can use `output-name` name flag, as you can see in [docs' results section](https://docs.kics.io/1.3.2/results/#results).

If you have any questions about this, feel free to ask. :)
