### ISSUE TITLE
Duplicate ID's for two different findings

### ISSUE THREAD

**Issue by rotem-cider** [Checkmarx/kics#3557]
### Expected Behavior
Each finding has to have 1 issue id

you should add also tests to check for duplicate ids

### Steps to Reproduce the Problem

2 different findings have the same ID here: 

https://github.com/Checkmarx/kics/blob/3d8a6cc4268827ed837e0f84fb8b84aa3f1e7a01/assets/queries/terraform/aws/s3_bucket_acl_allows_read_to_any_authenticated_user/metadata.json#L2

https://github.com/Checkmarx/kics/blob/3d8a6cc4268827ed837e0f84fb8b84aa3f1e7a01/test/fixtures/all_auth_users_get_read_access/metadata.json#L2

**Comment by rogeriopeixotocx** [comment]
@rotem-cider thank you for your contribution, this is not really a bug since the second query ID in question is just a test fixture. But just in case we decided to change it to something else :)
