### ISSUE TITLE
HCL files can be transformed into JSON

### ISSUE THREAD

**Issue by xqrt** [Checkmarx/kics#3585]
### Expected Behavior
HCL files can be transformed into JSON using the `kics scan -p ..` method
### Actual Behavior
The sample Vault HCL config returns an empty document, instead of the JSON format.
### Steps to Reproduce the Problem

1.  step 1
```
./bin/kics scan -p test.hcl -d test.hcl.json
```
2.  step 2
```
➜  kics git:(master) ✗ cat test.hcl.json 
{
        "document": []
}

```

[test.hcl.sample.txt](https://github.com/Checkmarx/kics/files/6615025/test.hcl.sample.txt)

### Specifications

-   Version: snapshot-7f6f1ea7; 1.3.1; 1.3.2 (and probably all below)
-   Platform: Linux x64 (tested)
-   Subsystem:

**Comment by rogeriopeixotocx** [comment]
Hi @xqrt, at this moment we only support Terraform HCL files.
We do not have queries to scan Vault configurations.
You're more than welcome to contribute to our project.
