### ISSUE TITLE
FN - S3 bucket allows put action from all principals query doesn't detect vulnerable configuration

### ISSUE THREAD

**Issue by securylight** [Checkmarx/kics#3748]
### Expected Behavior
S3 Buckets must not allow Put Action From All Principals
### Actual Behavior
Put Action From All Principals with is allowed. 
### Steps to Reproduce the Problem

Scan a folder that contains the attached file
[s3bucket.tf.txt](https://github.com/Checkmarx/kics/files/6702058/s3bucket.tf.txt)
Results are attached as well. 
[result2.html.txt](https://github.com/Checkmarx/kics/files/6702117/result2.html.txt)
Also a put request to the bucket.
![secrettoaws](https://user-images.githubusercontent.com/37718207/123103451-aff40d80-d43e-11eb-9fbc-7aab979a8334.PNG)

### Specifications

-   Version: v1.3.2
-   Platform: Terraform
-   Subsystem:

**Comment by felipe-avelar** [comment]
As observed #3789 , KICS does not supports `jsonencode` yet...
