### ISSUE TITLE
FN - S3 Buckets must not allow Get Action From All Principals

### ISSUE THREAD

**Issue by securylight** [Checkmarx/kics#3751]
### Expected Behavior
S3 Buckets must not allow Get Action From All Principals
### Actual Behavior
Get Action From All Principals with is allowed. 
### Steps to Reproduce the Problem

Scan a folder that contains the attached file
[s3bucketGet_.tf.txt](https://github.com/Checkmarx/kics/files/6770585/s3bucketGet_.tf.txt)

Results are attached as well. 
[resultbucketget.html.txt](https://github.com/Checkmarx/kics/files/6703258/resultbucketget.html.txt)

Also a Get request to the bucket.
![s3bucketget](https://user-images.githubusercontent.com/37718207/123128920-349d5680-d454-11eb-8d2c-042c75b8b1e8.PNG)

### Specifications

-   Version: v1.3.2
-   Platform: Terraform
-   Subsystem:

**Comment by felipe-avelar** [comment]
As observed [here](https://github.com/Checkmarx/kics/issues/3789#issuecomment-875767418), KICS does not supports `jsonencode` yet
