### ISSUE TITLE
FP - 'RUN npm install --production --no-cache' 

### ISSUE THREAD

**Issue by fredericmalo** [Checkmarx/kics#3767]
### Expected Behavior

Kics should not report that "npm install" needs a "pin version", as pin versions are defined in package.json. 
Kics should report a vulnerability with "npm install mongodb" (as an example) if mongodb has no pinned version 

### Actual Behavior

Kics reports: 'RUN npm install --production --no-cache' does not uses npm install with a pinned version

### Steps to Reproduce the Problem

Please scan https://github.com/OWASP/NodeGoat with kics

Thanks !

**Comment by felipe-avelar** [comment]
@fredericmalo First of all, I hope you are doing well. Thanks for your report, there was a problem with our query, I think it will be solved in our next release. 🙂

**Comment by fredericmalo** [comment]
Thanks !
