### ISSUE TITLE
FP - 'Dockerfile' contains the 'chown' flag'

### ISSUE THREAD

**Issue by fredericmalo** [Checkmarx/kics#3768]
### Expected Behavior

Kics should not report a "The 'Dockerfile' contains the 'chown' flag'" vulnerability if the chown flag is used in the regular 
"COPY --chown=node . $WORKDIR" that is a standard command: https://docs.docker.com/engine/reference/builder/#copy

### Steps to Reproduce the Problem

Please scan https://github.com/OWASP/NodeGoat with kics

Thanks !

**Comment by joaoReigota1** [comment]
Hi @fredericmalo, I will update the query description so it is more clear, Thank you!
