### ISSUE TITLE
FN - Terraform with S3 Bucket policy that Allows Delete to all principals  should be detected

### ISSUE THREAD

**Issue by securylight** [Checkmarx/kics#3789]
### Expected Behavior
Terraform with S3 Bucket policy that Allows Delete to all principals should be detected.

### Actual Behavior
Terraform with S3 Bucket policy that Allows Delete to all principals  are not detected
### Steps to Reproduce the Problem

Scan a folder that contains the attached file 
[s3Deletebucket.tf .txt](https://github.com/Checkmarx/kics/files/6741391/s3Deletebucket.tf.txt)

Results are attached as well. 
[result.html.txt](https://github.com/Checkmarx/kics/files/6741375/result.html.txt)

### Specifications

-   Version: v1.3.2
-   Platform: Terraform
-   Subsystem:

**Comment by felipe-avelar** [comment]
@securylight This bucket file uses `jsonencode` which is a terraform function and is not supported by KICS yet. We will put this on our roadmap, but, if you want, feel free to contribute.
I think this will use [HCL library to define functions](https://hcl.readthedocs.io/en/latest/go_expression_eval.html#defining-functions) and update terraform parser.
