### ISSUE TITLE
Kics doesn't scan zip files if the user doesn't provide the complete path of zip file

### ISSUE THREAD

**Issue by cxlucas** [Checkmarx/kics#3806]
### Expected Behavior

When running a kics scan with "-p folder-name", kics should perform a scan in all files within this folder, including ".zip" files.

### Actual Behavior

When running a kics scan with "-p folder-name", kics scan all files (.tf, .yaml ...) but ignores ".zip" files inside the folder. By this way, kics cannot found these files and doesn't perform a scan for them.

### Steps to Reproduce the Problem

1.  You should have a valid ZIP file (contaning a valid sample inside) to perform a successful scan.
2.  Open terminal.
3. Go to kics folder.
4. Create a folder (example: `samples-folder`)
5. Put the zip file inside this folder (example: `files.zip`)
6. Run: "`kics scan -p samples-folder`"
7. **Kics will perform a scan, but no files will be scanned.**
8. Run: "`kics scan -p samples-folder/files.zip`"
9. **Kics will perform a successful scan (scanning the files.zip content)**

### Specifications

-   Version: n/a
-   Platform: n/a
-   Subsystem: n/a

**Comment by rogeriopeixotocx** [comment]
This is expected behavior.
