### ISSUE TITLE
Inject custom data in queries

### ISSUE THREAD

**Issue by felipe-avelar** [Checkmarx/kics#3807]
[Following @mukeshpilaniya suggestion](https://gitter.im/kics-io/community?at=6099011d20d4f02631b25f60), since Rego has the ability to user injects custom data through the store, KICS should allows the user to give a custom JSON to overwrite default data in a simple way.

**Comment by rogeriopeixotocx** [comment]
cc: @mukeshpilaniya  @kaplanlior

**Comment by jonny-wg2** [comment]
One interesting usecase I have is the ability to not just whitelist a rule but also whitelist a `rule + label`. So if it is `02323c00-cdc3-4fdc-a310-4f2b3e7a1660` + `deployment: something-public`

**Comment by felipe-avelar** [comment]
@jonny-wg2 I think this can be solved by the path you pass when executing kics command, something like:
```sh
kics scan (...) --input-data dev/
kics scan (...) --input-data prod/
```

I think this way is better, since you will have a better folder structure. 🙂

**Comment by jonny-wg2** [comment]
We do do this currently for Mass scans. However the issue I have is an ability to keep the rule and whitelist the finding vs excluding the entire rule when performing the scan.

**Comment by felipe-avelar** [comment]
> We do do this currently for Mass scans. However the issue I have is an ability to keep the rule and whitelist the finding vs excluding the entire rule when performing the scan.

@jonny-wg2 are you refering to `exclude-queries` flag? I'm a little confused about your message. You want to execute the rule but ignore the result?

**Comment by jonny-wg2** [comment]
Sorry for the lack of clarity. I am seeking a way to exclude the results but keep the rule via a kics config of some sort.

**Comment by felipe-avelar** [comment]
Oh, I see. I will bring this up to the team and we will discuss in our future meetings.
However, I think this is not related with this feature, so, if you want, you can open a feature request describing what you want with more details, so we could take an action. 🙂
