### ISSUE TITLE
Update "Resources not using tags" query for Terraform AWS

### ISSUE THREAD

**Issue by jonny-wg2** [Checkmarx/kics#3824]
### Platform
Terraform

### Provider
AWS 

### Description
The current issue is that it triggers an alert for all AWS resources. However, not all AWS Resources have the ability for tags.

In the case we just saw, it triggered an error for the `resource "aws_iam_policy"`
```
Resource Not Using Tags, Severity: INFO, Results: 1

Description: AWS services resource tags are an essential part of managing components

Platform: Terraform


[1]: /tmp/build/1e3febcf/pull-request/infra/terraform/environments/infra/account/s3/env/s3.tf:60

	059: 
	060: resource "aws_iam_policy" "a_super_awesome_policy" {
	061:   name_prefix = "some-policy-name-"
```

**Comment by felipe-avelar** [comment]
@jonny-wg2 Hi, I hope you are doing well. Checking ['aws_iam_policy' terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy#tags), there is a `tags` field available. If you still think it is wrong, could you provide us more information about this issue, please?

**Comment by jonny-wg2** [comment]
@felipe-avelar Ah yes you are correct about `aws_iam_policy`, however, we did receive another error about `aws_iam_policy_document` which looking at the docs, does not support tags? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document

```
------------------------------------
Resource Not Using Tags, Severity: INFO, Results: 1

Description: AWS services resource tags are an essential part of managing components

Platform: Terraform


[1]: /tmp/build/1e3febcf/pull-request/infra/terraform/environments/dev/env/kubernetes-system/infra/registry.tf:1

	001: data "aws_iam_policy_document" "registry" {
	002:   statement {
	003:     actions = [

Results Summary:

HIGH: 0

MEDIUM: 0

LOW: 0

INFO: 1

TOTAL: 1


Results saved to file results.json

Results saved to file results.html

Scan duration: 8.500321294s
```

**Comment by felipe-avelar** [comment]
@jonny-wg2 you are right about this, I think there is an issue with the `searchKey` of this query. Is it possible for you to show your resource blocks definitions?

**Comment by jonny-wg2** [comment]
Sure, here is the file
```
data "aws_iam_policy_document" "registry_r_li" {
  statement {
    actions = [
      "s3:GetBucketLocation",
      "s3:ListBucket",
      "s3:ListBucketMultipartUploads",
    ]

    resources = [
      "arn:aws:s3:::bucketname"
    ]
  }

  statement {
    actions = [
      "s3:GetObject",
      "s3:ListMultipartUploadParts",
    ]

    resources = [
      "arn:aws:s3:::bucketname/*"
    ]
  }
}

resource "aws_iam_role" "registry-read-li" {
  name               = "k8s-infra-registry-read-li-${module.locals.cluster_name}"
  description        = "Role to allow r rights to registry li S3 bucket"
  assume_role_policy = data.terraform_remote_state.base.outputs.kiam_server_policy_document
  tags = {
    team           = "infra"
  }
}

resource "aws_iam_policy" "registry_r_li" {
  name_prefix = "wg2-registry-li-r-"
  description = "Read access to the registry li S3 buckets."
  policy      = data.aws_iam_policy_document.registry_r_li.json
}

resource "aws_iam_role_policy_attachment" "registry-read-li" {
  role       = aws_iam_role.registry-read-li.name
  policy_arn = aws_iam_policy.registry_r_li.arn
}
```

**Comment by felipe-avelar** [comment]
@jonny-wg2 there was an issue detecting the correct line and this will probably be solved in the next release.

But, checking your file, there is a problem with the resource in the **line 35**, `resource "aws_iam_policy" "registry_r_li"`, that does not have a `tags` field, which KICS is reporting. 🙂
