### ISSUE TITLE
Ansible query docs have incorrect documentation links

### ISSUE THREAD

**Issue by JonZeolla** [Checkmarx/kics#3830]
### Expected Behavior
Documentation links are version pinned

### Actual Behavior
Documentation links go to the latest release

### Steps to Reproduce the Problem

1. Browse to https://github.com/Checkmarx/kics/blob/master/docs/queries/ansible-queries.md
2. Click a documentation link
3. See that the `rego` for that finding does not match the naming in the linked Ansible documentation

**Comment by felipe-avelar** [comment]
@JonZeolla Hi, first of all I hope you're doing.
About the issue you described, I could not reproduce this bug... Could you provide more details, please?

**Comment by felipe-avelar** [comment]
Due lack of information and the fact we couldn't reproduce, this issue will be closed. If any new information is added, this can be reopened.
