### ISSUE TITLE
Add HCL Code Style queries for Terraform

### ISSUE THREAD

**Issue by rogeriopeixotocx** [Checkmarx/kics#3845]
### Platform
Terraform

### Provider
any

### Description
We should have queries to flag bad HCL code style.

* non-snake case
* variables without type
* variables/output without description
* names should not contain part of the resource type
* modules must have a ref

**Comment by felipe-avelar** [comment]
This issue is already done and can be closed. The following PRs resolve this issue: #3847 #3848 #3849 #3853 #3854
