### ISSUE TITLE
KICS_COLLECT_TELEMETRY environment variable not explained

### ISSUE THREAD

**Issue by dohnalv** [Checkmarx/kics#3876]
I think that this part of the documentation could use some explanation:
![image](https://user-images.githubusercontent.com/87282270/125741853-05bdc802-954f-4a82-aaf3-f0617b9bf20a.png)

Especially in open-source projects, you will rarely see mentions of telemetry without at least simple description of what data is being sent out and for what purpose. Some members of the community could also view telemetry as potentially malicious, even when there's absolutely no reason to (as @kaplanlior had already explained to me on Gitter). 

Suggestion: 
**Explain what kind of data is being sent out and what part of them (if any) is being shared with the community.**

**Comment by oribendetcx** [comment]
How about Disable_Crash_Report?

**Comment by dohnalv** [comment]
Sure, that might also work

**Comment by rogeriopeixotocx** [comment]
Hello @emanuelb

I want to give you a heads up related with the project https://github.com/beatcracker/toptout

I'll change the flag name `KICS_COLLECT_TELEMETRY` this to `DISABLE_CRASH_REPORT` per request

https://github.com/Checkmarx/kics/issues/3041
https://github.com/Checkmarx/kics/pull/3056
