### ISSUE TITLE
Support JUnit report format

### ISSUE THREAD

**Issue by bivas** [Checkmarx/kics#3902]
**Is your feature request related to a problem? Please describe.**
Most CI systems support JUnit format

**Describe the solution you'd like**
We would like to have the report format as JUnit (XML) format

**Describe alternatives you've considered**
Another common report format (glsast isn't common as JUnit)

**Comment by rogeriopeixotocx** [comment]
@bivas given the information we currently have in our formats (JSON, SARIF, etc...), do you have a suggested structure to accommodate that in the JUnit XML?

My first thought was to have a single `<testsuite>` inside `<testsuites>`. `<testcase>` would represent a query and `<failure>` would represent a result. All the result properties would be fit in `<failure>` as properties of the tag. Scan related information could be fit in the testsuite [properties](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L50-L70). I'm just not sure how the tools out there would parse our results in this format. 

Do you have a specific tool you're looking to parse this new report format? We could use it to test during development.

**Comment by rogeriopeixotocx** [comment]
@bivas Nevermind it seems that `<failure>` can only happen once per `<testcase>` when `maxOccurs` is not defined the default is 1. We need to find another way to map queries and results to the JUnit structure.

**Comment by AErmie** [comment]
Is there any progress on this? Having the output in a format that CI/CD tools can read and show results easily would be appreciated. If there isn't an easy option to include JUnit as an output type, is there any recommended alternative approach to convert the JSON output into JUnit?

**Comment by Praveena-PM** [comment]
any update on this? Even I want to generate a junit report after the Checkmarx scan. I have generated an xml file, but not in Junit Format and hence not able to parse them in bamboo VI plan using a Junit parser plugin. Any thoughts?

**Comment by nunoocx** [comment]
@bivas @Praveena-PM @AErmie 
Thanks for your comments. We are planning to support JUnit format by December 2021!
