### ISSUE TITLE
FP - Passwords and Secrets

### ISSUE THREAD

**Issue by rogeriopeixotocx** [Checkmarx/kics#3905]
### Expected Behavior
KICS should not flag a false positive secret

### Actual Behavior
KICS is flagging a false positive secret

![Passwords_Secrets_IaC](https://user-images.githubusercontent.com/75368139/127011784-0e736c49-0787-4591-bcc0-ff1e1a0572e4.jpg)

**Comment by kaplanlior** [comment]
Opened based on https://gitter.im/kics-io/community?at=60f9222223956a5aa44ce1b7 and https://gitter.im/kics-io/community?at=60fa9946b8422d6f4f000f19 by @adeshmukh123 (thanks for reporting).
