### ISSUE TITLE
Memcached disabled query is flagging CF IaC code with elasti cache engine running Redis

### ISSUE THREAD

**Issue by adeshmukh123** [Checkmarx/kics#3909]
### Expected Behavior
   - The query in question should not flag the IaC code as the choice of engine is subjective & depending upon the 
      project use case

### Actual Behavior
    It's flagging the IaC code

### Steps to Reproduce the Problem
1.  Run KiCS on a CF IaC code containing elastic cache configuration

### Specifications

-   Version :
-   Platform : CF , AWS
-   Subsystem:
![Memcached-Disabled](https://user-images.githubusercontent.com/20418199/127035023-a723b305-01a6-4527-a5be-1af01fe891dd.jpg)

**Comment by rogeriopeixotocx** [comment]
@adeshmukh123 please provide a full sample

**Comment by rogeriopeixotocx** [comment]
Sorry without a sample we cannot provide with a solution to your issue
