### ISSUE TITLE
kics constantly spams "Preparing Scan Assets:" message

### ISSUE THREAD

**Issue by Dentrax** [Checkmarx/kics#4112]
### Expected Behavior

It should not spam?

### Actual Behavior

https://user-images.githubusercontent.com/16493751/130800663-21a7a48f-cfc3-4bad-8698-e95ecc13d13d.mov

### Steps to Reproduce the Problem

1.  Prepare an empty Go project
2.  ` $ docker run -v $(pwd):/path checkmarx/kics:latest scan -p "/path" -o "/path/" --output-name kics-result --fail-on high`
3.  See the "Preparing Scan Assets:" messages

### Specifications

-   Version: `v1.4.1`
-   Platform: `macOS`
-   Subsystem: `-`

**Comment by rogeriopeixotocx** [comment]
This happened because you did not provide the `-tty` or `-t` flag to the [docker run](https://docs.docker.com/engine/reference/run/) command and docker didn't issue a pseudo-tty to the process causing this carriage return based progress spinner not to work as expected.

**Comment by Dentrax** [comment]
Oh, I didn't know that. Thanks for explaining!
