### ISSUE TITLE
Basic execution fails: invalid memory address

### ISSUE THREAD

**Issue by mosheavni** [Checkmarx/kics#4194]
### Expected Behavior
to work

### Actual Behavior
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1dd438f]
```
### Steps to Reproduce the Problem

1. Download mac executable
2. enter terraform directory
3. run `kics scan -p .`

### Specifications

-   Version: `Keeping Infrastructure as Code Secure 1.4.2`
-   Platform: macosx (Darwin)
-   Subsystem:

![image](https://user-images.githubusercontent.com/17252601/133274944-01423c17-5c32-40ee-9cd8-2088f6faafb5.png)

**Comment by felipe-avelar** [comment]
Hello @mosheavni, thanks for reaching us.
First of all, I hope you're doing well and thanks for your report.
I think this issue was solved by #4172 and does not happens anymore in KICS v1.4.3 which was released yesterday.
If it still happens, feel free to reopen this issue.
