### ISSUE TITLE
kics scan within a docker can not use proxy 

### ISSUE THREAD

**Issue by ticteam** [Checkmarx/kics#4257]
### Expected Behavior
kics scan within a docker can use proxy 

### Steps to Reproduce the Problem

I try to scan the folder /home/ubuntu/workspace/PROJECT/kics-scan within a docker
I also set the proxy as env but it's not working ..... 

docker run --env https_proxy=http://security-proxy.****.net:3128 -v /home/ubuntu/workspace/PROJECT/kics-scan:/home/ubuntu/workspace/PROJECT/kics-scan --network=host checkmarx/kics:latest scan -p /home/ubuntu/workspace/PROJECT/kics-scan -q /app/bin/assets/queries --ci --report-formats html -o /home/ubuntu/workspace/PROJECT/kics-scan --ignore-on-exit results

07:27:28  5:27AM INF Scanning with Keeping Infrastructure as Code Secure v1.4.3
07:27:28  5:27AM INF Loading queries of type: 

07:27:55  5:27AM INF Inspector initialized, number of queries=1998
07:27:55  5:27AM INF Query execution timeout=1m0s
07:27:55  5:27AM ERR Unable to GET descriptions API error="Get \"https://kics.io/api/\": dial tcp: lookup kics.io on 10.*.*.*:53: no such host"
07:27:55  5:27AM WRN Unable to get descriptions: Get "https://kics.io/api/": dial tcp: lookup kics.io on 10.*.*.*:53: no such host

### Specifications

connection from docker host ubuntu works well:
* Establish HTTP proxy tunnel to kics.io:443                                                                                                                                                
> CONNECT kics.io:443 HTTP/1.1                                                                                                                                                              
> Host: kics.io:443                                                                                                                                                                         
> User-Agent: curl/7.68.0                                                                                                                                                                   
> Proxy-Connection: Keep-Alive                                                                                                                                                              
>                                                                                                                                                                                           
< HTTP/1.1 200 Connection established                                                                                                                                                       

-   Version:
docker version                                                                                                                                                           
Client:                                                                                                                                                                                     
 Version:           20.10.2                                                                                                                                                                 
 API version:       1.41                                                                                                                                                                    
 Go version:        go1.13.8                                                                                                                                                                
 Git commit:        20.10.2-0ubuntu1~20.04.2                                                                                                                                                
 Built:             Tue Mar 30 21:24:57 2021                                                                                                                                                
 OS/Arch:           linux/amd64          
                                                                                                                                                   
-   Platform:
uname -a                                                                                                                                                                 
Linux runner-0 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux                                                                                  

-   Subsystem:
behind a coorperate proxy

**Comment by ticteam** [comment]
the isses above is with version 1.2.4 ! 
so I updated to version 1.4.3 AND tried it on the bash console of the host and getting the message:
1:06PM ERR Unable to GET descriptions API error="Get \"https://kics.io/api/\": dial tcp: lookup kics.io: no such host" 

when I downgrade to version 1.2.4 , I do not get the error and the scan ran through successfull

**Comment by rogeriopeixotocx** [comment]
Hi @ticteam, thank you for reporting this issue, we will investigate the issue for the moment as a workaround I recommend using `--disable-full-descriptions` flag to continue scanning with the latest version of KICS.
