### ISSUE TITLE
Failed to detect line, query response .securityContext.runAsUser=xxxx

### ISSUE THREAD

**Issue by ticteam** [Checkmarx/kics#4285]
### Expected Behavior
the kics scan runs without warnings, this warning let the jenkins job failing

### Steps to Reproduce the Problem

1.  checkout repo from github, ... fine
2.  scan the code with:
/usr/bin/kics scan --ci --no-color -p /home/ubuntu/workspace/BTF-Ops/kics-scan --disable-full-descriptions --output-path results --report-formats html results
3.  step 3
WRN Failed to detect line, query response .securityContext.runAsUser=1000 fileName=/home/ubuntu/workspace/BTF-Ops/kics-scan/deployment/-backend/values.yaml queryName=containers_run_with_low_uid scanID=console
4. tried with higher UID 9999
WRN Failed to detect line, query response .securityContext.runAsUser=9999 fileName=/home/ubuntu/workspace/BTF-Ops/kics-scan/deployment/-backend/value
s.yaml queryName=containers_run_with_low_uid scanID=console                                                                                                            

the results.html is created and also reports "Container Running With Low UID"

### Specifications

-   Version: Infrastructure as Code Secure 1.4.3
-   Platform: Linux runner-0 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-   Subsystem: 
Jenkins version 2.303.1
java.version | 1.8.0_201

**Comment by rogeriopeixotocx** [comment]
@ticteam we'll investigate this issue, thank you for reporting. Are you able to provide any samples with anonymized data?

Additionally, there might be an issue in the following command line input, the last `results` keyword seems to be unassociated with any parameters:

```/usr/bin/kics scan --ci --no-color -p /home/ubuntu/workspace/BTF-Ops/kics-scan --disable-full-descriptions --output-path results --report-formats html results```

I believe the correct form would be:

```/usr/bin/kics scan --ci --no-color -p /home/ubuntu/workspace/BTF-Ops/kics-scan --disable-full-descriptions --output-path results --report-formats html```

**Comment by ticteam** [comment]
question: the scan is always failing if there is any issue ?

**Comment by ticteam** [comment]
the additional result at the end of the command is removed. it's not related to that but: 
values.yaml 
securityContext:
  fsGroup: 9999
  runAsUser: 1000

>> 12:17PM WRN Failed to detect line, query response .securityContext.runAsUser=1000 fileName=/home/ubuntu/workspace/BTF-Ops/kics-scan/deployment/slp-config-backend/values.yaml queryName=containers_run_with_low_uid scanID=console


values.yaml:
securityContext:
  fsGroup: 19999
  runAsUser: 10001
  runAsGroup: 10001
>> no WRN Failed to detect line, ........

**Comment by joaoReigota1** [comment]
Hi @ticteam, we took a look into your issue and it seems it was a line detection problem, we added `searchLine` to the query `Container Running With Low UID` which should fix the warning you were getting and point to the correct line on this PR
https://github.com/Checkmarx/kics/pull/4286 . 
Regarding the vulnerability, `runAsUser` should be higher than 10 000 to prevent conflicts with the host's user table.


> question: the scan is always failing if there is any issue ?

The scan doesn't fail if an issue is found, unless it is an engine issue, otherwise, the issue is reported in the log and scan continues.

**Comment by ticteam** [comment]
ERROR: script returned exit code 50 
 
 + /usr/bin/kics scan -v --no-color -p /home/ubuntu/workspace/BTF-Ops/kics-scan -e oneapi.yaml --disable-full-descriptions --output-path results --report-formats html
 
                    .0MO.                                    
                    OMMMx                                    
                    ;NMX;                                    
                     ...           ...              ....     
 WMMMd     cWMMM0.  KMMMO      ;xKWMMMMNOc.     ,xXMMMMMWXkc.
 WMMMd   .0MMMN:    KMMMO    :XMMMMMMMMMMMWl   xMMMMMWMMMMMMl
 WMMMd  lWMMMO.     KMMMO   xMMMMKc...'lXMk   ,MMMMx   .;dXx 
 WMMMd.0MMMX;       KMMMO  cMMMMd        '    'MMMMNl'       
 WMMMNWMMMMl        KMMMO  0MMMN               oMMMMMMMXkl.  
 WMMMMMMMMMMo       KMMMO  0MMMX                .ckKWMMMMMM0.
 WMMMMWokMMMMk      KMMMO  oMMMMc              .     .:OMMMM0
 WMMMK.  dMMMM0.    KMMMO   KMMMMx'    ,kNc   :WOc.    .NMMMX
 WMMMd    cWMMMX.   KMMMO    kMMMMMWXNMMMMMd .WMMMMWKO0NMMMMl
 WMMMd     ,NMMMN,  KMMMO     'xNMMMMMMMNx,   .l0WMMMMMMMWk, 
 xkkk:      ,kkkkx  okkkl        ;xKXKx;          ;dOKKkc    
 
 
 Scanning with Keeping Infrastructure as Code Secure 1.4.3
 
 
 11:59AM INF Scanning with Keeping Infrastructure as Code Secure 1.4.3
 11:59AM INF Loading queries of type: dockerfile, ansible, kubernetes, openapi
 11:59AM INF Inspector initialized, number of queries=683
 11:59AM INF Query execution timeout=1m0s
 
 11:59AM WRN Skipping CIS descriptions because provided disable flag is set
 Files scanned: 14
 Parsed files: 14
 Queries loaded: 683
 Queries failed to execute: 0
 
 ------------------------------------
 
 Apk Add Using Local Cache Path, Severity: INFO, Results: 1
 Description: When installing packages, use the '--no-cache' switch to avoid the need to use '--update' and remove '/var/cache/apk/*'
 Platform: Dockerfile
 
 	[1]: Dockerfile:8
 
 		007: 
 		008: RUN apk upgrade --no-cache --available && \
 		009:     apk add openssl && \
 
 
 Service Does Not Target Pod, Severity: LOW, Results: 1
 Description: Service should Target a Pod
 Platform: Kubernetes
 
 	[1]: deployment/x-backend/templates/service.yaml:3
 
 		002: kind: Service
 		003: metadata:
 		004:   labels:
 
 
 Healthcheck Instruction Missing, Severity: LOW, Results: 1
 Description: Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
 Platform: Dockerfile
 
 	[1]: Dockerfile:1
 
 		001: FROM ******/openjdk:17-alpine
 		002: 
 		003: # set maintainer
 
 
 Unpinned Package Version in Apk Add, Severity: MEDIUM, Results: 1
 Description: Package version pinning reduces the range of versions that can be installed, reducing the chances of failure due to unanticipated changes
 Platform: Dockerfile
 
 	[1]: Dockerfile:8
 
 		007: 
 		008: RUN apk upgrade --no-cache --available && \
 		009:     apk add openssl && \
 
 
 Use of Apk Upgrade, Severity: HIGH, Results: 1
 Description: Avoid usage of apk upgrade because some packages from the parent image cannot be upgraded inside an unprivileged container
 Platform: Dockerfile
 
 	[1]: Dockerfile:8
 
 		007: 
 		008: RUN apk upgrade --no-cache --available && \
 		009:     apk add openssl && \
 
 
 
 Results Summary:
 HIGH: 1
 MEDIUM: 1
 LOW: 2
 INFO: 1
 TOTAL: 5
 
 11:59AM INF Files scanned: 14
 11:59AM INF Parsed files: 14
 11:59AM INF Queries loaded: 683
 11:59AM INF Queries failed to execute: 0
 11:59AM INF Inspector stopped
 11:59AM INF Results saved to file results/results.html fileName=results.html
 Results saved to file results/results.html
 Scan duration: 11.561367804s
 11:59AM INF Scan duration: 11.561367804s
 
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] emailext
11:59:52  Sending email to: 
[Pipeline] cleanWs
11:59:52  [WS-CLEANUP] Deleting project workspace...
11:59:52  [WS-CLEANUP] Deferred wipeout is used...
11:59:52  [WS-CLEANUP] done
[Pipeline] deleteDir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 50
Finished: FAILURE

**Comment by rogeriopeixotocx** [comment]
Hi @ticteam, exit status 50 means you have a HIGH severity issue in your scan results https://docs.kics.io/latest/results/#results_status_code

if you want to return exit status 0 unless there's an engine failure use `--ignore-on-exit results` flag.
