### ISSUE TITLE
kics is reporting "Service should Target a Pod" 

### ISSUE THREAD

**Issue by ticteam** [Checkmarx/kics#4302]
### Expected Behavior
a little description how to solve the finding

### Actual Behavior
kics is reporting "Service should Target a Pod" but even on https://kubernetes.io/docs/concepts/services-networking/service/ , there is only the app mentioned as selector and it is not described what else is needed.

### Steps to Reproduce the Problem
1.  step 1
scan the following service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: application
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}

2. step 2
after adding line 3 & 4
  selector:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}                                                # <<-- added to fix the finding
    app.kubernetes.io/instance: {{ .Chart.Name }}-{{ .Values.namespace }}      # <<-- added to fix the finding

and add the 2 lines to the deplyoment.yaml 
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}-{{ .Values.namespace }}
    app.kubernetes.io/name: {{ .Chart.Name }}                                                # <<-- added to fix the finding
    app.kubernetes.io/instance: {{ .Chart.Name }}-{{ .Values.namespace }}      # <<-- added to fix the finding

 and scanning again the issue is gone :) 

### Specifications

-   Version: Scanning with Keeping Infrastructure as Code Secure 1.4.3
-   Platform: ubuntu 20
-   Subsystem: Jenkins 2.303.1

**Comment by ticteam** [comment]
WTF ..... 
yesterday it was gone, today it is back, without any changes ............. on the service.yaml 

:(

**Comment by joaoReigota1** [comment]
Hi @ticteam, there was indeed an issue with our query  "Service should Target a Pod", which should be solved with PR #4323.
Thank you for your help!
