### ISSUE TITLE
Notify users when custom libraries do not load properly

### ISSUE THREAD

**Issue by cxlucas** [Checkmarx/kics#4357]
**Is your feature request related to a problem? Please describe.**

Maybe it can be a problem (do not warn the user). When using "`--libraries-path`" or "`-b`", we can define a path to load custom libraries configuration. It's a great feature that allows everyone to make their own changes and run kics using a custom configuration.
But, if I change, for example, the **terraform.rego** and by accident, I save the file with missing a comma or without closing parentheses properly, it will produce an invalid file, and kics won't be able to run this file.

**Describe the solution you'd like**

Kics will load the custom libraries and the default libraries (as the current behavior) and must finish the scan (because if just some libraries were broken, the remained libraries can be performed normally).
However, if kics throws an error while reading/interpreting any custom library, **the user must know that during the scan, a specific library/platform was not scanned because kics couldn't read the library**.

**Describe alternatives you've considered**

Kics can also stop the scan and display an error message if any custom library cannot be read correctly.

**Additional context**

**Current Behavior**: Kics performs the scan and doesn't send any alert about the error when trying to read the custom library.

The only way that allows us to identify the issue is using logs, like "--log-level DEBUG".

![image](https://user-images.githubusercontent.com/82591370/136599491-77c91e39-e26e-4581-8449-798a70e1d2b9.png)

**Comment by rafaela-soares** [comment]
Hi, @cxlucas! Thank you so much for the suggestion! It was added in PR #4405 🙂 


![kics](https://user-images.githubusercontent.com/74001161/147132105-4985c8a3-96e9-4375-bd9d-59fa0e1ca9d5.PNG)
