### ISSUE TITLE
I'd like to see a BoM (Bill-of-Material) for all of my cloud resources

### ISSUE THREAD

**Issue by oribendetcx** [Checkmarx/kics#4367]
### Description
*Give short description about the feature being implemented*
I'd like to see a BoM (Bill-of-Material) for all of my cloud resources
I'd like KICS to generate a full list of my cloud resources in a combined way for me to consume.

**Comment by rafaela-soares** [comment]
Hello, @oribendetcx 🙂 I hope you are doing well!

We will close this issue. For now, KICS supports BoM for the following Terraform resources: 
  - aws_ebs_volume
  - aws_efs_file_system
  - aws_elasticache_cluster
  - aws_mq_broker
  - aws_msk_cluster
  - aws_s3_bucket
  - aws_sns_topic
  - aws_sqs_queue
  - aws_sqs_queue_policy

**Comment by Jeeppler** [comment]
What is or should be the output using `--bom`? SPDX, CycloneDX? Does it only work with `aws_*` resources?
