### ISSUE TITLE
feature request: Exclude resources based on kind:

### ISSUE THREAD

**Issue by Carus11** [Checkmarx/kics#4378]
In my cluster I use the bitnami sealed-secrets utility to store encrypted secrets in my repository. I would like a method to exclude fails based on secrets existing in the manifests of kind: SealedSecret

**Is your feature request related to a problem? Please describe.**
When my repository includes bitnami sealed-secrets the scan fails, even though the secrets are not base64 encoded but are encrypted.

**Describe the solution you'd like**
I would like the ability to configure a way to exclude certain resources.

**Describe alternatives you've considered**
Havent considered much else.....

**Additional context**
Perhaps I am naive in using the bitnami-sealed-secrets project. Let me know if this is just ridiculous.

**Comment by felipe-avelar** [comment]
Hello @Carus, thanks for your message. I think `--exclude-categories` might solve your problem, could you check it, please?

**Comment by Carus11** [comment]
Hi Felipe,
I dont think that would solve my problem, as I would still like the tool to search for and identify issues with things in that category (secrets). I would just like it to not think that storing encrypted secrets was worth raising a flag about.

**Comment by joaoReigota1** [comment]
Hi, @Carus11 with v1.4.7 the ability to ignore blocks and lines by comment commands was added to KICS, can you try to add

 `# kics-scans ignore-block` on the top of the resource you want to ignore.
example:
```
---
#  kics-scans ignore-block
kind: SealedSecret
metadata:
...
```
For more information please check: https://docs.kics.io/latest/running-kics/#using_commands_on_scanned_files_as_comments
