### ISSUE TITLE
Decrypt ansible vault files on the fly

### ISSUE THREAD

**Issue by LvffY** [Checkmarx/kics#4417]
**Describe the solution you'd like**

When running Ansible anlaysis, it could be very practical to analyse encrypted files by decrypt these files on the fly and analyse their values. For now, if we want to use a password **admin** we just have to encrypt our password. May be a new configuration like `KICS_ANSIBLE_VAULT_PASSWORD` or just use the `ANSIBLE_VAULT_PASSWORD_FILE` could do the job.

Kics would then decrypt vault files on the fly, analyse their values and add the potentiel security analysis in the report

**Comment by rafaela-soares** [comment]
Hi, @LvffY 🙂 Thank you so much for contacting us!

Can you detail the use case a little more, please? When you mention "decrypt vault files", do you mean an entire encrypted vault file or a vault file with encrypted parts?

**Comment by LvffY** [comment]
Hi @rafaela-soares sorry for the time of response.

In my use case this is only entire encrypted vault file (and I **hope** this is the most common case in the community) but I think that we can't ignore people that would just encrypt variables in non encrypted files.

But i think that this second use case could be leave for a later issue.

**Comment by rafaela-soares** [comment]
Hi, @LvffY!

We will take a look as soon as possible at your suggestion! Thank you so much for your collaboration 😊

**Comment by rafaela-soares** [comment]
Hi, @LvffY!

We are happy to inform you that we are working on this in PR #4976 😊
