### ISSUE TITLE
Document the state of Terraform module support

### ISSUE THREAD

**Issue by JonZeolla** [Checkmarx/kics#4493]
**Is your feature request related to a problem? Please describe.**
When I'm reviewing the documentation of KICS I want to identify if it supports my use case, which makes copious use of Terraform modules.

**Describe the solution you'd like**
Document the state of Terraform module support, including any prereqs or limitations (i.e. if you run `terraform init` the `.terraform` folder will be scanned, but variables will not be interpolated)

**Comment by felipe-avelar** [comment]
Hi, @JonZeolla, first of all I hope you're doing well and thanks for reaching us. Right now we do not support custom modules on terraform, just some official repository modules, as you can see [here](https://github.com/Checkmarx/kics/blob/master/assets/libraries/common.json).
I agree with you that this feature must be well documented and we will add this section as soon as possible.

If you have any other question, feel free to reach us. 🙂

**Comment by JonZeolla** [comment]
Thank you for the clarification @felipe-avelar!  This does resolve my initial question.

Is there a roadmap item for supporting custom modules?
