### ISSUE TITLE
Update \[sqs_policy_with_public_access\] query for \[AWS\] (Terraform)

### ISSUE THREAD

**Issue by kenwynejohnes** [Checkmarx/kics#4498]
### Platform
Terraform

### Provider
AWS

### Description

- The query is checking for `statement.Action ` instead of `statement.Principal`
- Definition of `queue_name` and `queue_resource` is not needed

Possible fix:

1)  `commonLib.containsOrInArrayContains(statement.Action, "*")`  -> 

`commonLib.containsOrInArrayContains(statement.Principal, "*")`

2) Remove this code snippet
```
	queue_name := trim_prefix(trim_suffix(resource.queue_url, ".id}"), "${aws_sqs_queue.")
	queue_resource := input.document[j].resource.aws_sqs_queue[queue_name]
```

Terraform config:
```
resource "aws_sqs_queue_policy" "test" {
  queue_url = aws_sqs_queue.q.id
 
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:*",
      "Resource": "arn:aws:sqs:us-east-1:<account_id>:<sqs_queue>"
    }
  ]
}
POLICY
}
```

**Comment by kaplanlior** [comment]
Hi @kenwynejohnes , thanks for this suggestion. 

Would you be interested in also sending a pull request to fix this ?
We'll be happy to help you do that.
