### ISSUE TITLE
Wrong detection of unused security group

### ISSUE THREAD

**Issue by jynicolas** [Checkmarx/kics#4501]
### Description

- Platform: Terraform
- Provider: AWS

The query "Security Group Not Used" (id `4849211b-ac39-479e-ae78-5694d506cb24`) detects unused security group when this sg is attached to an `aws_instance` resource.

### Expected Behavior

No vulnerability of type _Security Group Not Used_ found

### Actual Behavior

```
Security Group Not Used, Severity: INFO, Results: 1
Description: Security group must be used or not declared
Platform: Terraform

        [4]: negative3.tf:9

                008: 
                009: resource "aws_security_group" "used_sg" {
                010:   name        = "used-sg"
```

### Steps to Reproduce the Problem

Create an security group and attach it to an aws_instance using the argument [vpc_security_group_ids](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#vpc_security_group_ids)

Example tf file failing this query:

```
# given:
#  - used security group
#  - aws_instance
# when:
#  - used security group attached to aws_instance
# then:
#  - do not detect any unused security group

resource "aws_security_group" "used_sg" {
  name        = "used-sg"
  description = "Used security group"
  vpc_id      = aws_vpc.main.id

  ingress {
    description      = "Some port"
    from_port        = 43
    to_port          = 43
    protocol         = "tcp"
    cidr_blocks      = [aws_vpc.main.cidr_block]
    ipv6_cidr_blocks = [aws_vpc.main.ipv6_cidr_block]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

}

resource "aws_instance" "negative3" {
  ami = "ami-003634241a8fcdec0"

  instance_type = "t2.micro"

  vpc_security_group_ids = [ "${aws_security_group.used_sg.id}" ]
  
}

```

### Specifications

-   Version: 1.4.7
-   Platform: Linux
-   Subsystem:  N/A

**Comment by kaplanlior** [comment]
Thanks @jynicolas for reporting this issue.
