### ISSUE TITLE
A new version is available message although running with latest KICS

### ISSUE THREAD

**Issue by oribendetcx** [Checkmarx/kics#4525]
Found a bug? You're welcome to [![Gitter](https://badges.gitter.im/kics-io/community.svg)](https://gitter.im/kics-io/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

- **Please make sure to:**
  - Describe in details what the problem is
  - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG`)
  - Attach the scanned sample files, anonymize the data if the original file cannot be provided
  - When attaching files to the issue make sure they are properly formatted

### Expected Behavior
The version check of KICS should only show if not running on latest
(Which results are expected from KICS?)

### Actual Behavior
Pulling the latest KICS (docker hub pull) - KICS 1.4.7 and still getting the notification about the new verrsion
(Formatted logs and samples helps us to better understand the issue)

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  docker pull checkmarx/kics:latest
2.  run KICS scan
3.  check the outout

### Specifications
(N/A if not applicable)

-   Version:
-   Platform:
-   Subsystem:

**Comment by joaoReigota1** [comment]
I believe this issue is already fixed!
