### ISSUE TITLE
team_name hardcoded in team_name.webhook.office.com

### ISSUE THREAD

**Issue by skorpy2009** [Checkmarx/kics#4528]
Hi,

In the following line, do I misinterpret the line or is `team_name` wrong there and should be a regex?

https://github.com/Checkmarx/kics/blob/a546d9adfaa808ea05192988c075e105155a3f0a/assets/queries/common/passwords_and_secrets/regex_rules.json#L103

**Comment by joaoReigota1** [comment]
Hello, @skorpy2009 I believe this is indeed a bug and team_name should be a Regex and not hardcoded, I will make the change to regex.
Thank you
