### ISSUE TITLE
Update S3 Bucket Without Enabled MFA Delete query for Terraform

### ISSUE THREAD

**Issue by zbmowrey** [Checkmarx/kics#4576]
### Platform
*Terraform*

### Provider
*AWS*

### Description
This query suggests enabling MFA delete on buckets where lifecycle policies are in place. The result should be suppressed if the bucket contains any lifecycle policy. 

Per [AWS Documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiFactorAuthenticationDelete.html):

> You cannot use MFA delete with lifecycle configurations. For more information about lifecycle configurations and how they interact with other configurations, see Lifecycle and other bucket configurations.

**Comment by rafaela-soares** [comment]
Hello, @zbmowrey 🙂 Such a great suggestion! Thank you so much! 

We are happy to inform you that #4635 implements your suggestion!
