### ISSUE TITLE
Use .gitignore to automatically exclude paths

### ISSUE THREAD

**Issue by jgrumboe** [Checkmarx/kics#4584]
**Is your feature request related to a problem? Please describe.**
I tested kics for Terraform code and it will also report problems it finds in the external modules I use in my code.
To be more precise it scans also `.terraform` folders and files found there.

**Describe the solution you'd like**
I already ignore `.terraform` folders in my `.gitignore` and would like kics to understand/respect the definitions there - automatically or via cmdline argument.

**Describe alternatives you've considered**
I can define the folders in this case also directly using `kics scan -e '.terraform,*/.terraform' -p .`
But for future improvements, I think it would be good to support .gitignore.

**Comment by anterosilva1985** [comment]
Hi @jgrumboe,

First of all i'm sorry for the delay on the feedback. Also i would like to thanks you on this input. 
Regarding this feature request, i've decided to include it on Kics 1.6 version. 

Regards,
Antero Silva
Product Manager - Kics

**Comment by rafaela-soares** [comment]
Hi, @jgrumboe!

Thank you so much for the suggestion. KICS 1.6 version implements it 😊
