### ISSUE TITLE
kics-extract folder created during the kics scan is not removed and cause disk quota exceeded issue in Docker container

### ISSUE THREAD

**Issue by ppanchal10** [Checkmarx/kics#4585]
kics-extract folder created during the kics scan is not removed. I am running the kics (Command line) against our gitlab source repository in docker a container where multiple scans are executed simultaneously and each scan is creating a kics-extract folder to store downloaded gitlab source code in /tmp (by default linux temporary directory) but those folders and source code is not removed after the scan is completed. 

./kics_1.4.5/kics -s scan --no-progress --minimal-ui -q <query path> -p <git URL> -o --output-name
### Expected Behavior

kics should remove the extract folder once the scan is completed.

### Actual Behavior

I am seeing a lot of kics-extract folders under /tmp folder which cause disk quota exceeded problem and impacts subsequent scans  

### Steps to Reproduce the Problem

1.  step  - Run KICS as command line in a Docker container to scan multiple gitlab source code repository simultaneously
2.  step 2 - 
3.  step 3

### Specifications
(N/A if not applicable)

-   Version: 1.4.7
-   Platform: Linux RHEL 7.6
-   Subsystem:

**Comment by rafaela-soares** [comment]
Hello, @ppanchal10 🙂 Thank you so much for reaching us and reporting the bug!

We are happy to inform you that we are fixing it (#4638)!

**Comment by rafaela-soares** [comment]
Hello, @ppanchal10 🙂I hope you are doing well!

The fix will be included in the next release (around the end of this month).
