### ISSUE TITLE
Wrong detections in multi-arch Dockerfiles

### ISSUE THREAD

**Issue by Amaelh** [Checkmarx/kics#4591]
### Expected Behavior

KICS should properly recognize multi-arch Dockerfiles and only report vulnerabilities in actual stages of multi-stage Dockerfiles. 

### Actual Behavior

KICS seems to wrongly detect a multi-stage Dockerfile when there is a variable used to produce a multi-architecture Dockerfile.

It's probably easier with an example ! My Dockerfile starts like this :

```
ARG ARCH=
FROM ${ARCH}alpine:3.15

RUN apk add --no-cache unbound==1.13.2-r2 ca-certificates==20191127-r7

```

And KICS detects vulnerabilities on line -1. I guess it's because of the first `ARG ARCH=`.
Note that KICS succcesfully detects all vulnerabilities on the part after the FROM....

### Steps to Reproduce the Problem

I used the latest kics docker image with following flags :

```
docker run --pull always --rm \
                --workdir="/project" \
                --entrypoint "" \
                -v /home/amael/Tresors/workspace/rpi-unbound:/project/:rw \
                checkmarx/kics:latest \
                kics scan -q /app/bin/assets/queries \
                -p /project/ \
                --ignore-on-exit all \
                --log-level=DEBUG \
                --log-path /dev/stdout \
                --report-formats glsast \
                -o /project/output/ \
                --output-name kics-results
```

My Dockerfile : 

```
ARG ARCH=
FROM ${ARCH}alpine:3.15

RUN apk add --no-cache unbound==1.13.2-r2 ca-certificates==20191127-r7

# Copy main configuration file
COPY unbound.conf root.hints /etc/unbound/

# Copy contents of conf to image
COPY conf /etc/unbound/unbound.conf.d/

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod a+x /usr/local/bin/docker-entrypoint.sh ; unbound-anchor -v ; chown -R unbound:unbound /usr/share/dnssec-root/

# Create a low-privileged user for runnning
RUN addgroup -S container && adduser -S container -G container
# Set SUID to unbound binaries
RUN chmod 4755 /usr/sbin/unbound-checkconf /usr/sbin/unbound
# Switch to the new user
USER container

EXPOSE 53/udp

CMD ["/usr/local/bin/docker-entrypoint.sh"]

HEALTHCHECK --interval=1m --retries=1 --start-period=5s CMD nslookup www.google.fr
```

The result : 

```
Files scanned: 2
Parsed files: 2
Queries loaded: 327
Queries failed to execute: 2

------------------------------------

Healthcheck Instruction Missing, Severity: LOW, Results: 1
Description: Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
Platform: Dockerfile

        [1]: Dockerfile:-1



Missing User Instruction, Severity: HIGH, Results: 1
Description: A user should be specified in the dockerfile, otherwise the image will run as root
Platform: Dockerfile

        [1]: Dockerfile:-1




Results Summary:
HIGH: 1
MEDIUM: 0
LOW: 1
INFO: 0
TOTAL: 2
[kics-debug.log](https://github.com/Checkmarx/kics/files/7710134/kics-debug.log)

```

Note that I had the same findings in the actual stage of my Dockerfile and corrected them by adding a user and a healthcheck instruction. These findings disappeared after correction, but the ones on line -1 are staying.

Please find attached full log file in debug mode.

### Specifications

-   Version: Keeping Infrastructure as Code Secure v1.4.8
-   Platform: Linux-amd64
-   Subsystem: ?

**Comment by joaoReigota1** [comment]
Hi @Amaelh, Thank you for reporting this issue,
It seems this is a bug with our Dockerfile parser as it creates a structure just for the args returning the vulnerabilities on that structure, I will create a PR fixing this issue and it should be available on the next release.
