### ISSUE TITLE
Kics Panic when trying to scan protected zip file

### ISSUE THREAD

**Issue by cxlucas** [Checkmarx/kics#4604]
### Expected Behavior

Kics should display an error message, such as "Failed to open/read file protected.zip"

### Actual Behavior

Kics displays a panic message when trying to open a **protected zip file** compressed with AES-256 using 7zip/WinRAR.
The error doesn't reproduce for the same file if it's protected with a ZipCrypto encryption method (legacy).

- Protected zip with **AES-256**
![image](https://user-images.githubusercontent.com/82591370/146526827-69e4f05a-d18f-44aa-b5af-d7981910e403.png)

- Protected zip with **legacy encryption**
![image](https://user-images.githubusercontent.com/82591370/146526865-ec5f4a48-075a-4548-b29c-90395383d6c9.png)

### Steps to Reproduce the Problem

1.  Create a compressed ZIP file within a password, using encryption method AES-256 (or use the protected-AES-256.zip attached file).
2.  Perform a scan in the file, such as "kics scan -p protected.zip".
3.  Kics must display an error message.

### Specifications
-   Version: 1.4.8
-   Platform: N/A
-   Subsystem: N/A

### Attachments

ZIP Password: 123
[protected-zipcrypto.zip](https://github.com/Checkmarx/kics/files/7734214/protected-zipcrypto.zip)
[protected-AES-256.zip](https://github.com/Checkmarx/kics/files/7734213/protected-AES-256.zip)

**Comment by joaoReigota1** [comment]
Hi @cxlucas, unfortunately, this seems to be a [go-getter](https://github.com/hashicorp/go-getter) issue that we can't prevent from the KICS side, I will open an issue on their repo in order to fix it.
Thank you!
