### ISSUE TITLE
KICS is panicking when running against its project

### ISSUE THREAD

**Issue by lipeavelar** [Checkmarx/kics#4655]
### Expected Behavior
KICS should run without any errors

### Actual Behavior
KICS is panicking and showing the following stack:
> panic: runtime error: index out of range [-1]
> 
> goroutine 16582 [running]:
github.com/Checkmarx/kics/pkg/parser/grpc/converter.getLastElementLine({0x32768a0, 0xc000161ce0}, 0x0)
        /home/lipeavelar/projects/kics/pkg/parser/grpc/converter/converter.go:621 +0x2ef
github.com/Checkmarx/kics/pkg/parser/grpc/converter.(*JSONProto).processCommentProto(0xc004a17680, 0xc00f47d220, 0x63, {0x32768a0, 0xc000161ce0})
        /home/lipeavelar/projects/kics/pkg/parser/grpc/converter/converter.go:581 +0x258
github.com/Checkmarx/kics/pkg/parser/grpc/converter.Convert(0xc00534c420)
        /home/lipeavelar/projects/kics/pkg/parser/grpc/converter/converter.go:156 +0x525
github.com/Checkmarx/kics/pkg/parser/grpc.(*Parser).Parse(0xc000092100, {0xc005e01300, 0x1079}, {0xc005e01300, 0x1079, 0x1300})
        /home/lipeavelar/projects/kics/pkg/parser/grpc/parser.go:27 +0xbe
github.com/Checkmarx/kics/pkg/parser.(*Parser).Parse(0xc004f5d2c0, {0xc000b217a0, 0x5b}, {0xc005e01300, 0x1079, 0x1300})
        /home/lipeavelar/projects/kics/pkg/parser/parser.go:119 +0x108
github.com/Checkmarx/kics/pkg/kics.(*Service).sink(0xc00327dea0, {0x38ed598, 0xc000050068}, {0xc000b217a0, 0x0}, {0x3432618, 0x7}, {0x38a47a0, 0xc006215018})
        /home/lipeavelar/projects/kics/pkg/kics/sink.go:34 +0x105
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources.func1({0x38ed598, 0xc000050068}, {0xc000b217a0, 0x5b}, {0x38cbac8, 0xc006215018})
        /home/lipeavelar/projects/kics/pkg/kics/service.go:64 +0xa5
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir.func1({0xc000b217a0, 0x5b}, {0x3915290, 0xc002284680}, {0x0, 0x0})
        /home/lipeavelar/projects/kics/pkg/engine/provider/filesystem.go:155 +0x4b5
path/filepath.walk({0xc000b217a0, 0x5b}, {0x3915290, 0xc002284680}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:418 +0x125
path/filepath.walk({0xc0115ec460, 0x4b}, {0x3915290, 0xc002284270}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc0115ec2d0, 0x42}, {0x3915290, 0xc0022840d0}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc003a4d410, 0x30}, {0x3915290, 0xc00259a000}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc003a4d350, 0x2c}, {0x3915290, 0xc002237e10}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc004261dd0, 0x25}, {0x3915290, 0xc000bf9ee0}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc0007fc520, 0x1e}, {0x3915290, 0xc006dae0d0}, 0xc00642be20)
        /usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.Walk({0xc0007fc520, 0x1e}, 0xc00008ce20)
        /usr/local/go/src/path/filepath/path.go:505 +0x6c
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir(0xc0007fc520, {0x38ed598, 0xc000050068}, {0xc0007fc520, 0x7f637677b360}, 0x1, 0x20, 0x7f63bf0e5f18, 0x20)
        /home/lipeavelar/projects/kics/pkg/engine/provider/filesystem.go:120 +0x9b
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).GetSources(0xc002d75780, {0x38ed598, 0xc000050068}, 0xc001187798, 0xc002e927c0, 0xc000982cb0)
        /home/lipeavelar/projects/kics/pkg/engine/provider/filesystem.go:109 +0x1b0
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources(0xc00327dea0, {0x38ed598, 0xc000050068}, {0x3432618, 0x7}, 0x0, 0x0)
        /home/lipeavelar/projects/kics/pkg/kics/service.go:60 +0x1a7
created by github.com/Checkmarx/kics/pkg/scanner.PrepareAndScan
        /home/lipeavelar/projects/kics/pkg/scanner/scanner.go:24 +0xe5
exit status 2

### Steps to Reproduce the Problem

1.  Run KICS from its folder using the following command: `go run cmd/console/main.go scan -p . -q ./assets/queries/k8s/`

### Specifications

-   Version: 1.4.9
-   Platform: Linux
-   Subsystem: Linux

**Comment by nunoocx** [comment]
Thank you @lipeavelar! :) 
We will take a look at this soon.

**Comment by rafaela-soares** [comment]
Hi, @lipeavelar 🙂
I hope this message finds you well. Wishing you a year filled with health, love, happiness, peace, and success!

Thank you so much for continuing to reach us 🚀 

I was not able to reproduce the error through `go run cmd/console/main.go scan -p . -q ./assets/queries/k8s/`. However, the same kind of error was found in the previous week. I think this PR(#4651) should fix it.
