### ISSUE TITLE
Missing newline after `Generating Reports: Done`

### ISSUE THREAD

**Issue by Dentrax** [Checkmarx/kics#4663]
Found a bug? You're welcome to [![Gitter](https://badges.gitter.im/kics-io/community.svg)](https://gitter.im/kics-io/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

- **Please make sure to:**
  - Describe in details what the problem is
  - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG`)
  - Attach the scanned sample files, anonymize the data if the original file cannot be provided
  - When attaching files to the issue make sure they are properly formatted

### Expected Behavior

(Which results are expected from KICS?)

```
Generating Reports: DoneScan duration: 13.914609004s
```

### Actual Behavior

(Formatted logs and samples helps us to better understand the issue)

```
Generating Reports: Done
Scan duration: 13.914609004s
```

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  `docker run -v $(pwd):/path checkmarx/kics:latest scan -p "/path" -o "/path/" --output-name kics-result --fail-on high --version`
2.  See the line: `Generating Reports: DoneScan duration: 13.914609004s`

### Specifications
(N/A if not applicable)

-   Version: `v1.4.9`
-   Platform: `Linux`
-   Subsystem:

**Comment by rafaela-soares** [comment]
Hello, @Dentrax! Thank you for reaching out 🙂 

Unfortunately, the Docker image does not interpret correctly the progress bar. 

For now, you can use the flag `--no-progress` to avoid this behaviour.
