### ISSUE TITLE
Remove "Use of Apk Upgrade"

### ISSUE THREAD

**Issue by GoneUp** [Checkmarx/kics#4672]
Hi,

We started to use this scanner in our company. While it found many valid points, I think one "Issue" is unjustified. I talk about "Use of Apk Upgrade" / 989ab888-7d1e-410f-9dde-c64a1d367bf2.

The linked documentation provided by docker does not contain any warning of using a upgrade mechanism. I also saw this [blogpost](https://pythonspeed.com/articles/security-updates-in-docker/) talking about this behavior and how it is still beneficial to security. 

There was also a deeper [discussion](https://github.com/hadolint/hadolint/issues/562) in hadolint, they removed a simialr rule. 

### Platform
Docker

### Provider
Docker

### Description
"Use of Apk Upgrade" / 989ab888-7d1e-410f-9dde-c64a1d367bf2.

Thanks for looking into this!

**Comment by rafaela-soares** [comment]
Hello, @GoneUp 🙂 

We contacted our security team and we took into account your documentation references. After reading them and analysing them, we decided to proceed with the query removal (PR #4832). 

Thank you so much for addressing this matter with us! 🚀
