### ISSUE TITLE
Support for the AWS Security Finding Format (ASFF) for output results

### ISSUE THREAD

**Issue by barnesrobert** [Checkmarx/kics#4676]
The support for [ASFF](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-syntax.html) for output results will allow the findings to be consumed by AWS Security Hub.

**Comment by rafaela-soares** [comment]
Hello, @barnesrobert ! Thank you so much for your suggestion 🙂 

Can you please describe it a little more? Thank you.
