### ISSUE TITLE
 SAST Integration with GitLab will stop working in GitLab 15.0 (2022-05-22)

### ISSUE THREAD

**Issue by theoretick** [Checkmarx/kics#4700]
Hey folks! Just wanted to give you a heads-up on an upcoming deprecation from GitLab.

[GitLab SAST schemas below 14.0.0](https://docs.gitlab.com/ee/update/deprecations#sast-schemas-below-1400) have been deprecated.

### Expected Behavior

[`pkg/report/model/gitlab_sast.go#L88`](https://github.com/Checkmarx/kics/blob/591b849573fb10a07878123a807d0f74223766cf/pkg/report/model/gitlab_sast.go#L88) is using a deprecated version:

>    SchemaVersion:   "13.1.0",

[The latest version of the schema is 14.1.0](https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee/lib/ee/gitlab/ci/parsers/security/validators/schemas/14.1.0). There are [other schemas available](https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee/lib/ee/gitlab/ci/parsers/security/validators/schemas); any version from 14.0.0 is supported.

From GitLab 15.0 (2022-05-22), any reports submitted using an unsupported version will be rejected.

**Comment by theoretick** [comment]
It might be worth noting that [GitLab's kics analyzer](https://gitlab.com/gitlab-org/security-products/analyzers/kics) does not use the `glsast` report format directly but [uses our shared report library](https://gitlab.com/gitlab-org/security-products/analyzers/report/-/blob/b63268ccd18d199b47cda862b7532f4f86585aa6/sarif.go#L99) for handling [conversion](https://gitlab.com/gitlab-org/security-products/analyzers/kics/-/blob/038c9830a08d59bb656d5b62c763d569d76748a7/convert.go#L23) from [the raw SARIF output](https://gitlab.com/gitlab-org/security-products/analyzers/kics/-/blob/038c9830a08d59bb656d5b62c763d569d76748a7/analyze.go#L61).

So this deprecation will not affect our existing integration, only those using the `--report-formats glsast` directly

**Comment by nunoocx** [comment]
Thanks a lot for the heads up @theoretick!
We will upgrade our GitLab SAST output to be compliant with v14 ASAP.
