### ISSUE TITLE
Support Terraform CDK (CDKTF)

### ISSUE THREAD

**Issue by schematis** [Checkmarx/kics#4764]
**Is your feature request related to a problem? Please describe.**
I am unable to scan Terraform CDK output json because it is different than what is output by terraform plan

**Describe the solution you'd like**
I would like to be able to pass in cdk.tf.json and have it scanned

**Describe alternatives you've considered**
I have tried to convert cdk.tf.json to something compatible with terraform plan.

**Comment by rafaela-soares** [comment]
Hi, @schematis! 🙂 I hope this message finds you well.

Thank you so much for reaching us and suggesting a new feature.

We are happy to inform you that KICS will support it (#4770).

**Comment by schematis** [comment]
Ok great! Will it find the output file automatically in the cdktf.out folder or will we have to move the output to the root directory for it to process it?

**Comment by rafaela-soares** [comment]
It will find it no matter where the file is located in the path.
