### ISSUE TITLE
SimilarityID ("id") is also set as "cve" value in JSON report

### ISSUE THREAD

**Issue by CxKMc** [Checkmarx/kics#4781]
Example:
			"id": "3d4f14f3ac2ebc0d2cb1710eec4f61fae359fe78ab244cb716485cb6c90846f6",
			"category": "sast",
			"severity": "High",
			"cve": "3d4f14f3ac2ebc0d2cb1710eec4f61fae359fe78ab244cb716485cb6c90846f6",

Code snippet:
https://github.com/Checkmarx/kics/blob/fcc173581f6fa7c42c3885cdd3e84e9d327c62ef/pkg/report/model/gitlab_sast.go#L119

**Comment by rafaela-soares** [comment]
Hello, @CxKMc 🙂 

For now, the similarity ID is a workaround to fill the CVE field. We will contact our security team (AppSec) to investigate the possibility to map the KICS queries in CVE's. We will let you know the verdict as soon as possible. Thank you so much for reaching us.

**Comment by rafaela-soares** [comment]
Hello again, @CxKMc 🙂 

We will maintain the similarity ID as the CVE field. As documented [here](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/sast-report-format.json#L584), the CVE is deprecated, and it is not related to the CVE described in MITRE.
