### ISSUE TITLE
Can't scan current working directory

### ISSUE THREAD

**Issue by corydorning** [Checkmarx/kics#4783]
Found a bug? You're welcome to [![Gitter](https://badges.gitter.im/kics-io/community.svg)](https://gitter.im/kics-io/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

### Expected Behavior
when running `kics scan -p ./` it should scan files in the current directory

### Actual Behavior
i get the error:
```
Error: initialization error - unknown configuration key: 'not_configured'
```

### Steps to Reproduce the Problem
1.  run `kics scan -p ./`

### Specifications
-   Version: 1.5
-   Platform: Mac Big Sur
-   Subsystem: zsh 5.7.1

**Comment by rafaela-soares** [comment]
Hi, @corydorning 🙂 

I was not able to reproduce the issue in Windows and Linux. Can you give us more information, please?
Meanwhile, we will try to test it on Mac.

**Comment by corydorning** [comment]
mac is the only environment i tested this on and the above command didn't work.

**Comment by joaorufi** [comment]
Hi, @corydorning 

I managed to reproduce the issue by scanning a path with a `kics.config` file at the root of the directory containing the key `not_configured`. 
Kics throw an error when it does not recognize the key present on the config file.

Could you verify your scanning directory and make sure if there is a config file with a wrong key on it?

**Comment by joaorufi** [comment]
Your `kics.config` is invalid because `not_configured` is not a valid key for kics. You can see templates of a valid configuration file in this [link](https://github.com/Checkmarx/kics/blob/master/docs/configuration-file.md#templates) .

Also, it's possible to write with a `yaml` format so you can add comments if needed.
