### ISSUE TITLE
Multiple paths for queries

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4809]
In the case when we need to add our own queries to the default **queries** (which are very great BTW ! thank you), it seems that there's no way to pass multiple **queries paths**.

**Describe the solution you'd like**

```bash
kics scan --queries-path /app/default/queries --queries-path /app/my/queries
```

or

```bash
kics scan --queries-path /app/default/queries:/app/my/queries
```
**Describe alternatives you've considered**

In a CI usecase : 
- we can create a single directory which contains the default queries and our queries which fit to my specific needs, then we use the kics CLI
- we can execute 2 times KICS

```bash
kics scan --queries-path /app/default/queries
kics scan --queries-path /app/my/queries
```

**Comment by jycamier** [comment]
Related issue on the github action: 
https://github.com/Checkmarx/kics-github-action/issues/41

**Comment by rafaela-soares** [comment]
Hello, @jycamier 🙂 

Thank you so much for getting in touch with us! 

We are happy to inform you that we are working on that in PR #4813!
