### ISSUE TITLE
Need to refresh the docker image related to the github action Checkmarx/kics-github-action

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4810]
Currently, your official github action https://github.com/Checkmarx/kics-github-action execute the command within a container created from the image `checkmarx/kics:gh-action`.

This image isn't up to date and the build is manually triggered.
As a consequence, it miss in the github action all new queries created since 26th november 2021

**Comment by joaoReigota1** [comment]
Hi @jycamier, thank you for alerting us of this issue, the KICS GitHub Action was now updated to version 1.5.1
Thank you for using KICS!
