### ISSUE TITLE
Kics different behavior on similar scans (using flag -t)

### ISSUE THREAD

**Issue by cxlucas** [Checkmarx/kics#4848]
### Expected Behavior

When running "`kics scan -p sample.zip -o output`" using (or not) the **flag -t**, kics must run the queries and create, if the scan is valid, a results.json

### Actual Behavior

Kics generates a results.json if the flag -t was provided, otherwise, it will display "No files were scanned".

### Steps to Reproduce the Problem

1. Download the sample (or create an empty zip file).
2. Execute kics scans 2 times using the attached sample (empty zip file):
 - 1. `kics scan -p sample.zip -o output1` - will display "No Files were scanned" and it will not generate a results.json file.
 - 2. `kics scan -p sample.zip -o output2 -t terraform` - will perform a scan with 0 results and it will generate a results.json file.

### Specifications

-   Version: N/A
-   Platform: N/A
-   Subsystem: N/A

### Attachments
[sample.zip](https://github.com/Checkmarx/kics/files/8079776/sample.zip)

**Comment by rafaela-soares** [comment]
Resolved in version 1.6 😊
