### ISSUE TITLE
exclude-queries option isn't easy to use

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4849]
## My Problem

The `exclude-queries` option is a pain on the neck to use.

For exemple, as a yaml file configuration : 

```yaml
exclude-queries: "5617a9b5-3be9-4835-a188-695b8e6d3609,dd86685a-40ff-4c7e-a65e-523a8ca874cf,87399016-7f59-471e-afa8-8f518ad5b36e"
``` 

Not so easy to read of update.
So, I have simplify a bit the way to write my configuration.

```yaml
exclude-queries: >-
  5617a9b5-3be9-4835-a188-695b8e6d3609, 
  dd86685a-40ff-4c7e-a65e-523a8ca874cf,
  87399016-7f59-471e-afa8-8f518ad5b36e
``` 

But, I don't know the UUID and I would like to add a comments for each rules to know in 6 months what are the excluded-queries.

## Describe the solution you'd like

```yaml
exclude-queries: 
  ## terraform/aws/check_foobar_is_foobar
  - 5617a9b5-3be9-4835-a188-695b8e6d3609
  ## terraform/aws/check_foo_is_foo
  - dd86685a-40ff-4c7e-a65e-523a8ca874cf
  ## terraform/aws/check_bar_is_bar
  - 87399016-7f59-471e-afa8-8f518ad5b36e
```

**Comment by rafaela-soares** [comment]
Hello, @jycamier 🙂 I hope this message finds you well!

The documentation does not mention it, but the solution you suggested already works in the configuration file. Did you try it? Can you give us more information, please?

Thank you so much for reaching us!

**Comment by jycamier** [comment]
Excellent @rafaela-soares 
I try this so.
