### ISSUE TITLE
A way to ignore query for a specific resource

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4859]
## Needs

It will be great to get a way to ignore a query on a ressource.

## The solution I would like

Sometimes, we don't want to have an AWS S3 bucket versionned and encrypted.

```terraform
#kics:ignore:568a4d22-3517-44a6-a7ad-6a7eed88722c kics:ignore:5fb49a69-8d46-4495-a2f8-9c8c622b2b6e
resource "aws_s3_bucket" "backend" {
    bucket = "backend"
    acl    = "private"
}
```

**Comment by williamwd** [comment]
I kept finding this ticket instead of the docs when searching for a solution, so here's the [documentation](https://github.com/Checkmarx/kics/blob/master/docs/running-kics.md#using-commands-on-scanned-files-as-comments)
