### ISSUE TITLE
Terraform AWS 4.0 Provider

### ISSUE THREAD

**Issue by PatrickRice-KSC** [Checkmarx/kics#4863]
The KICS terraform scanning now throws a significant number of false positives related to AWS S3 buckets due to the breaking changes within the AWS 4.0 terraform provider. Rules such as: `S3 Bucket should have versioning enabled` and `S3 Bucket SSE Disabled` now return a false positive on every resource as those configurations were moved into separate resource bloc's that reference the bucket ID.

KICS should update to support the AWS 4.0 terraform provider. Which set of s3 rules to apply should likely be keyed off the aws terraform provider version.

**Comment by rafaela-soares** [comment]
Hello, @PatrickRice-KSC 🙂 

Thank you so much for bringing this matter to us. We will take a look as soon as possible!

**Comment by rafaela-soares** [comment]
Hello again, @PatrickRice-KSC 🙂 

Meanwhile, you can exclude these queries from running KICS with `--exclude-queries 568a4d22-3517-44a6-a7ad-6a7eed88722c,6726dcc0-5ff5-459d-b473-a780bef7665c`.

**Comment by PatrickRice-KSC** [comment]
Thanks @rafaela-soares ! that's the current workaround that we implemented yesterday, I just didn't want it to be a long-term solution because obviously I want to ensure our configurations are scanned for those rules 😄

**Comment by rafaela-soares** [comment]
Hi, @PatrickRice-KSC! We are working on that in PR #4872.

**Comment by PatrickRice-KSC** [comment]
Hey @rafaela-soares  - Any idea when this issue will be resolved? There doesn't seem to be a ton of action on the PR  😞

**Comment by rafaela-soares** [comment]
Hi, @PatrickRice-KSC!

We have to be sure about the deprecated version identification. Additionally, we will need to change the KICS queries tests approach. Since this change can bring possible breaking changes, we will take care of it before 1.6.0 (as soon as possible). The matter is not forgotten 😊

**Comment by rafaela-soares** [comment]
Hi, @PatrickRice-KSC!

We have to be sure about the deprecated version identification. Additionally, we will need to change the KICS queries tests approach. Since this change can bring possible breaking changes, we will take care of it before 1.6.0 (as soon as possible). The matter is not forgotten 😊

**Comment by PatrickRice-KSC** [comment]
@rafaela-soares  - Not a problem, I appreciate the update 😄 . We just have teams who keep running into it, so I was curious about progress.

Let me know if I can help in any way!

**Comment by rafaela-soares** [comment]
Thank you so much for your disponibility, @PatrickRice-KSC! We will take care of it as soon as possible!

**Comment by rafaela-soares** [comment]
Hello, @PatrickRice-KSC!

We came up with a better approach to cover Terraform AWS 4.0 Provider. We are updating the PR. Hope it will be ready for version 1.5.8 😊

**Comment by kaplanlior** [comment]
@rafaela-soares notice some feedback from this thread https://www.reddit.com/r/Terraform/comments/uq1ppv/terraform_aws_40_provider_migration/ changes / breaks between minor versions
