### ISSUE TITLE
DinD Error : read: connection reset by peer / maybe OMMkilled

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4915]
In a DinD context, the github action is very often encountered this error : 

```
time="2022-03-01T16:37:00Z" level=error msg="error waiting for container: unexpected EOF"
read tcp 127.0.0.1:43918->127.0.0.1:2376: read: connection reset by peer
```

It seams that a OMM kill... 

The actual runner is a : 
- request : 
  - 2 CPU
  - 2 GB
- limit : 
  - 4 CPU
  - 4 GB

Is exist a workaround ?

**Comment by joaorufi** [comment]
Hi @jycamier, hope you are doing well!

Could you give us more information about your github action for us to try to reproduce the error?

**Comment by jycamier** [comment]
Finaly, it just my DockerInDocker sidecar which a bit little !
