### ISSUE TITLE
Check custom tag

### ISSUE THREAD

**Issue by changhyuni** [Checkmarx/kics#4917]
### Platform
* Terraform

### Provider
* AWS

### Description
Can I create a query to check the value of the custom aws tag value?
When I looked it up, I could only check the tag key.

(https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/resource_not_using_tags/query.rego)

**Comment by joaorufi** [comment]
Hi @changhyuni, hope you are doing well.

Yes, it's possible to create this query. Suppose we are looking at [this](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/resource_not_using_tags/test/positive1.tf) terraform file, you can check the tag value in this way: `resource.tags.Name`.

Here is a complete example
```
CxPolicy[result] {
    resource := input.document[i].resource[res][name]
    resource.tags.Name == "test"
    result := "tag 'Name' cannot be equal to 'test'"
}
```

**Comment by changhyuni** [comment]
@joaorufi oh I was looking for it. Thank you. I need to learn more about OPA Rego.
