### ISSUE TITLE
Need a homebrew upgrade

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#4923]
Currently,  KICS release of homebrew isn't update.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/984570/157009184-7ccbeb46-6802-4fac-8ebc-ffc9b76a24dc.png">

We need an upgrade !

**Comment by joaorufi** [comment]
Hi @jycamier, thanks for contacting us!

KICS deprecated the availability of binaries from the version 1.5.2 and on. 

The latest possible version for homebrew is 1.5.1.

**Comment by jycamier** [comment]
Hi @joaorufi 

Alright ! Thank you.
