### ISSUE TITLE
Secret values are displayed as plain text in the reports

### ISSUE THREAD

**Issue by geowalrus4gh** [Checkmarx/kics#4975]
AWS Access Key id and secret are displayed as plain text in the results report files. 

Identified keys and passwords should not display as plain text. Any possibility to mask the values or exclude the real values ?

**Comment by anterosilva1985** [comment]
Hi @geowalrus4gh,

First of all sorry for the delay on the feedback and thank you for our input. 
This feature is going to be implemented in Kics 1.6 version. 

Regards,
Antero Silva
Product Manager - Kics

**Comment by rafaela-soares** [comment]
Hi, @geowalrus4gh!

Thank you so much for bringing this suggestion. KICS 1.6 version implements it 😊
