### ISSUE TITLE
Homebrew version updates?

### ISSUE THREAD

**Issue by grantyoung** [Checkmarx/kics#5006]
Hey.

The homebrew tap is still only installing v1.5.1. Is it expected to get the newer versions or should I move to a different install method?

**Comment by nunoocx** [comment]
Hi @grantyoung, we deprecated the binaries in v 1.5.2, which directly affects homebrew.
We strongly suggest you to move to using our docker images. 
let us know if you need any help on that!

**Comment by grantyoung** [comment]
Oh ok, thanks. Will do that.

**Comment by grantyoung** [comment]
Although you may want to remove the [docs section then](https://docs.kics.io/latest/getting-started/#homebrew)?
