### ISSUE TITLE
Add/Update \[QUERY_NAME\] query for \[PLATFORM\] (Terraform, Ansible, ..)

### ISSUE THREAD

**Issue by gafnit-lightspin** [Checkmarx/kics#5058]
### Platform
Terraform

### Provider
AWS

### Description
[This query](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/iam_policy_grants_full_permissions/query.rego#L6) search for iam_policy_grants_full_permissions.

The current evaluated documents are:
"aws_iam_role_policy", "aws_iam_user_policy", "aws_iam_group_policy", **"aws_iam_policy_attachment"**

but we believe that the last one should be replaced:
"aws_iam_role_policy", "aws_iam_user_policy", "aws_iam_group_policy", **"aws_iam_policy"**

**Comment by cxMiguelSilva** [comment]
Hi @gafnit-lightspin
Thank you so much for contacting us and reporting this issue. 
The PR #5064 solves this problem!
