### ISSUE TITLE
Getting "S3 Bucket Logging Disabled" when using "aws_s3_bucket_logging" Terraform resource

### ISSUE THREAD

**Issue by liorjacobian** [Checkmarx/kics#5084]
when running Kics on a Terraform file(please see attached) using "aws_s3_bucket_logging" resource for S3 logging I'm getting:

> S3 Bucket Logging Disabled, Severity: LOW, Results: 2
> Description: S3 bucket without logging
> Platform: Terraform
> 
> 	[1]: ./s3-log.tf:10
> 
> 		009:
> 		010: resource "aws_s3_bucket" "log_bucket" {
> 		011:   bucket = "my-tf-log-bucket"
> 
> 
> 	[2]: ./s3-log.tf:1
> 
> 		001: resource "aws_s3_bucket" "example" {
> 		002:   bucket = "my-tf-example-bucket"
> 		003: }

Seems like the resource "aws_s3_bucket_logging" is not supported and therefore the error I'm getting(looks like there is a  list of other resources also which are not supported).
By the way, when running bridgecrew checkov on the same file, it supports the "aws_s3_bucket_logging" resource and Im not getting any error regarding logging not enabled.

### Expected Behavior
I believe Kics shouldn't indicate there is an issue and that logging is not enabled. 

### Steps to Reproduce the Problem
Running with latest Kics version version on the attached Terraform file

[s3-bucket-logging.example.txt](https://github.com/Checkmarx/kics/files/8378286/s3-bucket-logging.example.txt)

**Comment by cxAndreFelicidade** [comment]
Hello liorjacobian, we will be fixing this in one of our PR's that is currently being drafted, to support terraform 4.0. Please refer to this [PR](https://github.com/Checkmarx/kics/issues/4863) for more information.

Thank you for being so attentive!

**Comment by rafaela-soares** [comment]
Hello, @liorjacobian!

We are updating the PR in the hope it will be ready for version 1.5.8 😊
