### ISSUE TITLE
[Feat] Allow user to specify the directories to look for when performing IaC scanning for terraform 

### ISSUE THREAD

**Issue by gopipara** [Checkmarx/kics#5113]
Hi,

Have come across this open source solution recently that supports various vulnerability scans. 👍

**Problem Statement:**

We make use of Gitlab for our CI/CD platform. Gitlab seems to be relying on KICS for IaC scanning. At the moment, it seems there is no way for a user to specify what dirs to look in when performing IaC scanning for terraform. It will only look for files with **.tf** extension and input variables using **terraform.tfvars** or files with **.auto.tfvars** extension that are in same directory of **.tf** files

**Some context:** 
We are using terraform to manage our GCP infra. Our repository structure is below
```
.
├── README.md
├── generator.py
├── modules
│   ├── main.tf
│   ├── outputs.tf
│   └── variables.tf
├── pipeline.py
├── projects
│   ├── prj_crh_cep_npd_yls_eng_amer
│   │   ├── ansible.tfvars
│   │   ├── bastion.tfvars
│   │   ├── bigtable.tfvars
│   │   ├── buckets.tfvars
│   │   ├── cloud_sql.tfvars
│   │   ├── composer.tfvars
│   │   ├── engvm.tfvars
│   │   ├── gke.tfvars
│   │   ├── kafka_bk_dev.tfvars
│   │   ├── kafka_zk_dev.tfvars
│   │   ├── terragrunt.hcl
│   │   └── vars.hcl
│   ├── prj_crh_cep_npd_yls_imp_amer
│   │   ├── ansible.tfvars
│   │   ├── bastion.tfvars
│   │   ├── bigtable.tfvars
│   │   ├── buckets.tfvars
│   │   ├── cloud_sql.tfvars
│   │   ├── composer.tfvars
│   │   ├── engvm.tfvars
│   │   ├── gke.tfvars
│   │   ├── kafka_bk_dev.tfvars
│   │   ├── kafka_zk_dev.tfvars
│   │   ├── terragrunt.hcl
│   │   └── vars.hcl
│   └── prj_crh_cep_shd_yls_ops_glbl
│       ├── buckets.tfvars
│       ├── gke.tfvars
│       ├── terragrunt.hcl
│       └── vars.hcl
└── terragrunt.hcl

5 directories, 35 files
```

In a nutshell, `modules` dir would have nothing but few lines of code in `main.tf` file that calls the root modules from an other gitlab project, empty default variables in `variables.tf` file and outputs blocks in `outputs.tf`. There is no use of scanning those files as they have no actual code or variables. 

The way it is now, KICS is only raising flags from those `*.tf` files and not very helpful in terms of validation as it display's vulnerabilities like `Output Without Description`, `Variable Without Type` by only looking at `*.tf` files in `modules` dir which would not have the actual user input vars.

**My expectation:**

`*.tfvars` in other directories would contain the actual variables that we feed to modules in `modules/main.tf`. I expected KICS to scan the user input variables we pass through the `*.tfvars` files and raise flags if there are any over permissive roles that are being granted to a user/group or using a default service account which has `Editor` access on a `Google Cloud Platform` project for example or something of this sort.

**Comment by gopipara** [comment]
I have sent a sample project via email to your core team.

**Just a bit more detail about the project i sent via email:**

Once you unzip the attached file you should see modules and projects dirs. modules dir contains `main/variables/outputs.tf` files. 

Each module in `main.tf` file will refer to a remote location where the source code for the module is located, this way we can keep our parent modules centralized and use them as necessary.

`outputs.tf` file will show the outputs from the modules in `main.tf` which in turn will return from parent modules output as each module itself is referring to parent module in remote location.

variable values in `variables.tf` will be empty by default. we will pass the variable input from `*.tfvars` files in `projects/project` dir

So, technically when we run KICS scan pointing it to a root dir it will only find `*.tf` files wherever they are in the dir tree (this is actually good for us because as part of initialization, terraform will download the parent modules into the current dir tree) and analyzes the source code. 

Scanning those files without taking the `*.tfvars` in the `projects/project` dir into account will produce false positives as the attributes in the source code may be optional and we set it to `null` if it is not defined in the `*.tfvars`. 

For example KICS scan produced a Medium level vulnerability saying below
<img width="931" alt="Screen Shot 2022-06-04 at 5 55 20 PM" src="https://user-images.githubusercontent.com/14302157/172026898-1030613b-d28b-4f37-b1d5-bf5f2aa47f54.png">

the above points at below
<img width="876" alt="Screen Shot 2022-06-04 at 5 55 08 PM" src="https://user-images.githubusercontent.com/14302157/172026902-6f768191-7eb9-44db-8cd1-9c5fcce68f03.png">

but in reality, we have defined the service account through a variable in `*.tfvars` file and are passing it to `terraform` commands.
 
As of now, there seems no way to specify extra locations where the `*.tfvars` files are located. My expectation is KICS would let me provide the `*.tfvars` dir path and let it warn based on the user input; like (if any over permissive roles are being granted, any plain text passwords etc.. for example).

**Below is an other example just in case:**
KICS scan produced below High vulnerability 
<img width="1021" alt="Screen Shot 2022-06-04 at 6 15 34 PM" src="https://user-images.githubusercontent.com/14302157/172027101-abe0d5c2-0629-40e7-87c4-fbecb3f74b16.png">

But in reality, we have `logging` attribute present in the resource but it is dynamic and we enable it through the variable passed via *.tfvars` file.


Hope this helps.

**Comment by rafaela-soares** [comment]
Hello, @gopipara!

Thank you so much for sending the project and for the detailed explanation!

We will discuss internally this feature as soon as possible! Thank you so much for suggesting it 🚀

**Comment by asofsilva** [comment]
Hello @gopipara,

Thanks again for raising this question! 

The fix to this case is now merged. 

To solve it, were added two features:
1- An optional flag was added to indicate where the terraform variables are present: https://github.com/Checkmarx/kics/pull/6456/files#diff-be4f567a7d9020aa5351b77b667903229d9ac7235a1d710f46d400f4ce1f7585R56, use it in kics scan, giving to it the path to your variables.

2- Another way to do this is by adding an optional line (a comment line like: // kics_terraform_vars: path/to/vars) in your terraform file, to indicate where the used variables are. 

If you use both features at the same time, the flag will prevail.

Is this solution suitable for your needs?
