### ISSUE TITLE
Rule CloudFormation dynamodb_with_aws_owned_cmk. Problem with SSEType

### ISSUE THREAD

**Issue by uripb** [Checkmarx/kics#5189]
Hello,

We are using Kics v1.5.5.

We are using AWS CDK to create the cloudFormation template.

The description rule says that we should be encrypting using AWS Managed CDK instead of AWS owned CDK.

CDK example code (create dynamodb table):
```typescript
const table = new dynamodb.Table(this, tableName, {
tableName: tableName,
billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
removalPolicy: RemovalPolicy.RETAIN,
partitionKey: {
   name: 'testId', type: dynamodb.AttributeType.NUMBER
},
stream: StreamViewType.NEW_IMAGE,
pointInTimeRecovery: true,
encryption: TableEncryption.AWS_MANAGED
```
Cloudformation output If we set ```encryption: TableEncryption.AWS_MANAGED```:
```json
"Resources": {
    "ddbdevpushnotificationsusersA2AD2302": {
      "Type": "AWS::DynamoDB::Table",
      "Properties": {
           "SSESpecification": {
                 "SSEEnabled": true
            },
           "TableName": "ddb-test-table"
           ...
      }
}
```

This rule checks ```properties.SSESpecification.SSEType == "KMS"``` (line 10 and 43), but when encryption is AWS_MANAGED the SSEType doesn't exists in CF output.

### Actual Behavior

```bash
DynamoDB With Aws Owned CMK, Severity: HIGH, Results: 5
Description: AWS DynamoDb should be encrypted using AWS Managed CMK, instead of AWS-owned CMK. To verify this, SSEEnabled must be verified if false for AWS-owned CMK or true for AWS-Managed CMK. Default value is false.
Platform: CloudFormation
```

### Expected Behavior

Successful result. We use AWS MANAGED table encryption.

Thanks.

**Comment by cxMiguelSilva** [comment]
Hi @uripb !
Thank you for your input.
Hope #5210 addresses this issue.
