### ISSUE TITLE
CloudFormation rule sns_topic_is_publicly_accessible_for_subscription. Problem with Subscription

### ISSUE THREAD

**Issue by uripb** [Checkmarx/kics#5190]
Hello,

We are using Kics v1.5.5.

We are using AWS CDK to create the cloudFormation template.

The rule "sns_topic_is_publicly_accessible_for_subscription" checks if the SNS Topic has Subscription property.

CDK example code (from AWS CDK documentation):
```typescript
const myTopic = new sns.Topic(this, 'MyTopic', {
   topicName: 'mytopic',
   masterKey: Alias.fromAliasName(this, 'SnsKeyMyTopic', 'alias/aws/sns')
});

myTopic.addSubscription(new EmailSubscription('test@example.com'));
```

CloudFormation output:
```json
"mytopicF1111A24": {
      "Type": "AWS::SNS::Topic",
      "Properties": {
        "TopicName": "mytopic",
        ...
     }
},
"mytopictestexamplecomCB22222C3": {
      "Type": "AWS::SNS::Subscription",
      "Properties": {
        "Protocol": "email",
        "TopicArn": {
          "Ref": "mytopicF1111A24"
        },
        "Endpoint": "test@example.com"
      },
      "Metadata": {
        "aws:cdk:path": "stack-test/mytopic/test@example.com/Resource"
      }
 },
...
```

The rule checks ```resourceSNS[nameSNS].Properties.Subscription```. But using CDK, CF doesn't has ```Subscription``` property.

CDK creates an "AWS::SNS::Subscription" with an SNS Topic Reference.

### Actual Behavior

```bash
SNS Topic is Publicly Accessible For Subscription, Severity: LOW, Results: 2
Description: Ensure appropriate subscribers to each SNS topic
Platform: CloudFormation
```

### Expected Behavior

Successful result. We have Subscription using resource "AWS::SNS::Subscription".

Thanks.

**Comment by cxMiguelSilva** [comment]
Hi @uripb !
Thank you for your input.
Hope #5210 addresses this issue.
