### ISSUE TITLE
Duplicate api_gateway_with_open_access CF rule

### ISSUE THREAD

**Issue by uripb** [Checkmarx/kics#5191]
Hello,

I think there are two duplicate rules, a Medium severity and a Low severity.

- api_gateway_with_open_access (medium)
- open_access_to_resources_through_api (low)

Both rules check that ```AuthorizationType = "NONE"``` and ```HttpMethod != "OPTIONS"```.

Thanks.

**Comment by cxMiguelSilva** [comment]
Hi @uripb !
Thank you for your input.
Hope #5210 addresses this issue.
