### ISSUE TITLE
Support CodeClimate Engine output

### ISSUE THREAD

**Issue by rndmh3ro** [Checkmarx/kics#5231]
**Is your feature request related to a problem? Please describe.**
We use kics in our Gitlab-CI Pipeline to check our code.
In Gitlab there's a Code Quality Widget that can display nice results of kics directly in the Merge Request.
However this requires that kics outputs its results in Code Climate fashion.

More information:
https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html
https://gitlab.com/gitlab-org/gitlab/-/issues/19248

**Describe the solution you'd like**
kics should support CodeClimate output.

**Comment by joaorufi** [comment]
Hi @rndmh3ro, thanks for the suggestion!

We are going to develop this feature as soon as possible :)

**Comment by rndmh3ro** [comment]
Thanks for this really fast implementation! I'll take a look soon.
