### ISSUE TITLE
cannot install KICS older then V1.5.1 using the tag on linux machine 

### ISSUE THREAD

**Issue by daviduash** [Checkmarx/kics#5241]
the URL for the download file has changed since V1.5.2 and the installation script does not support it 

curl -sfL 'https://raw.githubusercontent.com/Checkmarx/kics/master/install.sh' | bash -s -- -b /usr/local/bin v1.5.1 ==> WORKS
curl -sfL 'https://raw.githubusercontent.com/Checkmarx/kics/master/install.sh' | bash -s -- -b /usr/local/bin v1.5.2 ==> FAILES

**Comment by rafaela-soares** [comment]
Hello, @daviduash  🙂 Thank you so much for reaching us!

KICS deprecated the availability of binaries in the GitHub releases assets as of version 1.5.2. The latest (and last) binary available is 1.5.1: https://github.com/Checkmarx/kics/releases/tag/v1.5.1

However, KICS is available as a [Docker image](https://hub.docker.com/r/checkmarx/kics). You can see the documentation [here](https://github.com/Checkmarx/kics/blob/master/docs/getting-started.md#docker).

Let me know if you need any help 😊

**Comment by todd-hough** [comment]
At my company the desktop security configuration prevents using bind mounts with Docker.  This makes it very inconvenient to use Kics in Docker form.  Please reconsider supporting standalone binaries again.
