### ISSUE TITLE
network_acl_with_unrestricted_access_to_rdp possible incorrect test

### ISSUE THREAD

**Issue by binarymist** [Checkmarx/kics#5245]
Just looking at: https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/network_acl_with_unrestricted_access_to_rdp/test/negative2.tf#L23 and at first appearances it looks like `positive1` should be `negative2`?

**Comment by cxMiguelSilva** [comment]
Hi @binarymist 
Thank you so  much for your input!!
Hope #5296 solves this issue.

**Comment by binarymist** [comment]
LGTM
