### ISSUE TITLE
Terraform AWS remote desktop port open - tests seem to contradict the rule

### ISSUE THREAD

**Issue by binarymist** [Checkmarx/kics#5276]
In looking at this rule:

* https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/remote_desktop_port_open/query.rego

and then looking at the tests for it:

* https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/remote_desktop_port_open/test/negative.tf
* https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/remote_desktop_port_open/test/positive.tf

The rule appears to be saying don't have the ingress port 3389 open. It doesn't appear to say anything about whether it's accessible to the world or not.

The tests on the other hand are specific about whether the rule is open to world or not.

The title of the rule seems to be in alignment with the rule but not the tests. Do the tests need some adjustment to take the `cidr_blocks` out of the equation?

**Comment by cxMiguelSilva** [comment]
Hi @binarymist hope you are doing great!
Currently this rule checks if the 3389 port is within the port interval, is TCP protocol and cidr_blocks contains 0.0.0.0/0. That is done through this [function](https://github.com/Checkmarx/kics/blob/master/assets/libraries/terraform.rego#L12) in terraform.rego file. Are you proposing to change the query name?

**Comment by binarymist** [comment]
Oh I see. I didn't expect a function called openPort to also have the side effect of checking the cidr_block, etc. I wonder how many ripples it would cause if we either:

* Renamed the `openPort` function in terraform.rego to what it actually does, say something along the lines of `openPortFullIPRangeTCP`
* Just used the three seperate functions... which would make the intent completly clear

Thoughts?

**Comment by cxMiguelSilva** [comment]
Hi @binarymist
We have changed AWS open port queries names and a changed the terraform.rego file function name. What do you think of the approach?
