### ISSUE TITLE
tf azure sensitive port is exposed to small public network - incorrect possitive test?

### ISSUE THREAD

**Issue by binarymist** [Checkmarx/kics#5287]
Looking at rule: https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/

Name says: "sensitive port is exposed..."

Looking at the [positive test](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/azure/sensitive_port_is_exposed_to_small_public_network/test/positive.tf) for `azurerm_network_security_rule.positive1` `source_address_prefix` has a small public network suffix, but the `destination_port_range` which is "61621" doesn't appear to be a sensitive port. Is this incorrect (bug)?

**Comment by binarymist** [comment]
My bad. 61621 is "Cassandra OpsCenter"

**Comment by rafaela-soares** [comment]
Hello, @binarymist!

Thank you so much for using KICS and contacting us 😊 

You can find the ports dictionary [here](https://github.com/Checkmarx/kics/blob/master/assets/libraries/common.rego#L183:L247).

**Comment by binarymist** [comment]
My bad, sorry for the false lead.
