### ISSUE TITLE
azure storage_account_not_using_latest_tls_encryption_version positive test should be negative

### ISSUE THREAD

**Issue by binarymist** [Checkmarx/kics#5301]
I think the [positive test](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/test/positive.tf#L1-#L11) for azure storage_account_not_using_latest_tls_encryption_version is not actually positive.

According to the [Terraform doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#min_tls_version), the default value for `min_tls_version` is TLS1_2, which should be a negative result.

Which will of course also mean that the first [`CxPolicy`](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/azure/storage_account_not_using_latest_tls_encryption_version/query.rego#L5-#L16) requiring `min_tls_version` to be defined and not null appears to be incorrect.

**Comment by cxMiguelSilva** [comment]
Hi @binarymist hope you are doing great!
Thank you so much for your input.
We have removed the check that requires min_tls_version to be defined in this PR #5314.
