### ISSUE TITLE
Getting CPU info fails on macOS Docker

### ISSUE THREAD

**Issue by andyshinn** [Checkmarx/kics#5364]
Found a bug? You're welcome to [![GitHub Discussions](https://img.shields.io/badge/chat-discussions-blue.svg?style=flat-square)](https://github.com/Checkmarx/kics/discussions)

- **Please make sure to:**
  - Describe in details what the problem is
  - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG`)
  - Attach the scanned sample files, anonymize the data if the original file cannot be provided
  - When attaching files to the issue make sure they are properly formatted

### Expected Behavior

(Which results are expected from KICS?)

No error on getting CPU info.

### Actual Behavior

(Formatted logs and samples helps us to better understand the issue)

```
Scanning with Keeping Infrastructure as Code Secure v1.5.8


9:01PM INF Scanning with Keeping Infrastructure as Code Secure v1.5.8
9:01PM INF Operating system: linux
9:01PM INF Total memory: 3.8G
9:01PM ERR failed to get CPU error="open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory"
```

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  `docker run -it -w /path -v $PWD:/path checkmarx/kics:v1.5.8 scan -p /path -v`

### Specifications
(N/A if not applicable)

-   Version: 1.5.8
-   Platform: macOS 12.4
-   Subsystem: Docker Desktop 4.7.0 (77141)

Related to #5321

**Comment by joaorufi** [comment]
Hi @andyshinn , thanks for the issue! I'll be working to fix that as soon as possible!
