### ISSUE TITLE
JUnit XML tests output in CircleCI are confusing

### ISSUE THREAD

**Issue by andyshinn** [Checkmarx/kics#5389]
**Is your feature request related to a problem? Please describe.**
The JUnit test descriptions are confusing to understand at first and don't align to the verbose description output very well.

Here is the output for a Terraform issue:

```
VPC Subnet Assigns Public IP, Severity: MEDIUM, Results: 3
Description: VPC Subnet should not assign public IP
Platform: Terraform

	[1]: terraform/vht-audit/vpc.tf:5

		004: 
		005: module "audit_applications_vpc" {
		006:   source          = "terraform-aws-modules/vpc/aws"
```

And the associated JUnit test output as shown by CircleCI:

```
A problem was found on 'terraform/vht-audit/vpc.tf' file in line 5, audit_applications_vpc.map_public_ip_on_launch is set to false, but audit_applications_vpc.map_public_ip_on_launch is set undefined.
```

**Describe the solution you'd like**

I think the JUnit test description should be more in line with the verbose stdout. Maybe something like:

```
Severity: MEDIUM - VPC Subnet should not assign public IP. Problem found on 'terraform/vht-audit/vpc.tf' file in line 5: audit_applications_vpc.map_public_ip_on_launch is expected to be set to false but is undefined.
```

**Describe alternatives you've considered**
Using stdout is more descriptive than test results at the moment which is the best alternative.

**Additional context**
None.

**Comment by rafaela-soares** [comment]
Hello, @andyshinn!

Thank you so much for suggesting this improvement! 🚀 

PR #5418 addresses your suggestion. 

As an example:
```
[Severity: MEDIUM, Query description: VPC Subnet should not assign public IP] Problem found on 'assets\queries\terraform\aws\vpc_subnet_assigns_public_ip\test\positive1.tf' file in line 13. Expected value: aws_subnet[positive].map_public_ip_on_launch is set to false or undefined. Actual value: aws_subnet[positive].map_public_ip_on_launch is set to true"
```

P.S. As the expected value and actual value of each query result are defined separately, it is very difficult to merge them into an intuitive phrase. So, as an intuitive solution, the message presents the expected value and the actual value separately.

**Comment by andyshinn** [comment]
Thanks. Those new messages are definitely a big improvement! Much more human readable.
