### ISSUE TITLE
AKS Uses Azure Policies Add-On Disabled  && AKS RBAC Disabled - azurerm 3.0

### ISSUE THREAD

**Issue by gherasim-learn** [Checkmarx/kics#5453]
### Discussed in https://github.com/Checkmarx/kics/discussions/5452

<div type='discussions-op-text'>

<sup>Originally posted by **gherasim-learn** June  8, 2022</sup>
I upgraded the azurerm provider (terraform) from 2.73.0 to 3.9.0.
There were some changes described in the upgrade guide: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide

After updating the terraform code, KICS scan started to rapport two findings:
![image](https://user-images.githubusercontent.com/75733876/172624646-786e072b-ab9e-44f6-b3a2-d680af051c77.png)
and
![image](https://user-images.githubusercontent.com/75733876/172624724-88403ca4-abfa-4272-8d50-91d2485c73ae.png)

my cluster definition looks like that:
![image](https://user-images.githubusercontent.com/75733876/172625691-f7d16a2c-53c4-4c7c-945d-3c0ca2832b58.png)
Did I do something wrong or is it a problem with KICS?</div>

**Comment by eXXL** [comment]
I have the same issue. It looks to me that the related KICS queries have not been adjusted to the updated syntax of the terraform resources.

**Comment by rafaela-soares** [comment]
Hello everyone!

@gherasim-learn, thank you so much for bringing this matter!

@eXXL is right, we did not adjust to the updated syntax of the terraform resources yet. We apologize for that. It is something that we will try to slot more time!

Fortunately, @rndmh3ro adjusted both queries in PRs #5652 and #5661.


Thank you so much all of you for being attentive to this question! We appreciate a lot!
