### ISSUE TITLE
Terraform api gateway without waf should also include wafv2

### ISSUE THREAD

**Issue by AlexEndris** [Checkmarx/kics#5480]
This only checks for `aws_wafregional_web_acl_association` here:

https://github.com/Checkmarx/kics/blob/f398dff5b5d37ab36a2040d0b365e3cdefed869a/assets/queries/terraform/aws/api_gateway_without_waf/query.rego#L22

But you can also associate `aws_wafv2_web_acl_association` with a stage.

**Comment by rafaela-soares** [comment]
Hello @AlexEndris!

Thank you so much for your suggestion!

Would you feel comfortable contributing to fixing it? If so, we can help you and give some tips 😊

**Comment by AlexEndris** [comment]
If I knew how, I would do it, naturally.

 

I have no idea about Rego and was looking at the code contemplating how to add the other waf resource in that statement.. Maybe duplicate the function and just change the resource name and then call that additionally to the existing one?

**Comment by rafaela-soares** [comment]
Hello again, @AlexEndris!

We would be glad to do the fix for this query, of course. But maybe it will be understanding for you to dive in REGO. If you have an interest in it, [this course](https://academy.styra.com/courses/opa-rego) is very good. We also have some detailed documentation about the REGO queries [in our documentation](https://github.com/Checkmarx/kics/blob/master/docs/creating-queries.md).

As a suggestion for this fix, I came across with two options:

(1) Duplicate the function with an else:

```
has_waf_associated(apiGatewayName) {
    resource := input.document[_].resource.aws_wafregional_web_acl_association[_]
   
    associatedResource := split(resource.resource_arn, ".")
   
    associatedResource[0] == "${aws_api_gateway_stage"
    associatedResource[1] == apiGatewayName
} else {
    resource := input.document[_].resource.aws_wafv2_web_acl_association[_]
   
    associatedResource := split(resource.resource_arn, ".")
   
    associatedResource[0] == "${aws_api_gateway_stage"
    associatedResource[1] == apiGatewayName
}
```

(2) Consider both aws_wafregional_web_acl_association and aws_wafv2_web_acl_association

```
has_waf_associated(apiGatewayName) {

    targetResources := {"aws_wafregional_web_acl_association", "aws_wafv2_web_acl_association"}

    waf := targetResources[_]

    resource := input.document[_].resource[waf][_]
   
    associatedResource := split(resource.resource_arn, ".")
   
    associatedResource[0] == "${aws_api_gateway_stage"
    associatedResource[1] == apiGatewayName
}
```



Let me know if you are conformable to contribute one of them 😊 If so, it will be necessary to add a negative sample like this:

```
resource "aws_api_gateway_rest_api" "example" {
  body = jsonencode({
    openapi = "3.0.1"
    info = {
      title   = "example"
      version = "1.0"
    }
    paths = {
      "/path1" = {
        get = {
          x-amazon-apigateway-integration = {
            httpMethod           = "GET"
            payloadFormatVersion = "1.0"
            type                 = "HTTP_PROXY"
            uri                  = "https://ip-ranges.amazonaws.com/ip-ranges.json"
          }
        }
      }
    }
  })

  name = "example"
}

resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    redeployment = sha1(jsonencode(aws_api_gateway_rest_api.example.body))
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "example" {
  deployment_id = aws_api_gateway_deployment.example.id
  rest_api_id   = aws_api_gateway_rest_api.example.id
  stage_name    = "example"
}

resource "aws_wafv2_web_acl" "example" {
  name  = "web-acl-association-example"
  scope = "REGIONAL"

  default_action {
    allow {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}

resource "aws_wafv2_web_acl_association" "example" {
  resource_arn = aws_api_gateway_stage.example.arn
  web_acl_arn  = aws_wafv2_web_acl.example.arn
}

```

**Comment by AlexEndris** [comment]
I'll take a closer look tomorrow, something like the 2nd one would've been my intuition. Negative example for testing, right?

**Comment by rafaela-soares** [comment]
> I'll take a closer look tomorrow, something like the 2nd one would've been my intuition. Negative example for testing, right?
> 
> And yes, I can gladly do it. 😄

@AlexEndris Yes, inside the folder test 😊

**Comment by AlexEndris** [comment]
@rafaela-soares I'm just looking at the CONTRIBUTING.md seeing I need golint to test. But apparently golint is deprecated since 2 years. 

Also.. I put an additional negative.tf into the test folder, right?

**Comment by AlexEndris** [comment]
See attached pull request.

**Comment by lrstanley** [comment]
I actually fixed this a month or two ago internally for our company, just didn't get around to submitting a PR. You can use this version for the PR, if you'd like, as it's simpler/uses the terraform library for the relation checks:

```rego
package Cx
import data.generic.common as common_lib
import data.generic.terraform as tf_lib

waf := {
    "aws_wafv2_web_acl_association",
    "aws_wafregional_web_acl_association",
}

CxPolicy[result] {
    r_stage := input.document[i].resource.aws_api_gateway_stage[stage_id]
    r_waf := input.document[i].resource[waf[idx]][assoc_id]

    # checks to see if any waf associations map to each related stage.
    not tf_lib.has_relation(stage_id, "aws_api_gateway_stage", r_waf, "resource_arn")

    result := {
        "documentId": input.document[i].id,
        "searchKey": sprintf("aws_api_gateway_stage[%s]", [stage_id]),
        "issueType": "IncorrectValue",
        "keyExpectedValue": "API Gateway Stage is associated with a Web Application Firewall",
        "keyActualValue": "API Gateway Stage is not associated with a Web Application Firewall",
        "searchLine": common_lib.build_search_line(["resource", "aws_api_gateway_stage", stage_id], []),
    }
}
```

**Comment by AlexEndris** [comment]
I honestly can't say which is better. I just want it fixed. So, by all means. @rafaela-soares you decide. Doing ctrl + a and then copy this onto it isn't much of a hassle. I'm fine either way 😊.

**Comment by rafaela-soares** [comment]
Hello, @AlexEndris!

You can run `go test ./test` in the KICS folder to run the queries tests.

**Comment by rafaela-soares** [comment]
Regarding the better approach, I think the PR #5529 addresses a good one.

**Comment by rafaela-soares** [comment]
@AlexEndris

Furthermore, your suggestion is trying to match each `aws_api_gateway_stage` with each `aws_wafv2_web_acl_association` or `aws_wafregional_web_acl_association` defined. This can result in FP, like the following (kics scan -p ./assets/queries/terraform/aws/api_gateway_without_waf -q ./assets/queries/terraform/aws/api_gateway_without_waf):

<img width="457" alt="image" src="https://user-images.githubusercontent.com/74001161/175898611-4d53b8ce-703d-4983-a1df-b4ca51a84794.png">

If you need help to understand my points, let me know 😊

**Comment by AlexEndris** [comment]
@rafaela-soares Do you mean me, because I didn't use the "tf_lib" variant in my PR.

Also thank you for the suggestion with test. I'll do that.

**Comment by rafaela-soares** [comment]
@lrstanley

Furthermore, your suggestion is trying to match each `aws_api_gateway_stage` with each `aws_wafv2_web_acl_association` or `aws_wafregional_web_acl_association` defined. This can result in FP, like the following (kics scan -p ./assets/queries/terraform/aws/api_gateway_without_waf -q ./assets/queries/terraform/aws/api_gateway_without_waf):

<img width="457" alt="image" src="https://user-images.githubusercontent.com/74001161/175898611-4d53b8ce-703d-4983-a1df-b4ca51a84794.png">

If you need help to understand my points, let me know 😊
