### ISSUE TITLE
Query Metadata Recommendation Enhancement 

### ISSUE THREAD

**Issue by roi-orca** [Checkmarx/kics#5493]
Hi,
Recently I had a chance of investigating kics queries structure and metadata while fixing a few anomalies and descriptions.
It made me realize we might want to extend our metadata with `recommendation` in order to provide better results to kics users
`descriptionText` attribute contains in some of the queries both general description and recommendation on how to fix the issue in the relevant platform. I would like to separate them into different attributes, for example -
```
{
  "id": "de77cd9f-0e8b-46cc-b4a4-b6b436838642",
  "queryName": "CloudFront Logging Disabled",
  "severity": "MEDIUM",
  "category": "Observability",
  "descriptionText": "AWS Cloudfront distributions must have logging enabled, which means the attribute 'DistributionConfig.Logging' must be defined",
  "descriptionUrl": "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/logging-and-monitoring.html",
  "platform": "CloudFormation",
  "descriptionID": "3254d6d0",
  "cloudProvider": "aws"
}
```

To
```
{
  "id": "de77cd9f-0e8b-46cc-b4a4-b6b436838642",
  "queryName": "CloudFront Logging Disabled",
  "severity": "MEDIUM",
  "category": "Observability",
  "descriptionText": "AWS Cloudfront distributions must have logging enabled",
  "recommendation": "The attribute 'DistributionConfig.Logging' must be defined",
  "descriptionUrl": "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/logging-and-monitoring.html",
  "platform": "CloudFormation",
  "descriptionID": "3254d6d0",
  "cloudProvider": "aws"
}
```
and add `recommendation` to queries that missing such information on how to remediate the issue

**Comment by ArturRibeiro-CX** [comment]
Hi @roi-orca,

Thank you for raising your concerns and suggesting improvements to our metadata structure.

The information you're suggesting to add is already available in the output generated by KICS. It includes details regarding the expected value and actual value, which helps the user understand the issue and how to solve it. 

![image](https://github.com/Checkmarx/kics/assets/153724638/2b2f652b-67d4-47ad-8b4f-495cdb3ff1a3)

For instance, the "_actual_value_" describes the current state of the vulnerability found and the "_expected_value_" represents the recommendation.  These details can be found in the "_results.json_" file.

If you feel there are specific benefits not covered by our current setup, we're open to discuss potential changes. If you prefer seeing a recommendation field information directly in the KICS CLI, we can explore implementing it in the metadata.

Looking forward to your thoughts and thanks for your valuable feedback!
CC: @anterosilva1985
