### ISSUE TITLE
GitHub Action not working

### ISSUE THREAD

**Issue by SoniaDias** [Checkmarx/kics#5559]
### Expected Behavior

Integarte kics in my repo, with a GitHub Action and be able to run kics scan.

### Actual Behavior
I got a error executing the action
Error: KICS scan failed with exit code 50

### Steps to Reproduce the Problem

1.  My project: https://github.com/SoniaDias/docker_helloWorld
2.  Change something on Dockerfile and do a pull request
3.  Watch the job being executed 

### Specifications
(N/A if not applicable)

-   Version: kics-github-action@v1.5
[docker_helloWorld-main (1).zip](https://github.com/Checkmarx/kics/files/9052744/docker_helloWorld-main.1.zip)
[logs_9 (1).zip](https://github.com/Checkmarx/kics/files/9052745/logs_9.1.zip)

My yaml is on docker_helloWorld/[.github/workflows](https://github.com/SoniaDias/docker_helloWorld/tree/main/.github/workflows)

**Comment by rafaela-soares** [comment]
Hello, @SoniaDias!

Exit code 50 means that the KICS scan found any `HIGH` results. You can find the documentation about the KICS exit code [here](https://github.com/Checkmarx/kics/blob/master/docs/results.md#results-status-code).

If you want to ignore the results status code, you will need to use `ignore_on_exit: results` in the KICS GitHub action.

**Comment by gabriel-cx** [comment]
Hi @SoniaDias !

In our perspective, this issue is now considered resolved.
Do you need more support from us regarding this situation?
