### ISSUE TITLE
alicloud is not supported

### ISSUE THREAD

**Issue by roi-orca** [Checkmarx/kics#5560]
Hi,

Although you added alicloud queries it's not supported yet via the CLI.
[feat(alicloud): added support to Alicloud provider for Terraform](https://github.com/Checkmarx/kics/discussions/5000)

![Screen Shot 2022-07-06 at 11 50 28](https://user-images.githubusercontent.com/95563877/177510564-8c396aec-d6d2-4858-991c-5eed3b56f390.png)

Following the implementation, alicloud works only if cloud-provider flag is not set on the command.
Thanks

**Comment by rafaela-soares** [comment]
Hi, @roi-orca!

Thank you so much for noticing and reporting it! We will take care of it as soon as possible!

**Comment by rafaela-soares** [comment]
PR #5561 will fix it 😊
