### ISSUE TITLE
Add support for variables inbase image name

### ISSUE THREAD

**Issue by LvffY** [Checkmarx/kics#5621]
### Context

Because we want to analyse some multistage docker builds or just use variables in the process, we'd like kics to analyse correctly our variables. 

### Expected Behavior

(Which results are expected from KICS?)

Kics should send an error on the tag latest of the image

### Actual Behavior

(Formatted logs and samples helps us to better understand the issue)

With the right variables, kics could miss some warnings on tags of the base image. 

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1. Have the following dockerfile : 

```dockerfile
# syntax=docker/dockerfile:1
ARG BASE_IMAGE=alpine
ARG BASE_IMAGE_TAG=latest

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG} as main
```

2. Run kics analysis
```bash
docker run -t -v "$PWD/kics":/path checkmarx/kics scan -p "/path" -o "/path/"
```
3.  You do not get the following warning `Image Version Using 'latest', Severity: MEDIUM`

While you get the warning with the following docker file : 

```dockerfile
# syntax=docker/dockerfile:1
ARG BASE_IMAGE=alpine

FROM ${BASE_IMAGE}:latest as main
```

**Comment by rafaela-soares** [comment]
Hello, @LvffY!

Thank you so much for noticing and reporting! We are fixing it in PR #5621 😊

**Comment by rafaela-soares** [comment]
@LvffY, do you mind if we use your sample for unit test purposes?

**Comment by kaplanlior** [comment]
> @LvffY, do you mind if we use your sample for unit test purposes?

Good idea.... If so, please approve we can use them under Apache 2.0 license.

**Comment by LvffY** [comment]
@kaplanlior @rafaela-soares No problem for me, you can use it for test purposes under Apache license :)

**Comment by rafaela-soares** [comment]
Thank you so much, @LvffY!
