### ISSUE TITLE
TF IaC - AWS IAM Policy Check not Compatible with Resources that Don't support ARNs

### ISSUE THREAD

**Issue by adamkendall1** [Checkmarx/kics#5714]
Hi guys, me again.

I believe I've found an issue with this check that's running on my Terraform infrastructure code:

Check if an IAM policy is granting full permissions to resources from the get-go, instead of granting permissions gradually as necessary.

The check is flagging on resources which do not support identification by ARN. For example [Amazon Message Delivery Service](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonmessagedeliveryservice.html). Relevant excerpt from AWS documentation:

> Amazon Message Delivery Service does not support specifying a resource ARN in the Resource element of an IAM policy statement. To allow access to Amazon Message Delivery Service, specify “Resource”: “*” in your policy.

### Expected Behavior

KICS should not flag this as a critical SAST finding, because AWS's recommended (and, in fact, the only) way to allow actions on these resources in an IAM policy is by using `"Resource": "*"`

### Actual Behavior

KICS flags these policies as critical vulnerabilities

### Example policy that gets flagged but should not:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
        "Effect": "Allow",
        "Action": [
            "ec2messages:*"
        ],
        "Resource": "*"
    }
  ]
}
```

**Comment by cxMiguelSilva** [comment]
Hi @adamkendall1, hope you are doing great!
First of all, thank you for all the issues that you have found and reported!
Regarding this issue, I'm glad to inform you that PR #5728 aims to solve it.
Keep up the great work!

**Comment by adamkendall1** [comment]
Thanks! I'll keep 'em coming if I find any more.

Much appreciated!
