### ISSUE TITLE
Support IAM Identity Center (successor to AWS Single Sign-On) Resources

### ISSUE THREAD

**Issue by jsimoni** [Checkmarx/kics#5801]
**Is your feature request related to a problem? Please describe.**
There are a number of great [queries defined for IAM Role & Policies](https://github.com/Checkmarx/kics/tree/master/assets/queries/terraform/aws) however, as AWS recommends the use of IAM Identity Center (successor to AWS Single Sign-On) kics should support queries that analyze Terraform code that defines SSO Permission Sets (those SSO Permission Sets ultimately end up as Roles & Policies in targeted AWS Accounts.)

**Describe the solution you'd like**
Queries that assess SSO Permission Sets.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rafaela-soares** [comment]
Hello @jsimoni!

Thank you so much for using KICS and suggesting this feature! We will take a look as soon as possible!

**Comment by cxMiguelSilva** [comment]
Hi @jsimoni, hope you are doing great!
I am glad to inform you that this issue is being addressed in PR #6096.
Thank you so much for this feature request!
