### ISSUE TITLE
Open API queries - 'default' response type is not handled

### ISSUE THREAD

**Issue by shiftleftorca** [Checkmarx/kics#5805]
Query "Responses With Wrong HTTP Status Code (v3)" checks for int response (in the range of [200-599]) **while 'default' is a valid option**

See https://swagger.io/docs/specification/describing-responses/
<img width="794" alt="image" src="https://user-images.githubusercontent.com/101038122/190922813-b23c40b8-35d0-46d3-8422-2a4925832bf0.png">

**Comment by cxMiguelSilva** [comment]
Hi @shiftleftorca, hope you are doing great!
The security was adapted to not be triggered by the 'default' value in #5834
Thank you so much for your input!
