### ISSUE TITLE
Need refresh checkmarx/kics:gh-action

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#5807]
I would like to test the KICS 1.6 features (auto-remediation sounds really cool) on my use-cases but the `checkmarx/kics:gh-action` isn't updated.

```bash
$ docker run checkmarx/kics:gh-action version
Keeping Infrastructure as Code Secure v1.5.15
```

**Comment by nunoocx** [comment]
@jycamier we will update it ASAP

**Comment by gabriel-cx** [comment]
Hi @jycamier,

Thank you for your feedback!

I'm happy to announce that you can now use the **v1.6 of our GitHub Action** ( checkmarx/kics:gh-action-kics1.6 ).
With this, you can now test KICS 1.6 features on your use-cases.

Hope this is good news for you!
If so, kindly close this issue. But if you still need more support from our side, feel free to contact me directly.

**Comment by jycamier** [comment]
Excellent ! Now Let's rock 🎸

**Comment by jycamier** [comment]
Hi @gabriel-cx 

I think your tags on `Checkmarx/kics-github-action` are wrong : 
- `checkmarx/kics:gh-action-kics1.6` is used on `master` branch
- `checkmarx/kics:gh-action` is used on  `v1.6` and `v1` tags

**Comment by gabriel-cx** [comment]
Hi @jycamier 

You right! Thank you for your feedback on this!
Kindly double check on your side to see if everything is better now. 🙌

**Comment by jycamier** [comment]
Awesome !
Thank you so much for the quality of the answer ! 👍 

I close this issue.
