### ISSUE TITLE
Masked Secrets - it works but...

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#5850]
The Secrets are now masked in the HTML report 🎉🎉🎉  but in the report you display : 
- the line before
- the concerned line
- the line after

If the lines before and after are some clear secrets, these secrets are displayed !

![image](https://user-images.githubusercontent.com/984570/192826630-845dca87-b707-4e2b-bc1e-c10fa7842733.png)

**Comment by cxMiguelSilva** [comment]
Hi @jycamier hope you are doing great!
I am glad to inform you that this issue is being solved in #5949.
Thank you so much for another great feedback!!
