### ISSUE TITLE
query assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda trigger false positive

### ISSUE THREAD

**Issue by jycamier** [Checkmarx/kics#5859]
The query `assets/queries/terraform/aws/hardcoded_aws_access_key_in_lambda` trigger some false positive.

The query seems to be too large in terme of access key detection.

**Comment by rafaela-soares** [comment]
Hello @jycamier

Thank you so much for bringing this to our attention. We will take a look 😊

**Comment by rafaela-soares** [comment]
Hello again @jycamier

We decided to use the same regex as `Passwords And Secrets - AWS Access Key`: `(A3T[A-Z0-9]|AKIA|ASIA)[A-Z0-9]{16}`.

Hope that it will reduce the noise. PR [#5951](https://github.com/Checkmarx/kics/pull/5951) addresses it.

**Comment by jycamier** [comment]
Thank you @rafaela-soares !
