### ISSUE TITLE
Wrong link for documentation on Passwords And Secrets

### ISSUE THREAD

**Issue by pascalrobert** [Checkmarx/kics#5934]
### Expected Behavior

Having a link to explain in details the "Passwords And Secrets" query

### Actual Behavior

The link to the documentation is https://kics.io/ instead of the actual documentation

### Steps to Reproduce the Problem

1.  Go to https://docs.kics.io/latest/queries/all-queries/
2.  In Platform, search for Common
3.  Click on Documentation
4. Link is sending us to the main page of kics.io

**Comment by cxMiguelSilva** [comment]
Hi @pascalrobert hope you are doing great!
I'm glad to inform you that the issue present in the Password and Secrets Security Query Metadata is being addressed in #5938
The listing in https://docs.kics.io/latest/queries/all-queries/ will be updated once KICS v1.6.3 is released. 
Thank you so much for your input!
