### ISSUE TITLE
Using Kics Query to detect admin policy attached to a Permission set - AWS SSO

### ISSUE THREAD

**Issue by drey0143143** [Checkmarx/kics#5961]
I'm new to Kics, I would like to know what version of Kics will scan if admin policy is attached to a permission set for AWS SSO.

**Comment by rafaela-soares** [comment]
Hello @drey0143143,

Thank you so much for using KICS and contacting us 🚀 

AWS SSO is now AWS IAM Identity Center, as explained in the [AWS documentation](https://aws.amazon.com/about-aws/whats-new/2022/07/aws-single-sign-on-aws-sso-now-aws-iam-identity-center/?nc1=h_ls). KICS already have a query (_"IAM Policies With Full Privileges"_) that verifies if admin privileges are attached to IAM policies. It is available for [Ansible](https://github.com/Checkmarx/kics/tree/master/assets/queries/ansible/aws/iam_policy_grants_full_permissions), [CloudFormation](https://github.com/Checkmarx/kics/tree/master/assets/queries/cloudFormation/aws/iam_policies_with_full_privileges), and [Terraform](https://github.com/Checkmarx/kics/tree/master/assets/queries/terraform/aws/iam_policies_with_full_privileges).

Please, let us know if this query fits your needs. If not, provide us more information 😊

**Comment by drey0143143** [comment]
Hello @rafaela-soares,
do you have any update on this feature request?

**Comment by cxMiguelSilva** [comment]
Hi @drey0143143, hope you are doing great!
I am very happy to let you know that this issue is being addressed in PR https://github.com/Checkmarx/kics/pull/6096.
Thank you so much for this feature request!

**Comment by drey0143143** [comment]
@cxMiguelSilva Thanks for the feat added. when I use checkmarx/kics-github-action@v1.6.9 in my workflow, it failed. how do I fix this?

**Comment by cxMiguelSilva** [comment]
Hi @drey0143143 hope you are doing great!
The KICS github action version does not follow the KICS release version names. You need to use a version for the kics-github-action. The KICS github action v1.6 is currently using the 1.6.6 version. We will update it to a newer version asap.

**Comment by drey0143143** [comment]
@cxMiguelSilva Kindly let me know when the upgrade is done

**Comment by drey0143143** [comment]
@cxMiguelSilva How are you doing? do you have a time frame when the KICS github action version will be updated to support the feature requests supported in Checkmarx/kics@v1.6.9 . I saw that there is an updated v1.6.3 for kics-github-action

**Comment by kaplanlior** [comment]
The github action now uses KICS 1.6.11.

**Comment by drey0143143** [comment]
@kaplanlior thanks for your response. I have updated github action KICS to the latest version but only IAM policies query is running against the policies attached to a PermissionSet with admin access. how do I get Kics to run all of the SSO & IAM queries?

**Comment by cxMiguelSilva** [comment]
Hi @drey0143143,
Sorry for the late response. The SSO Security Queries should be running if you are using the latest KICS gh action. Would you care to provide a sample in order to test on our side and find the problem?

**Comment by drey0143143** [comment]
@cxMiguelSilva thanks for your response - I'm trying to install KICS locally to find out why SSO security Queries is not checking the TF configuration and its only IAM Policies Security check that is identifying issues. I am receiving the following error message : I have installed docker and its enabled

```
[INFO - 9:52:03 AM] Opened a supported file by KICS. Starting KICS scan
[ERROR - 9:52:03 AM] Error: Check container engine state. Failed: exit status 126

[INFO - 10:03:42 AM] Opened a supported file by KICS. Starting KICS scan
[ERROR - 10:03:42 AM] Error: Check container engine state. Failed: exit status 126

[INFO - 10:03:48 AM] File saved updating KICS results
[ERROR - 10:03:48 AM] Error: Check container engine state. Failed: exit status 126

**Comment by drey0143143** [comment]
@cxMiguelSilva here is an example ... when I run KICS against the below code .the only findings seem to be related to “IAM policies shouldn't allow full administrative privileges (for all resources)” ,SSO Policy with full privileges did not run

```
data "aws_ssoadmin_instances" "example" {}

resource "aws_ssoadmin_permission_set" "example" {
  name         = "kics-sso-scan"
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}

data "aws_iam_policy_document" "example" {
  statement {
    sid = "1"

    actions = [
      "*",
    ]

    resources = [
      "arn:aws:s3:::*",
    ]
  }
}

resource "aws_ssoadmin_permission_set_inline_policy" "example" {
  inline_policy      = data.aws_iam_policy_document.example.json
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = aws_ssoadmin_permission_set.example.arn
}

**Comment by drey0143143** [comment]
@cxMiguelSilva how are you? were you able to go through the example provided for my use case?
