### ISSUE TITLE
False positive on Unpinned Package Version in Apk Add result when libstdc++ is pinned

### ISSUE THREAD

**Issue by tspearconquest** [Checkmarx/kics#6000]
Found a bug? You're welcome to [![GitHub Discussions](https://img.shields.io/badge/chat-discussions-blue.svg?style=flat-square)](https://github.com/Checkmarx/kics/discussions)

- **Please make sure to:**
  - Describe in details what the problem is
  - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG`)
  - Attach the scanned sample files, anonymize the data if the original file cannot be provided
  - When attaching files to the issue make sure they are properly formatted

### Expected Behavior
KICS should report no finding

### Actual Behavior
KICS reports Unpinned Package Version in Apk Add

Removing the `++` from the `libstdc++` package makes the results come out correctly, but then the package cannot be installed.

I tried to fix it locally in the `libraries/dockerfile.rego` in the `withVersion` rules but failed to find a working regex even after validating that the string in step 2 below validates properly at regexpal.com with the following regex: `[A-Za-z0-9_+-]+=(.+)`

You can see it doesn't validate in the below screenshot with the rule in the master branch, as the text is not highlighted by the linter:
![image](https://user-images.githubusercontent.com/81998567/201556882-9a109848-8b7b-4a2d-ab9f-049746b2b262.png)

You can see that it validates properly when removing the `++` part from `libstdc++` with the same rule, as the text is now highlighted by the linter:
![image](https://user-images.githubusercontent.com/81998567/201557063-73d19c32-9a78-4c6b-8352-1d8d9f93d1f3.png)

Finally, you can see it validates with the `++` part in `libstdc++` once I add the `+` character in between `_-` as in the regex above, as the text is highlighted by the linter:
![image](https://user-images.githubusercontent.com/81998567/201556954-7c63bdd4-47f8-45ab-af85-f0a6b6277748.png)

Please help me to find the right fix.

### Steps to Reproduce the Problem
1.  Create a Dockerfile based on Alpine
2.  Add `RUN apk --quiet --update --no-cache add libstdc++==11.2.1_git20220219-r2`
3.  Run `kics scan --config configfile.yaml`

### Specifications
(N/A if not applicable)

-   Version: 1.2.6
-   Platform: MacOS
-   Subsystem: dockerfile?

**Comment by cxMiguelSilva** [comment]
Hi @tspearconquest, hope you are doing great!
Thank you for finding another bug in our security queries 🚀
The change that you mentioned above fixes the problem and it is already being applied in #6006. 
Can we add your RUN command to our negative test cases?

**Comment by tspearconquest** [comment]
Yes you may, thank you for the fix!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
