### ISSUE TITLE
Helm files are not scanned when using certain chart names

### ISSUE THREAD

**Issue by gabgaudreau** [Checkmarx/kics#6011]
Running the checkmarx/kics scan command on 2 helm charts, both helm charts are identical except for the Chart.Name property as well as throughout the _helpers.tpl results in one chart getting scanned correctly while the other is not scanned at all.

### Expected Behavior

Both charts should be scanned correctly regardless of what the chart name is.

### Actual Behavior

helm-patate chart is scanned properly. ([scan-patate.txt](https://github.com/Checkmarx/kics/files/10071340/scan-patate.txt))
helm-users chart is not scanned at all. ([scan-users.txt](https://github.com/Checkmarx/kics/files/10071339/scan-users.txt))

### Steps to Reproduce the Problem

Commands used:
For the helm-patate chart ([helm-patate.zip](https://github.com/Checkmarx/kics/files/10071358/helm-patate.zip)):
`docker run --rm -v /path-to-chart/helm-patate:/src -v /path-to-results/results:/results checkmarx/kics scan -v --log-level trace -p /src -o /results/ --report-formats json --type Dockerfile,Kubernetes,Terraform --ignore-on-exit results`

For the helm-users chart ([helm-users.zip](https://github.com/Checkmarx/kics/files/10071356/helm-users.zip)):
`docker run --rm -v /path-to-chart/helm-users:/src -v /path-to-results/results:/results checkmarx/kics scan -v --log-level trace -p /src -o /results/ --report-formats json --type Dockerfile,Kubernetes,Terraform --ignore-on-exit results`

Names found to result in failed scans so far are: "users", "registration", "clientportal"

### Specifications

-   Version: Latest
-   Platform: Linux

**Comment by cxMiguelSilva** [comment]
Hi @gabgaudreau, hope you are doing great!
I am glad to inform you that this issue is being addressed in #6024. 
The problem was caused due a bug in our helm resolver.
Thank you for reporting this issue 🙂
