### ISSUE TITLE
Duplicate similarity_id for 2 resource types in the same file

### ISSUE THREAD

**Issue by niro-lightspin** [Checkmarx/kics#6103]
Not sure if that's a bug but we found a duplicate similarity_id for 2 resource types in the same file

> {
	"query_name": "ServiceAccount Allows Access Secrets",
	"query_id": "056ac60e-fe07-4acc-9b34-8e1d51716ab9",
	"query_url": "https://kubernetes.io/docs/reference/access-authn-authz/rbac/",
	"severity": "MEDIUM",
	"platform": "Kubernetes",
	"category": "Secret Management",
	"description": "Roles and ClusterRoles when binded, should not use get, list or watch as verbs",
	"description_id": "79619280",
	"files": [
		{
			"file_name": "../ingress_takeover.yaml",
			"similarity_id": "97148540dde559c5d4cdf9770ea286105f13c07626bb1f29120eefe69790c54d",
			"line": 51,
			"resource_type": "ClusterRole",
			"resource_name": "ingress-nginx",
			"issue_type": "IncorrectValue",
			"search_key": "metadata.name={{ingress-nginx}}.rules",
			"search_line": 0,
			"search_value": "",
			"expected_value": "The metadata.name={{ingress-nginx}}.rules.verbs should not contain the following verbs: [[\"list\", \"watch\"]]",
			"actual_value": "The metadata.name={{ingress-nginx}}.rules.verbs contain the following verbs: [[\"list\", \"watch\"]]"
		},
		{
			"file_name": "../ingress_takeover.yaml",
			"similarity_id": "97148540dde559c5d4cdf9770ea286105f13c07626bb1f29120eefe69790c54d",
			"line": 51,
			"resource_type": "Role",
			"resource_name": "ingress-nginx",
			"issue_type": "IncorrectValue",
			"search_key": "metadata.name={{ingress-nginx}}.rules",
			"search_line": 0,
			"search_value": "",
			"expected_value": "The metadata.name={{ingress-nginx}}.rules.verbs should not contain the following verbs: [[\"get\", \"list\", \"watch\"]]",
			"actual_value": "The metadata.name={{ingress-nginx}}.rules.verbs contain the following verbs: [[\"get\", \"list\", \"watch\"]]"
		}
	]
}

**Comment by cxMiguelSilva** [comment]
Hi @niro-lightspin, hope you are doing great!
I am glad to inform you that this issue is being addressed in #6111.
The similarity id was the same for the results because the similarity id is [computed using the path, query id, and search key](https://github.com/Checkmarx/kics/blob/master/pkg/engine/similarity/similarity_id.go#L26) which were the same for those 2 results.
Thank you so much for finding this bug.
