### ISSUE TITLE
kick-scan ignore does not work for certain queries

### ISSUE THREAD

**Issue by YYx00xZZ** [Checkmarx/kics#6104]
I have terraform file with kubernetes cluster definition. At the begging of the file I am declaring that I want to disable the following queries:

`# kics-scan disable=9192e0f9-eca5-4056-9282-ae2a736a4088`

`# kics-scan disable=11e7550e-c4b6-472e-adff-c698f157cdd7`

`# kics-scan disable=65c1bc7a-4835-4ac4-a2b6-13d310b0648d`

### Expected Behavior
None of the ignored queries should run.

### Actual behavoir:
Only the second query is disabled. The first and the third are runned and results in errors.

### Steps to Reproduce the Problem
Scan terraform project with the following command

`kics scan -p $(pwd) -o "$(pwd)"§`

-   Version: kics 1.6.8
-   Platform: Terraform
-   Subsystem: linux

**Comment by cxMiguelSilva** [comment]
Hi @YYx00xZZ , hope you are doing great!
To disable multiple queries in one file you should do it inline like this :
`# kics-scan disable=9192e0f9-eca5-4056-9282-ae2a736a4088,11e7550e-c4b6-472e-adff-c698f157cdd7,65c1bc7a-4835-4ac4-a2b6-13d310b0648d`
If you want to know more about the use of KICS ignore you can find the documentation [here](https://docs.kics.io/latest/running-kics/#using_commands_on_scanned_files_as_comments).
If this does not solve your problem feel free to add more info regarding how you are using KICS to replicate the problem on our side.
Hope this helps. Let me know what you think.

**Comment by YYx00xZZ** [comment]
@cxMiguelSilva I dont know how have I missed that in the docs. Excuse me. Everything is working as expected.
