### ISSUE TITLE
False positive error for environment variable encryption using query `serverless_function_environment_variables_not_encrypted`

### ISSUE THREAD

**Issue by prabhay759** [Checkmarx/kics#6135]
Even though the KMS key exists at the provider level, the Kicks scan returns a false positive error for **serverlessFW** environment variable encryption.Serverless FW let us set the KMS key at the function level as well as the provide level, which sets all functions defined in a serverless yaml file.

More information can be found below as well as [here](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml)
![image](https://user-images.githubusercontent.com/15219054/216588208-6cfeee35-51bb-4e13-8394-2f34d917e579.png)

### Possible Fix

We should do a lookup of  **kmsKeyArn** at _provider_ level before checking at _function_ level, something like this:

**not common_lib.valid_key(document.provider, "kmsKeyArn") or not common_lib.valid_key(function, "kmsKeyArn")**

https://github.com/Checkmarx/kics/blob/master/assets/queries/serverlessFW/serverless_function_environment_variables_not_encrypted/query.rego#L11
 

### Expected Behavior

When the KMS key is set at the provider level in this manner, there must not be an error: 
![image](https://user-images.githubusercontent.com/15219054/216588692-fa3db9b9-0081-4cce-bc9a-ccddf7257b55.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/15219054/216590104-7638fd3e-9583-4a70-8b11-0b874fb738fb.png)

### Steps to Reproduce the Problem
In order to produce the error using below Serverless config:
![image](https://user-images.githubusercontent.com/15219054/216588924-259073a3-0fdf-482e-9a02-5c0d84c6a7ce.png)

**Comment by cxMiguelSilva** [comment]
Hi @prabhay759, 
I am glad to inform you that this issue is being addressed in #6136.
Thank you for reporting this issue.

**Comment by prabhay759** [comment]
@cxMiguelSilva Thank you!
