### ISSUE TITLE
Support "Passwords And Secrets" query for Google API key and AWS access key in Dockerfile

### ISSUE THREAD

**Issue by bqcuong** [Checkmarx/kics#6183]
### Platform
Dockerfile

### Provider
* AWS
* Google API

### Description
`AWS_ACCESS_KEY` and `GOOGLE_API_KEY` are the sensitive information, it should not be hard-coded in the Dockerfile for best practices. So far, I have not seen that KICS supports the detection of these secrets.

```
FROM scratch

ENV AWS_ACCESS_KEY="token_A3Tf2a1dc71232943330" \
    GOOGLE_API_KEY="token_A3Tf2a1dc71232943330"
```

**Comment by cxMiguelSilva** [comment]
Hi @bqcuong,
KICS already does secret detection for the cases you mentioned.
[GOOGLE_API_KEY](https://github.com/Checkmarx/kics/blob/master/assets/queries/common/passwords_and_secrets/regex_rules.json#L149 )
[AWS_ACCESS_KEY](https://github.com/Checkmarx/kics/blob/master/assets/queries/common/passwords_and_secrets/regex_rules.json#L77)
Let us know what you think and if it solves your issue,

**Comment by bqcuong** [comment]
Hi @cxMiguelSilva,

Thanks for your response.
I found that in these cases, KICS detects smells based on the values of the environment variables, but not by the key names ([regex_rules.json#L79](https://github.com/Checkmarx/kics/blob/master/assets/queries/common/passwords_and_secrets/regex_rules.json#L79)).
For instance, the variable value I provided `token_A3Tf2a1dc71232943330` did not match the regex in [regex_rules.json#L79](https://github.com/Checkmarx/kics/blob/master/assets/queries/common/passwords_and_secrets/regex_rules.json#L79) so KICS ignored it.
