### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by kaplanlior** [Checkmarx/kics#6211]
For KICS 1.6.x the docker images size is around 1 GB. 
Our goal is to reduce the image size or offer another image with extended abilities / files.

Removing terraformer would save ~ 900 MB
60	terraform binary
460	terraform providers
380	terraformer binary

Taking into account we might want to keep the terraform binary for future uses.

**Comment by davidjeddy** [comment]
[`tfenv`](https://github.com/tfutils/tfenv) is a great solution for using multiple terraform binary versions. This would reduce the size of the KICS image while maintaining TF binary version compatability.
