### ISSUE TITLE
Ignore .terra* cache directories by default globally

### ISSUE THREAD

**Issue by davidjeddy** [Checkmarx/kics#6217]
**Is your feature request related to a problem? Please describe.**
When running KICS the Terraform module cache directories are scanned by default. Most consumers of modules have little to no ability to change a 3rd part module. 

**Describe the solution you'd like**
By default KICS should ignore `**/.terra*` when executing a `scan`. This would ignore both .terraform and .terragrunt cache directories that are present in module Terraform deployment modules.

**Describe alternatives you've considered**
Currently using `--exclude-paths ".terra*, ./.terra*, ./**/.terra*, .terra*/*, ./.terra*/*, ./**/.terra*/*", ...". This is functional but contrived.

**Additional context**

The full command:

```
kics scan \
        --cloud-provider "aws" \
        --exclude-paths ".terra*, **/.terra*" \
        --no-color \
        --path "." \
        --queries-path "$PATH_TO/assets/queries" \
        --type "Terraform" \
        --verbose
```

**Comment by cxMiguelSilva** [comment]
Hi @dim-ops, 
Of course! Take the lead! 
In case you need any help do not hesitate to ask!
