### ISSUE TITLE
Potentially wrong queries

### ISSUE THREAD

**Issue by giladshahar** [Checkmarx/kics#6233]
there are existing queries that point out non-issues.
specifically, having requests.memory/cpu != limits.memory/cpu is not an issue (but a best practice).
resource limits are supposed to help users avoid OOM/throttling, while resource requests make sure resources are actually allocated for the containers.

even in the [https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/](link attached) as help for these queries, the example shows limits>requests.

### Expected Behavior
containers having requests.memory/cpu != limits.memory/cpu will not trigger an issue.

queries:

aafa7d94-62de-4fbf-8838-b69ee217b0e6
9d43040e-e703-4e16-8bfe-8d4da10fa7e6
aee3c7d2-a811-4201-90c7-11c028be9a46

should be removed

### Actual Behavior

containers having requests.memory/cpu != limits.memory/cpu trigger an issue.

**Comment by kaplanlior** [comment]
Do you suggest to to remove these queries or change their severity (e.g. informational) ?

**Comment by giladshahar** [comment]
well I'd remove them

**Comment by gabriel-cx** [comment]
Hi @giladshahar ,

Thank you for your inputs on this.
We asked our AppSec team to have a look on this. We will update you asap.

(APPSEC-2347)
