### ISSUE TITLE
Mask secrets in code snippets even with --disable-secrets

### ISSUE THREAD

**Issue by ayala-orca** [Checkmarx/kics#6264]
Currently, when a scan is set up to detect both vulnerabilities and secrets, if a vulnerability code snippet includes a secret, the secret will be masked:
```
Cluster Master Authentication Disabled, Severity: HIGH, Results: 1
...

	[1]: ../../path/myconfig.tf:7

		005:   initial_node_count = 3
		006:
		007:   master_auth {
		008:     username = ""
		009:     password = <SECRET-MASKED-ON-PURPOSE>
```

However, if the --disable-secrets flag is used, the secrets in the vulnerability code snippet are displayed in plain text:
```
Cluster Master Authentication Disabled, Severity: HIGH, Results: 1
...

	[1]: ../../path/myconfig.tf:7

		005:   initial_node_count = 3
		006:
		007:   master_auth {
		008:     username = ""
		009:     password = "root"
``` 

 It can be useful to have the ability to mask secrets in vulnerable code snippets even when the --disable-secrets option is enabled.

**Comment by nunoocx** [comment]
Hi @ayala-orca , thanks for your suggestion,
We can do this by default, but we will need to run all secret queries under the hood anyway to detect and mask the secrets.
We can do the following:
1. the default is the same: always run secret queries and mask secrets when displaying them
2. the `--disable-secrets` behavior remains the same: don't run secret queries and therefore display them
3. add a new flag, e.g.,  `--always-mask-secrets` that changes the behavior of `--disable-secrets` by making the queries run under the hood, hide the results but mask the detected secrets when they are displayed in other queries.

WDYT?

**Comment by lior-orca** [comment]
@nunoocx 
The direction sounds right.
i do think the following, for bullet 3, will improve the performance and scan time - 
If only masking is needed, do not perform a full secret scan. Instead scan only files with issues (or, only the code snippets, but this is probably much harder to achieve)

**Comment by nunoocx** [comment]
@lior-orca that's actually a good idea!
Thanks for the suggestion.

**Comment by gabriel-cx** [comment]
Hi @ayala-orca  @lior-orca ,

Right now we decided to move with this functionality without adding a new flag.
The current behavior is:

- If user **uses** `--disable-secrets`, KICS will not perform a full secret scan but will mask the secrets on the preview lines.

- If user do **not use** `--disable-secrets`, KICS will keep the default behavior (will run a full secret scan + masking secrets).

Kindly open a discussion if you think that adding a new flag can bring some advantages.

Cc: @nunoocx
