### ISSUE TITLE
CIS description not fetched

### ISSUE THREAD

**Issue by prathamesh-parekh** [Checkmarx/kics#6299]
### Platform Terraform
*(e.g. Terraform, Ansible, etc.)*

### Provider AWS
*(e.g. AWS, Azure, GCP, etc.)*

### Description
How do I fetch CIS description? I am running the scan and have internet connectivity in my system, However CIS information like description, title is not being fetched by the tool

**Comment by prathamesh-parekh** [comment]
How do I configure the BaseURL to fetch the CIS details ? 
Which URL do I have to configure, and how do I get access to that URL ?

**Comment by kaplanlior** [comment]
Hi,

We've stopped using CIS descriptions since version 1.7.0.

For earlier version the mechanism is still there but is expected to return  empty results.
CC @gabriel-cx
