### ISSUE TITLE
Add an option to override the max size limit file

### ISSUE THREAD

**Issue by roi-orca** [Checkmarx/kics#6306]
Currently, the max size limitation of a file is [5MB](https://github.com/Checkmarx/kics/blob/0bb5fa7b441ba1b8189757aba6506aeda8f01ee9/pkg/kics/service.go#L133)

When trying to scan a plan upon terraform post plan stage we failed due to this constraint.

**Suggestion**
Add the ability to override the max size limit of file with a specific flag (e.g. --max-file-size) to allow dynamically change this configuration.

We can work on it and contribute to the change, if we have the approval.

**Comment by lior-orca** [comment]
@cxMiguelSilva, @kaplanlior please give a 👍 and we can take it

**Comment by gabriel-cx** [comment]
Hi @roi-orca @lior-orca ,

The suggestion sounds good!
Feel free to take it, and thanks in advance! :D

**Comment by kaplanlior** [comment]
Cool, go ahead. 

I'm curious how increasing the limitation would effect performance. But, if it's a parameter, that's up to the user to consider.  I would suggest to give a warning if case the file is over the limit with the possibility to use the new flag to override.
