### ISSUE TITLE
Gitlab SAST schemas version 14.x.x have been deprecated

### ISSUE THREAD

**Issue by stegojulia** [Checkmarx/kics#6318]
Hi everyone, [SAST schemas version 14.x.x have been deprecated ](https://docs.gitlab.com/ee/update/deprecations.html#security-report-schemas-version-14xx) in version 15.8, starting from Gitlab version 16.0 that is now causing an error.

https://github.com/Checkmarx/kics/blob/4e841b2abc0b387c2df38549cabdc457152e7c9d/pkg/report/model/gitlab_sast.go#L90
is using version "14.0.1". Latest version is 15.04, all versions from 15.00 are supported.

**Comment by kaplanlior** [comment]
Thanks for the report. Do we need to change anything more or just that version?

Do you want to also create the pull request to fix this ?

**Comment by kaplanlior** [comment]
> Thanks for the report. Do we need to change anything more or just that version?
@stegojulia Can you help us here ?

**Comment by stegojulia** [comment]
I tried updating the version but have now realised that there have been some changes to the schema that include both new required and deprecated fields. I will try and sort that in the next few days.
