### ISSUE TITLE
Where are the release binaries?

### ISSUE THREAD

**Issue by danielbraun89** [Checkmarx/kics#6336]
### Expected Behavior

Per the docs:
https://docs.kics.io/1.3.0/getting-started/#binary
releases should have binaries based on OS

### Actual Behavior

no binaries in releases page
https://github.com/Checkmarx/kics/releases

**Comment by nunoocx** [comment]
@danielbraun89 as of 1.5.1 we discontinued the binary releases.
We encourage you to use our docker-based images.
If you need a binary you can still [build it from the sources](https://docs.kics.io/latest/documentation/#build_from_sources). We will be glad to help in case you find any trouble.

**Comment by kaplanlior** [comment]
And the announcement back than: https://github.com/Checkmarx/kics/discussions/4744

**Comment by danielbraun89** [comment]
Thanks for the clarification!
