### ISSUE TITLE
File requirements used in pip install not checked ?

### ISSUE THREAD

**Issue by liloumuloup** [Checkmarx/kics#6341]
Found a bug? You're welcome to [![GitHub Discussions](https://img.shields.io/badge/chat-discussions-blue.svg?style=flat-square)](https://github.com/Checkmarx/kics/discussions)

- **Please make sure to:**
  - Describe in details what the problem is
  - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG`)
  - Attach the scanned sample files, anonymize the data if the original file cannot be provided
  - When attaching files to the issue make sure they are properly formatted

### Expected Behavior

(Which results are expected from KICS?)

* File pip_requirements.txt checked
* No trigger for rule `02d9c71f-3ee8-4986-9c27-1a20d0d19bfc`

### Actual Behavior

(Formatted logs and samples helps us to better understand the issue)

I'm trying to fix some KICS rules at this moment and i have some troubles with this one : `02d9c71f-3ee8-4986-9c27-1a20d0d19bfc` that is present in my results but i pinned all the packages in my file `pip_requirements.txt` used in my dockerfile. KICS is executed in a Github action here.

* KICS command launch by my Github action :
```
15:38 - INF : kics command kics -p .cloud,inventories,playbooks -o ./ --report-formats json,json   --config /github/home/merged_assets/kics-config.yaml       -q /github/home/merged_assets/queries/  --ignore-on-exit results --fail-on high
```
* Command used in the dockerfile to install python packages : 
```
RUN pip3 install --no-cache-dir -r pip_requirements.txt
```
* File `pip_requirements.txt` : 
```
ansible-lint==6.0.2
ansible==7.5.0
jinjalint==0.5
jmespath==1.0.1
molecule==3.6.1
molecule-docker==1.1.0
netaddr==0.8.0
yamllint==1.30.0
```

* Debug output in my CI (i censored the parts where i'm unsure if it's sensitive or not) :
```
		{
			"query_name": "Unpinned Package Version in Pip Install",
			"query_id": "02d9c71f-3ee8-4986-9c27-1a20d0d19bfc",
			"query_url": "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/",
			"severity": "MEDIUM",
			"platform": "Dockerfile",
			"category": "Supply-Chain",
			"description": "Package version pinning reduces the range of versions that can be installed, reducing the chances of failure due to unanticipated changes",
			"description_id": "37db3a53",
			"files": [
				{
					"file_name": ".cloud/docker/Dockerfile",
					"similarity_id": "<censored>",
					"line": 17,
					"issue_type": "IncorrectValue",
					"search_key": "FROM={{<censored>/ubuntu:22.04}}.{{RUN pip3 install --no-cache-dir -r pip_requirements.txt}}",
					"search_line": 0,
					"search_value": "",
					"expected_value": "RUN instruction with 'pip/pip3 install \u003cpackage\u003e' should use package pinning form 'pip/pip3 install \u003cpackage\u003e=\u003cversion\u003e'",
					"actual_value": "RUN instruction pip3 install --no-cache-dir -r pip_requirements.txt does not use package pinning form"
				}
			]
		},
```

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  Create a dockerfile Ubuntu22.04
2.  Add the command pip to install the packages from pip_requirements.txt file
3.  Launch KICS scan

### Specifications
(N/A if not applicable)

-   Version:  v1.6.13
-   Platform: Github Action
-   Subsystem: Docker

**Comment by felipeng** [comment]
I am running KICS 1.7.3 and still have this bug
