### ISSUE TITLE
"kics-scan ignore" doesn't work as expected

### ISSUE THREAD

**Issue by EsDmitrii** [Checkmarx/kics#6458]
Hi!
I use Gitlab CI and Helm to prepare manifests for my multiple env Kubernetes infrastructure.
I run kics in Gitlab CI using official docker image `checkmarx/kics:latest` this way, like in docs:
```
kics scan -q /app/bin/assets/queries/common/passwords_and_secrets -p $(pwd) -o $(pwd) --output-name kics-result --config=.kics-config.yaml --fail-on high,medium,low --report-formats "json,glsast" --no-progress
```
We started to use Kics to prevent secrets being in a rendered files by Helm.
What I noticed: 
1. "kics-scan ignore" works when it is placed on the top of the file. It should be really the FIRST line, even before the Helm comments.
I render multiple the same kind Kubernetes entities into one file using helm, example: 
<img width="757" alt="Screenshot 2023-06-19 at 20 45 58" src="https://github.com/Checkmarx/kics/assets/124890665/9cefd521-f4c5-4330-9659-6152fbd9d7c2">

2. "kics-scan ignore-block" works only from the root of the block, i.e. if you want to exclude a nested block - you get troubles

3. "kics-scan ignore-line" also works weird, but only if the yaml is "clean". He does not perceive what is transmitted after | or >, example:
this works
```
deploy:
  # kics-scan ignore-line
  my-super-token: 123
```
and this doesn't work
```
deploy: |
  # kics-scan ignore-line
  my-super-token: 123
```
real file I have problems with (lines before and after are deleted , but it doesn't change the essence):
<img width="507" alt="Screenshot 2023-06-19 at 21 01 35" src="https://github.com/Checkmarx/kics/assets/124890665/5161b25a-b2e7-4327-8b94-6a1344749714">
<img width="512" alt="Screenshot 2023-06-19 at 21 03 30" src="https://github.com/Checkmarx/kics/assets/124890665/9fa6aabc-1115-4771-9ddd-ed6995094c73">

4. We have a lot false alarms due to kics get triggered on vars names by hardcoded pattern, it don't analyse what inside this var. So for example as you can see I have four vars with "token" word in name, but kics alerts only for two of them (and ignores the "# kics-scan ignore-line" comment). 
<img width="944" alt="Screenshot 2023-06-19 at 21 21 40" src="https://github.com/Checkmarx/kics/assets/124890665/f7897ba1-aebd-4f1b-a9d4-64548890bdb0">

Kics's alert for 21 line of code is false alarm because there is no token or really sensitive data inside
But Kics's alert for 21 line of code is expected true, because there is sensitive data inside (but it should ignore this line due to special comment before)

5. It is related to previous point, due to names of files to which kics is triggered are hardcoded, so developers prefer to rename var names instead of to fix the issue and hide a secret to some vaults.

var name with "token" word
<img width="946" alt="Screenshot 2023-06-19 at 21 12 18" src="https://github.com/Checkmarx/kics/assets/124890665/7d4823b6-ae69-4f70-805a-a620060c1631">

var name without "token" word
<img width="657" alt="Screenshot 2023-06-19 at 21 13 44" src="https://github.com/Checkmarx/kics/assets/124890665/94f02f84-5ed7-45e3-9763-369f6c563328">

Maybe I read the documentation badly, or you should complete the documentation it because many things are not entirely clear, or it's still a bug and it needs to be fixed.
Appreciate you for your assistance!

### Specifications

-   Kics version: latest (v1.7.1)
-   Platform: Gitlab

**Comment by kaplanlior** [comment]
The documentation at https://docs.kics.io/latest/running-kics/#using_commands_on_scanned_files_as_comments says
>  kics-scan will not works if there is any valid line above it
(allowing only other comments about the kics-scan)

But your point is valid. I'm flagging this also as a feature request so we'll better support for helm charts and the deployment form you've mentioned.
