### ISSUE TITLE
Kics v1.7.2 fails with panic on a yaml file

### ISSUE THREAD

**Issue by ayala-orca** [Checkmarx/kics#6481]
Running kics on the following yaml file resulted in a panic exception:
```
post:
  tags:
  - "admin"
  summary: "My summary"
  description: "My description"
  responses: 
    200:
      description: |
        ### my description
      content: 
        application/json:
          schema:
            $ref: "my-ref"
```

Command: `docker run -t -v $PWD:/path checkmarx/kics:v1.7.2 scan -p /path/configuration.yaml -o /path --log-level DEBUG`

Results: 
![image](https://github.com/Checkmarx/kics/assets/93713792/6876f7f7-92a2-4765-8546-116526d5be2c)

It looks like the response description causing the issue
```
      description: |
        ### my description
```

**Comment by kaplanlior** [comment]
Thanks for reporting.

Adding regression tag after verifying it works fine with v1.7.1.
