### ISSUE TITLE
Swagger scan findings are shown multiple times

### ISSUE THREAD

**Issue by ayala-orca** [Checkmarx/kics#6484]
Consider the following yaml files:
1. ./test/swagger.yaml
```
openapi: "3.0.0"
info:
  description: "my description"
  version: "1.8.8"
  title: "my title"
servers:
  - url: "http://localhost:3000/"
tags:
- name: "users"
  description: "users tag description"
paths:
  /users/{userId}:
    $ref: "./paths/users/user.yaml"

components: 
  schemas:
    MyResponse:
      $ref: "./schemas/MyResponse.yaml"
``` 
2. ./test/paths/users/user.yaml
```
get:
  tags:
    - "users"
  summary: "Get user"
  responses:
    200:
      description: "Ok"
      content:
        application/json:
          schema:
            $ref: "../../schemas/MyResponse.yaml"
    404:
      description: "not found"
      content:
        application/json:
          schema:
            $ref: "../../schemas/MyResponse.yaml"
```
3. ./test/schemas/MyResponse.yaml
```
properties:
    message:
      type: string
type: object
```

When running `docker run -t -v $PWD:/path checkmarx/kics:v1.7.2 scan -p /path/test` we get the same finding multiple times. For example:
<img width="908" alt="image" src="https://github.com/Checkmarx/kics/assets/93713792/02a82a06-e7d9-4c09-840e-38c5c25c120a">
As you can see, `test/swagger.yaml:13`  appears twice in the results for the same query.

In addition, the above query seems as related to `test/schemas/MyResponse.yaml` but the code snippets are of `test/swagger.yaml:13` and `test/swagger.yaml:18`

**Comment by cx-henriqueAlvelos** [comment]
Hello @ayala-orca
We are working in a new feature that will clarify those references. In this case, there is 2 vulnerabilities in the same line:
- "paths.{{/users/{userId}}}.get.responses.404.content.{{application/json}}.schema.properties.message.type"
- "paths.{{/users/{userId}}}.get.responses.202.content.{{application/json}}.schema.properties.message.type"

It shows that the problem is in `test/swagger.yaml` because you referenced in it `test/schemas/MyResponse.yaml` file

**Comment by ayala-orca** [comment]
Currently, it seems like `./test/schemas/MyResponse.yaml` is being scanned multiple times - once per `ref`.
In some big swagger files, we encountered a serious performance issue - the scan didn't end even after half an hour.
Is this behavior expected to be changed as part of this feature?

**Comment by ayala-orca** [comment]
Thanks @cx-henriqueAlvelos 
Currently, it seems like `./test/schemas/MyResponse.yaml` is being scanned multiple times - once for each reference. We observed a significant performance issue when large swagger files were processed.
Is this behavior expected to be changed as part of this new feature?

**Comment by lior-orca** [comment]
@cx-henriqueAlvelos
can you try to explain a bit more about the suggested direction/solution
e.g. are we aiming to reduce the issues raised to a single one OR have it more accurately surfaced?

**Comment by cx-henriqueAlvelos** [comment]
Hello @lior-orca.
Currently, we are working internally in order to find the best approach
