### ISSUE TITLE
Concurrent Queries Scan

### ISSUE THREAD

**Issue by gabriel-cx** [Checkmarx/kics#6583]
**Is your feature request related to a problem? Please describe.**
This Feature Request is an improvement/enhancement.

**Describe the solution you'd like**
Currently, KICS have [concurrent scans for different platforms](https://docs.kics.io/latest/architecture/#concurrent_scans).
The goal of this Feature Request is to make KICS able to perform concurrent scans over the queries, instead of scan queries in sequence.

**Additional context**
Besides the code implementation, will be necessary to update the [documentation ](https://github.com/Checkmarx/kics/blob/master/docs/architecture.md) in order to mention the new feature.

**Comment by johnnogit** [comment]
Hey @gabriel-cx 
I did a refactoring of the previous work based on this article https://medium.com/@dgravesa/an-openmp-inspired-approach-to-parallelizing-loops-in-go-9d2e984a488c
