### ISSUE TITLE
KICS Violation - Array Items Has No Type (v3) - Schema array items type should be defined - support query

### ISSUE THREAD

**Issue by shijinrajbosch** [Checkmarx/kics#6650]
Hi KICS Team,

I am working in sldt-digital-twin-registry, sldt-bpn-discovery, sldt-discovery-finder and sldt-semantic-hub - Eclipse Tractus-X open-source projects.

We are getting KICS High severity - Array Items Has No Type (v3) even after including the array types in sldt-discovery-finder.

Array Items Has No Type (v3), Severity: HIGH, Results: 2
Description: Schema array items type should be defined
Platform: OpenAPI
Learn more about this vulnerability: https://docs.kics.io/latest/queries/openapi-queries/be0e0df7-f3d9-42a1-9b6f-d425f94872c4

We have defined the "type" to fix the problem in sldt-discovery-finder project . But it is still showing the same error.

1.	sldt-discovery-finder      https://github.com/eclipse-tractusx/sldt-discovery-finder/actions/workflows/kics.yml
2.	sldt-digital-twin-registry https://github.com/eclipse-tractusx/sldt-digital-twin-registry/actions/workflows/kics.yml
3.	sldt-bpn-discovery          https://github.com/eclipse-tractusx/sldt-bpn-discovery/actions/workflows/kics.yml

It will be helpful if you could help us to resolve issue.

We appreciate for all the help and support.

**Comment by shijinrajbosch** [comment]
We found the solution for this . Thanks for the understanding.

**Comment by shijinrajbosch** [comment]
We found a solution for this violation. Thanks for the understanding.

**Comment by gabriel-cx** [comment]
Hi @shijinrajbosch ,

Thanks for your inputs!
