### ISSUE TITLE
bug(queries): scanning custom json files 

### ISSUE THREAD

**Issue by TmmmmmR** [Checkmarx/kics#6777]
I would like to check some attributes in json files which are mandatory. So, I've created a query for that but it seam that's not possible : my files are parsed but nothing happen.

Is it possible to create a query which fit on any JSON file ? How ?

**Comment by kaplanlior** [comment]
KICS works on a variety of known formats and they queries are based on that syntax. 
See https://docs.kics.io/latest/architecture/

If you have your own format you can extend KICS for that as well and have custom queries for it.
Take a look at the parsers kics has at pkg/parser directory for examples.

**Comment by kaplanlior** [comment]
And this is for creating queries on the format KICS already have: https://docs.kics.io/latest/creating-queries/

If you have a specific query question - fill free to reopen this issue.

**Comment by TmmmmmR** [comment]
Thanks for your reply.
Can you point me please to the part of code where it checks if an input file is an openAPI definition ?

**Comment by TmmmmmR** [comment]
Also is there any type of "platform" I can use for a generic json file ? They have no specific format or attributes, they are just valid JSON files.

**Comment by TmmmmmR** [comment]
Hello again @kaplanlior , apparently I can't re open this issue.
Could you please provide me with your thoughts regarding my last question ?
Thanks
