### ISSUE TITLE
bug(parser): poor openapi parsing performance

### ISSUE THREAD

**Issue by leadpogrommer** [Checkmarx/kics#6806]
prepare_sources takes unreasonably long time to parse some openapi json files.
This is caused by two things:
1. [pkg/parser/json/parser.go::Resolve](https://github.com/Checkmarx/kics/blob/c6af14e77c0730b2ad4fe26d897e57c7f44e0780/pkg/parser/json/parser.go#L19)
recursively expands all `$ref`s in json, which significantly increases document size (In my case it went from ~250K to 5.1M).
2. [pkg/parser/json/json_line.go::initializeJSONLine](https://github.com/Checkmarx/kics/blob/c6af14e77c0730b2ad4fe26d897e57c7f44e0780/pkg/parser/json/json_line.go#L37)
has O(len(doc)^2) complexity.

I don't know how to fix the first problem, but I will open PR for second problem soon.

### Expected Behavior
prepare_assets on attached file takes about 10 seconds

### Actual Behavior
parse assets on attached file takes more than 10 minutes (I terminated kics without waiting for it to finish)

### Steps to Reproduce the Problem
1. `kics scan --path death.json -v --profiling CPU`

### Specifications
-   Version: 1.7.11
-   Platform: darwin
-   Subsystem: parser

### Problematic file
[death.json](https://github.com/Checkmarx/kics/files/13373409/death.json)
(This file was created to demonstrate the issue)

**Comment by gabriel-cx** [comment]
Hi @leadpogrommer ,

Thanks for your inputs!

This [PR](https://github.com/Checkmarx/kics/pull/6789) will close the mentioned issue number 1.

**Comment by gabriel-cx** [comment]
@leadpogrommer yes, thank you! we will review and merge it asap.

**Comment by gabriel-cx** [comment]
Hi @leadpogrommer ,

We merged today the PR that fixes the issue number 1 mentioned above.
Feel free to re-open this github issue until we close it with your PR or create a new github issue to tackle the issue number 2.
