### ISSUE TITLE
Add no_platform_flag_with_from query for Docker

### ISSUE THREAD

**Issue by NunoAraujoCX** [Checkmarx/kics#991]
**Platform**
Docker

**Provider**
Dockerfile

**Description**
Check if we are using the --platform flag with FROM

**Comment by takeyourhatoff** [comment]
Hi, can somebody explain how using the --platform flag with FROM is considered a security vulnerability?

**Comment by gabriel-cx** [comment]
Hi @takeyourhatoff ,

Our AppSec team is checking your question and we will update you asap.

(APPSEC-2388)

**Comment by gabriel-cx** [comment]
@takeyourhatoff thanks for your inputs!
I will transmit your point of view to our internal team and we will analyze it carefully.
We will keep you updated.

**Comment by gabriel-cx** [comment]
@takeyourhatoff , our intern Product and AppSec teams analyzed the situation carefully and they decided that we will keep the query as Severity (Info) and Category (Best practices). So, KICS v2.1.0 will start to trigger a notification if you are using "--platform" with "FROM".
